#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PartnerRegistration/PendingPartnerRegistrations.cshtml")]
    public partial class _Views_PartnerRegistration_PendingPartnerRegistrations_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_PartnerRegistration_PendingPartnerRegistrations_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\PartnerRegistration\PendingPartnerRegistrations.cshtml"
      
    ViewBag.Title = "Pending Partner Registration";
    var userRole = ViewBag.UserRole;
    Layout = "~/Views/Shared/_eGateLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 188), Tuple.Create("\"", 260)
, Tuple.Create(Tuple.Create("", 194), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/Model/PendingPartnerRegistrationModel.js")
, 194), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 284), Tuple.Create("\"", 364)
, Tuple.Create(Tuple.Create("", 290), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/ViewModel/PendingPartnerRegistrationViewModel.js")
, 290), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

DefineSection("ko_apply", () => {

WriteLiteral("\r\n    var viewModel = new eGateRoot.PendingPartnerRegistrationViewModel(\'");

            
            #line 15 "..\..\Views\PartnerRegistration\PendingPartnerRegistrations.cshtml"
                                                                  Write(userRole);

            
            #line default
            #line hidden
WriteLiteral("\');\r\nko.applyBindingsWithValidation(viewModel, $(\"#PendingRegistration\")[0], { in" +
"sertMessages: false, messagesOnModified: false, grouping: { deep: true }});\r\n");

});

WriteLiteral(@"<style>
    .k-grid-header .k-header {
        white-space: nowrap;
        line-height: 15px;
    }

    .k-upload-status .k-upload-status-total {
        visibility: hidden;
        display: none;
    }

    .k-icon .k-i-tick {
        visibility: hidden;
        display: none;
    }

    .k-dropzone strong {
        display: none;
    }
     
    .modal-dialog1 {        
        width: 500px !important;
    }
</style>

<!-- BEGIN CONTENT -->
<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n\r\n\r\n<div");

WriteLiteral(" class=\"portlet-body\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"table-toolbar\"");

WriteLiteral(" id=\"PendingRegistration\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"portlet box advbg\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"portlet-title\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"caption\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i>Advance Search\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"tools\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"expand\"");

WriteLiteral("></a>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"portlet-body\"");

WriteLiteral(" data-bind=\"with: $root.AdvanceSearch\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-wizard form-horizontal\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Partner Name:</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-bind=\"value: PartnerName, event: { keypress: $root.validationHelper.Validat" +
"eAlphabetsWithSpaces }\"");

WriteLiteral(" id=\"PartnerName\"");

WriteLiteral(" maxlength=\"50\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                                    </div>\r\n                                </" +
"div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">PartnerType:</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"PartnerType\"");

WriteLiteral(" data-bind=\"options: $root.PartnerTypeVals, optionsText: \'name\', optionsValue: \'v" +
"al\', value: PartnerType\"");

WriteLiteral("></select>\r\n                                    </div>\r\n                         " +
"       </div>\r\n                            </div>\r\n                            <" +
"div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral(">Status:</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"\"");

WriteLiteral(" data-bind=\"options: [\'All\',\'New\', \'Verified\', \'Rejected At Verification\', \'Appro" +
"ved\', \'Rejected\'], value: WFStatus\"");

WriteLiteral("></select>\r\n                                    </div>\r\n                         " +
"       </div>\r\n                            </div>\r\n                        </div" +
">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral("></label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                                        <button");

WriteLiteral(" class=\"btn btn-xs green\"");

WriteLiteral(" data-bind=\"click: $root.FilterPartnerRegistrations\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">Search</button>\r\n                                        <button");

WriteLiteral(" class=\"btn btn-xs blue\"");

WriteLiteral(" id=\"btnReset\"");

WriteLiteral(" data-bind=\"click: $root.ResetAdvanceSearchFilters\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(@">Reset</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-body form-horizontal \"");

WriteLiteral(" data-bind=\'with: PendingPartnerRegistrationModel\'");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"tableheader\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" data-bind=\"loadingWhen: $root.viewModelHelper.isLoading\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"Grid\"");

WriteLiteral(@" data-bind=""kendoGrid: {
	data: $root.PendingRegistrationList,
	groupable: false,
	sortable: true,
	scrollable: true,
	filterable: {
		extra: false, operators: {
			string: {
				startswith: 'Starts with',
				eq: 'Is equal to',
				neq: 'Is not equal to', contains: 'Contains', doesnotcontain: 'Does not Contain'
			},
			number: { eq: 'Is equal to' }
		}
	},
	rowTemplate: 'rowTmpl',
	useKOTemplates: true,
	columns: [{ title: 'Actions', filterable: false, width: 90 },
        { field: 'RequisitionNoSort', width: 150, title: 'Request No.', filterable: true },
        { field: 'PartnerTypeSort', width: 150, title: 'Partner Type', filterable: true },
        { field: 'PartnerNameSort', width: 150, title: 'Establishment Name', filterable: true, sortable: true },
         { field: 'RequestedDateSort', width: 150, title: 'Requested Date', filterable: false, sortable: true },
                         { field: 'StatusDisplaySort', width: 150, title: 'Status', filterable: true, sortable: true }
	]
}""");

WriteLiteral(">\r\n\t    </div>\r\n\t    <script");

WriteLiteral(" id=\"rowTmpl\"");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(@">
	    <tr>
	        <td align=""center"">
	            <a href=""#"" id=""btnView"" data-bind=""click: $root.ViewForm"" title=""View Pending Partner Registration"" class=""afterapproval""><i class=""fa fa-eye""></i></a>&nbsp;&nbsp;
	            <span data-bind=""visible: ((WFStatus() == 'New' && '");

            
            #line 142 "..\..\Views\PartnerRegistration\PendingPartnerRegistrations.cshtml"
                                                               Write(userRole);

            
            #line default
            #line hidden
WriteLiteral("\' == \'ACC\') || (\'");

            
            #line 142 "..\..\Views\PartnerRegistration\PendingPartnerRegistrations.cshtml"
                                                                                         Write(userRole);

            
            #line default
            #line hidden
WriteLiteral(@"' == 'TerminalOperator'))"" >          
                                        <a href=""#"" title=""Edit Pending Partner Registration"" data-bind=""click: $root.EditForm""><i class=""fa fa-edit""></i></a>
                                </span> 
	            <span data-bind=""visible: ((WFStatus() != 'New' && '");

            
            #line 145 "..\..\Views\PartnerRegistration\PendingPartnerRegistrations.cshtml"
                                                               Write(userRole);

            
            #line default
            #line hidden
WriteLiteral(@"' == 'ACC'))"" >          
                                        <a title=""Edit Pending Partner Registration""><i class=""fa fa-edit"" style=""color: #f3c398;""></i></a>

                                </span>
                                <span data-bind=""visible: ('");

            
            #line 149 "..\..\Views\PartnerRegistration\PendingPartnerRegistrations.cshtml"
                                                       Write(userRole);

            
            #line default
            #line hidden
WriteLiteral(@"' == 'TerminalOperator' && WFStatus()=='Verified')"">
                                    <a href=""#"" id=""btnApprove"" data-target=""#rejectBulk"" data-toggle=""modal"" data-bind=""click: $root.ShowContainersPopup"" title=""Approve Pending Partner Registration""><i class=""fa fa-thumbs-up"" aria-hidden=""true"" style=""color: green;""></i></a>&nbsp;&nbsp;
                                        <a href=""#"" id=""btnReject"" data-target=""#rejectBulk"" data-toggle=""modal"" data-bind=""click: $root.ShowContainersPopup"" title=""Reject Pending Partner Registration""><i class=""fa fa-times red"" style=""color: red;""></i></a>
                                </span>
                                <span data-bind=""visible: ('");

            
            #line 153 "..\..\Views\PartnerRegistration\PendingPartnerRegistrations.cshtml"
                                                       Write(userRole);

            
            #line default
            #line hidden
WriteLiteral(@"' == 'TerminalOperator' && WFStatus()!='Verified')"">
                                    <a title=""Approve Pending Partner Registration""><i class=""fa fa-thumbs-up"" aria-hidden=""true""  style=""color: #a8fca8;""></i></a>&nbsp;&nbsp;
                                        <a title=""Reject Pending Partner Registration""><i class=""fa fa-times red"" style=""color: #f8aeae;""></i></a>
                                </span>
                                <span data-bind=""visible: ('");

            
            #line 157 "..\..\Views\PartnerRegistration\PendingPartnerRegistrations.cshtml"
                                                       Write(userRole);

            
            #line default
            #line hidden
WriteLiteral(@"' == 'ACC' && WFStatus()=='New')"">
                                    <a href=""#"" id=""btnVerify"" data-target=""#rejectBulk"" data-toggle=""modal"" data-bind=""click: $root.ShowContainersPopup"" title=""Verify Pending Partner Registration""><i class=""fa fa-check green"" style=""color: green;""></i></a>&nbsp;&nbsp;
                                        <a href=""#"" id=""btnRejectVerification"" data-target=""#rejectBulk"" data-toggle=""modal"" data-bind=""click: $root.ShowContainersPopup"" title=""Reject Pending Partner Registration""><i class=""fa fa-times red"" style=""color: red;""></i></a>
                                </span>
                                <span data-bind=""visible: ('");

            
            #line 161 "..\..\Views\PartnerRegistration\PendingPartnerRegistrations.cshtml"
                                                       Write(userRole);

            
            #line default
            #line hidden
WriteLiteral(@"' == 'ACC' && WFStatus()!='New')"">
                                    <a title=""Verify Pending Partner Registration""><i class=""fa fa-check green"" style=""color: #a8fca8;""></i></a>&nbsp;&nbsp;
                                        <a title=""Reject Pending Partner Registration""><i class=""fa fa-times red"" style=""color: #f8aeae;""></i></a>
                                </span>
                            </td>
                            <td align=""center"">
                                <span data-bind=""text: RequisitionNo, attr: { title: RequisitionNo }""></span>
                            </td>
                            <td align=""center"">
                                <span data-bind=""text: PartnerTypeDisplay, attr: { title: PartnerType }""></span>
                            </td>
                            <td align=""center"">
                                <span data-bind=""text: PartnerName, attr: { title: PartnerName }""></span>
                            </td>
                            <td align=""center"">
                                <span data-bind=""text: RequestedDate, attr: { title: RequestedDate }""></span>
                            </td>
                            <td align=""center"">
                                <span data-bind=""text: StatusDisplay, attr: { title: StatusDisplay }""></span>
                            </td>
                        </tr>
                    </script>

                    <div");

WriteLiteral(" id=\"rejectBulk\"");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"modal-dialog1\"");

WriteLiteral(" id=\"stk\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" id=\"rejectBulkClose\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" data-bind=\"visible: false\"");

WriteLiteral("></button>\r\n                                    <div");

WriteLiteral(" class=\"form-wizard\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"col-md-12 form-group\"");

WriteLiteral(">\r\n                                            <h3");

WriteLiteral(" id=\"lblMainHeading\"");

WriteLiteral(" style=\"border-bottom: 2px solid #ccc; margin-top: 1px; padding-bottom: 5px;\"");

WriteLiteral("></h3>\r\n                                        </div>\r\n                         " +
"               <div");

WriteLiteral(" data-always-visible=\"1\"");

WriteLiteral(" data-rail-visible1=\"1\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                                <label");

WriteLiteral(" id=\"lblRejectsContainer\"");

WriteLiteral("></label>\r\n                                            </div>\r\n                  " +
"                          <div");

WriteLiteral(" data-bind=\"visible: $root.IsRemarksVisible\"");

WriteLiteral(">\r\n                                                <fieldset>\r\n                  " +
"                                  <form");

WriteLiteral(" action=\"#\"");

WriteLiteral(" id=\"form_sample_2\"");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n\r\n                                                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" data-bind=\"if: $root.IsReject\"");

WriteLiteral(">\r\n                                                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                                                <label");

WriteLiteral(" id=\"lblheadingReject\"");

WriteLiteral(" class=\"col-md-4 control-label\"");

WriteLiteral(">Reason For Reject:<span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" style=\"color: red\"");

WriteLiteral(">*</span></label>\r\n                                                              " +
"  <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n                                                                    <textarea");

WriteLiteral(" rows=\"4\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" onchange=\" HandleValidateRejectRemarks(this); \"");

WriteLiteral(" id=\"txtAreaRejectsRemarks\"");

WriteLiteral(" style=\"resize: none; width: 100%; border: 1px solid #ccc;\"");

WriteLiteral(" data-bind=\"value: $root.Remarks, visible: $root.IsReject\"");

WriteLiteral(" maxlength=\"500\"");

WriteLiteral("></textarea>\r\n                                                                   " +
" <span");

WriteLiteral(" id=\"spanReject\"");

WriteLiteral(" class=\"validationError\"");

WriteLiteral(@"></span>
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" data-bind=\"if: $root.IsApprove\"");

WriteLiteral(">\r\n                                                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                                                <label");

WriteLiteral(" id=\"lblheadingApprove\"");

WriteLiteral(" class=\"col-md-6 control-label\"");

WriteLiteral(">Partner Code:<span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" style=\"color: red\"");

WriteLiteral(">*</span></label>\r\n                                                              " +
"  <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                                                                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" onchange=\" HandleValidateRejectRemarks(this); \"");

WriteLiteral(" id=\"txtAreaPartnerCode\"");

WriteLiteral(" style=\"resize: none; width: 100%; border: 1px solid #ccc;\"");

WriteLiteral(" data-bind=\"value: $root.PartnerCode, visible: $root.IsApprove, event: { keypress" +
": $root.validationHelper.ValidateAlphaNumeric, change: $root.DupliacteValidation" +
" }\"");

WriteLiteral(" maxlength=\"25\"");

WriteLiteral(" />\r\n                                                                    <span");

WriteLiteral(" id=\"spanApprove\"");

WriteLiteral(" class=\"validationError\"");

WriteLiteral(@"></span>
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" data-bind=\"if: $root.IsApprove\"");

WriteLiteral(">\r\n                                                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                                                <label");

WriteLiteral(" id=\"lblheading1\"");

WriteLiteral(" class=\"col-md-6 control-label\"");

WriteLiteral(">User Name:<span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" style=\"color: red\"");

WriteLiteral(">*</span></label>\r\n                                                              " +
"  <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                                                                    <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onchange=\" HandleValidateRejectRemarks(this); \"");

WriteLiteral(" id=\"txtAreaUserName\"");

WriteLiteral(" style=\"resize: none;\"");

WriteLiteral(" data-bind=\"value: $root.UserName, visible: $root.IsApprove, event: { keypress: $" +
"root.validationHelper.ValidateAlphaNumeric, change: $root.validateUserName }\"");

WriteLiteral(" maxlength=\"30\"");

WriteLiteral(" />\r\n                                                                    <span");

WriteLiteral(" id=\"spanUserName\"");

WriteLiteral(" class=\"validationError\"");

WriteLiteral(@"></span>
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" data-bind=\"if: $root.IsApprove\"");

WriteLiteral(">\r\n                                                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                                                <label");

WriteLiteral(" id=\"lblheading2\"");

WriteLiteral(" class=\"col-md-6 control-label\"");

WriteLiteral(">First Name:<span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" style=\"color: red\"");

WriteLiteral(">*</span></label>\r\n                                                              " +
"  <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                                                                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" onchange=\"changeFirstname(this);\"");

WriteLiteral(" id=\"txtAreaFirstName\"");

WriteLiteral(" style=\"resize: none; width: 100%; border: 1px solid #ccc;\"");

WriteLiteral(" data-bind=\"value: $root.FirstName, visible: $root.IsApprove, event: { keypress: " +
"$root.validationHelper.ValidateAlphabetsWithSpaces_keypressEvent }\"");

WriteLiteral(" maxlength=\"50\"");

WriteLiteral(" />\r\n                                                                    <span");

WriteLiteral(" id=\"spanFirstName\"");

WriteLiteral(" class=\"validationError\"");

WriteLiteral(@"></span>
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" data-bind=\"if: $root.IsApprove\"");

WriteLiteral(">\r\n                                                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                                                <label");

WriteLiteral(" id=\"lblheading3\"");

WriteLiteral(" class=\"col-md-6 control-label\"");

WriteLiteral(">Last Name:<span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" style=\"color: red\"");

WriteLiteral(">*</span></label>\r\n                                                              " +
"  <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                                                                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" onchange=\" changeLastname(this);\"");

WriteLiteral(" id=\"txtAreaLastName\"");

WriteLiteral(" style=\"resize: none; width: 100%; border: 1px solid #ccc;\"");

WriteLiteral(" data-bind=\"value: $root.LastName, visible: $root.IsApprove, event: { keypress: $" +
"root.validationHelper.ValidateAlphabetsWithSpaces_keypressEvent }\"");

WriteLiteral(" maxlength=\"50\"");

WriteLiteral(" />\r\n                                                                    <span");

WriteLiteral(" id=\"spanLastName\"");

WriteLiteral(" class=\"validationError\"");

WriteLiteral(@"></span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" data-bind=\"if: $root.IsApprove\"");

WriteLiteral(">\r\n                                                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                                                <label");

WriteLiteral(" id=\"lblheading4\"");

WriteLiteral(" class=\"col-md-6 control-label\"");

WriteLiteral(">Roles:<span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" style=\"color: red\"");

WriteLiteral(">*</span></label>\r\n                                                              " +
"  <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n\r\n                                                                    <input");

WriteLiteral(" class=\"displaytxt col-md-12\"");

WriteLiteral(" id=\"userPort\"");

WriteLiteral(" onchange=\"validateRole(this);\"");

WriteLiteral(" data-bind=\"kendoMultiSelect: { dataTextField: \'RoleName\', dataValueField: \'RoleI" +
"d\', data: $parent.Roles, value: UserRoleArray }\"");

WriteLiteral(" />\r\n\r\n                                                                    <span");

WriteLiteral(" id=\"spnrole\"");

WriteLiteral(" style=\"margin: 15px -0px 0px 0px\"");

WriteLiteral(" class=\"validationError\"");

WriteLiteral(@"></span>

                                                                </div>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </fieldset>
                                            </div>



                                        </div>
                                        <div");

WriteLiteral(" class=\"btns-group fluid \"");

WriteLiteral(" data-bind=\"loadingWhen: $root.viewModelHelper.isLoading\"");

WriteLiteral(">\r\n                                            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn green\"");

WriteLiteral(" data-bind=\"click: $parent.RejectsForm, visible: $root.IsReject\"");

WriteLiteral(" value=\"POST VAL\"");

WriteLiteral(">Yes</button>\r\n                                            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn green\"");

WriteLiteral(" data-bind=\"click: $parent.ApproveForm, visible: $root.IsApprove\"");

WriteLiteral(" value=\"POST VAL\"");

WriteLiteral(">Save</button>\r\n                                            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn green\"");

WriteLiteral(" data-bind=\"click: $parent.VerifyForm, visible: $root.IsVerify\"");

WriteLiteral(" value=\"POST VAL\"");

WriteLiteral(">Yes</button>\r\n                                            <button");

WriteLiteral(" id=\"btnPopUpNo\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn red\"");

WriteLiteral(" data-bind=\"click: $parent.closeRejectBulkPopup,text:($root.IsVerify()?\'No\':\'No\')" +
"\"");

WriteLiteral(@"></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">&nbsp;</div>\r\n\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
