#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ForgotPassword.cshtml")]
    public partial class _Views_Account_ForgotPassword_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Account_ForgotPassword_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Account\ForgotPassword.cshtml"
  

 Layout = "~/Views/Shared/_eGateLayoutForPassword.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Account\ForgotPassword.cshtml"
  
    ViewBag.Title = "ChangePassword";

    var IsFirstTimeLogin = "N";
    var PassWord="";
    var UserName="";
    var LogTransId="";

    if (!string.IsNullOrEmpty(ViewBag.PassWord))
    {
        PassWord = ViewBag.PassWord;

    }
if (!string.IsNullOrEmpty(ViewBag.UserName))
    {
        UserName = ViewBag.UserName;

    }
if (!string.IsNullOrEmpty(ViewBag.LogTransId))
    {
        LogTransId = ViewBag.LogTransId;

    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 558), Tuple.Create("\"", 592)
, Tuple.Create(Tuple.Create("", 564), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/angular.min.js")
, 564), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 612), Tuple.Create("\"", 668)
, Tuple.Create(Tuple.Create("", 618), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/Model/ChangePasswordModel.js")
, 618), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 688), Tuple.Create("\"", 752)
, Tuple.Create(Tuple.Create("", 694), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/ViewModel/ChangePasswordViewModel.js")
, 694), false)
);

WriteLiteral("></script>\r\n");

});

DefineSection("ko_apply", () => {

WriteLiteral("\r\n    var viewModel = new eGateRoot.ChangePasswordViewModel(\"");

            
            #line 37 "..\..\Views\Account\ForgotPassword.cshtml"
                                                      Write(IsFirstTimeLogin);

            
            #line default
            #line hidden
WriteLiteral("\");\t \r\n    ko.applyBindingsWithValidation(viewModel, $(\"#ChangePassword\")[0], { i" +
"nsertMessages: false, messagesOnModified: false, grouping: { deep: true }});\r\n");

});

WriteLiteral("\r\n<style>\r\n    .input-help {\r\n        display: none;\r\n        /*position:absolute" +
";*/\r\n        z-index: 100;\r\n        top: -27px;\r\n        left: -200px;\r\n        " +
"width: 300px;\r\n        padding: 10px;\r\n        background: #fefefe;\r\n        fon" +
"t-size: .875em;\r\n        border-radius: 5px;\r\n        box-shadow: 0 1px 3px #aaa" +
";\r\n        border: 1px solid #ddd;\r\n        opacity: 0.9;\r\n    }\r\n\r\n        .inp" +
"ut-help::before {\r\n            content: \"\\25C0\";\r\n            position: absolute" +
";\r\n            top: 10px;\r\n            left: -12px;\r\n            font-size: 16px" +
";\r\n            line-height: 16px;\r\n            color: #ddd;\r\n            text-sh" +
"adow: none;\r\n        }\r\n\r\n        .input-help h4 {\r\n            margin: 0;\r\n    " +
"        padding: 0;\r\n            font-weight: normal;\r\n            font-size: 1." +
"1em;\r\n        }\r\n\r\n    /* Always hide the input help when it\'s pristine */\r\n    " +
"input.ng-pristine + .input-help {\r\n        display: none;\r\n    }\r\n\r\n    /* Hide " +
"the invalid box while the input has focus */\r\n    .ng-invalid:focus + .input-hel" +
"p {\r\n        display: none;\r\n    }\r\n\r\n    /* Show a blue border while an input h" +
"as focus, make sure it overrides everything else */\r\n    /* Overriding Twitter B" +
"ootstrap cuz I don\'t agree we need to alarm the user while they\'re typing */\r\n  " +
"  input:focus {\r\n        color: black !important;\r\n        border-color: rgba(82" +
", 168, 236, 0.8) !important;\r\n        -webkit-box-shadow: inset 0 1px 1px rgba(0" +
", 0, 0, 0.075), 0 0 8px rgba(82, 168, 236, 0.6) !important;\r\n        -moz-box-sh" +
"adow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(82, 168, 236, 0.6) !imp" +
"ortant;\r\n        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(" +
"82, 168, 236, 0.6) !important;\r\n    }\r\n\r\n\r\n    /* Show green border when stuff h" +
"as been typed in, and its valid */\r\n    .ng-dirty.ng-valid {\r\n        border-col" +
"or: #ccc;\r\n    }\r\n\r\n    /* Show red border when stuff has been typed in, but its" +
" invalid */\r\n    .ng-dirty.ng-invalid {\r\n        border-color: #ec3f41;\r\n    }\r\n" +
"\r\n    .immediate-help {\r\n        display: block;\r\n        width: 20%;\r\n        f" +
"ont-size: 13px;\r\n        color: #555;\r\n        vertical-align: middle;\r\n        " +
"background-color: white;\r\n        background-image: none;\r\n        border-radius" +
": 4px;\r\n    }\r\n\r\n        /* Show the help box once it has focus */\r\n        .imm" +
"ediate-help:focus + .input-help {\r\n            position: relative;\r\n            " +
"margin-left: 450px;\r\n            display: block;\r\n        }\r\n\r\n        /* Immedi" +
"ate help should be red when pristine */\r\n        .immediate-help.ng-pristine:foc" +
"us + .input-help {\r\n            border-color: #ec3f41;\r\n        }\r\n\r\n           " +
" .immediate-help.ng-pristine:focus + .input-help::before {\r\n                colo" +
"r: #ec3f41;\r\n            }\r\n\r\n    .input-help::before {\r\n        display: none;\r" +
"\n    }\r\n\r\n    /* Help hould be green when input is valid */\r\n    .ng-valid + .in" +
"put-help {\r\n        border-color: #3a7d34;\r\n    }\r\n\r\n        .ng-valid + .input-" +
"help::before {\r\n            color: #3a7d34;\r\n        }\r\n\r\n    /* Help should sho" +
"w and be red when invalid */\r\n    .ng-invalid + .input-help {\r\n        display: " +
"block;\r\n        /*position:relative;*/\r\n        /*margin-left: 450px;*/\r\n       " +
" border-color: #ec3f41;\r\n    }\r\n\r\n        .ng-invalid + .input-help::before {\r\n " +
"           color: #ec3f41;\r\n        }\r\n\r\n    /* Style input help requirement bul" +
"lets */\r\n    .input-help ul {\r\n        list-style: none;\r\n        margin: 10px 0" +
" 0 0;\r\n    }\r\n\r\n    /* Default each bullet to be invalid with a red cross and te" +
"xt */\r\n    .input-help li {\r\n        padding-left: 22px;\r\n        line-height: 2" +
"4px;\r\n        color: #ec3f41;\r\n        background: url(data:image/png;base64,iVB" +
"ORw0KGgoAAAANSUhEUgAAABAAAAA1CAYAAABIkmvkAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAJwA" +
"AACcBKgmRTwAAABZ0RVh0Q3JlYXRpb24gVGltZQAxMC8wOS8xMlhq+BkAAAAcdEVYdFNvZnR3YXJlAEF" +
"kb2JlIEZpcmV3b3JrcyBDUzVxteM2AAAEA0lEQVRIie2WW2jbVRzHv//zT5rkn0ub61zaNdEiPqTC9EF" +
"RhtgJk63qg3Wr0806pswNiYgDUXxwyryCEB8UBevtaSCCDHQoboKyoVvVzfRmL2napU0mrdbl8s//dy4" +
"+dM1M28n64FsPnIdz+XzO75zfOXA0pRRWU7o/uS9FxOc+3/vlIQBgq4F3fHxvKuIPJ9cFwi9uTXU8BwD" +
"a1Uaw/aN7UusCkWRbPI5yxcTI2Bgy49kXrkrwwIedqYg/nGyLXwsJiYHBYWTGs7Cq5Kpt4cA3PXft+2r" +
"X40vhrt7OVLgplIzHYuBKoH9gCKMjGVE1LdfJl86YDAAOfN2ziZP4NODyv9/z2fanFuH7P9iWCjcFk/F" +
"YK4QSGLgEk0WeUy/3mQCgPXFs9xbBRW883NrssDvQN3hWcOLPEPGWiD94MBaPQymBoaERjI9mBSfu+fH" +
"wL+biItpjR3e6JFfloDeAaGQ9SpUycvlp6ExHJBKGYsDvgyMYH81KTsL90yuX4VoWdh3pMqSQpWBjAC3" +
"RZkgpYEkCFDA8NIqJ0UlFxI3Tr/5aB9elsau305BcloKBAFpjLeBSYGRwDBNjk4oTN06/dnYZXCcAgK1" +
"vbzYkl6VwOATihOzYlOLEjTOvn1sRXiYAgDsP32YIKUuWaXFOwtP3xrnqleAVBQBwy/M3GZy4+PnN3/4" +
"TvqJgNWVVj2lNsCZYE6wJ1gRrgv9dYAMAHHw2Bl2fUEpBVavtLPVW/78nVR/Zk4CupzVHA6zChSOK0yH" +
"v0S8GFyK4BMPhAJxOgLE03/9kYhE2dz+agKaldY8bDaEQ7D5ft7Roy+UIlCooy5LQdaZ5vVBEgGmmrT1" +
"72yVxaIylmdcDm9cHc2oK1Zm8kETvLAo0pRRk8mmnEqKouVw68zVCzP8F/uccFHHoXi/sjT6Y53Mw83m" +
"hOHn8J7416wQAwPftd0ouiswwdJu/CRASkBKQAmYuBzNfWIC/O173W6llwfbeu6Yi8tDsrAQJYGICyGQ" +
"AIWDO5KUkaxlcJwAASdSmaWAQHCACOAc4h6YzJi1qWymNNUHlwYcT0JDWXQbACYhGgeh6gHM4Ghuh2/R" +
"0YePNiaUCTSmFcvdDCY1paZvhht3nQ2VmGmahICSR5vQHmDt6DcozeZSnp2FdLLZHhwdq94SVd+xMaJq" +
"WtrkM2L1uVHILpy0t8igidymXExfHMzBCQbhCIdga7Onz8etqkdgkUYTZbYCSqORmULlQEIq4J3jyexM" +
"A8jdu9BRzuaKyLN3udkNjDEqICID+2hbm797Wwez24/T3vJTE3aFTP9Sd9vT1NziVEMUGr1c35+Y2b5j" +
"KnqgNKqWglMLspjs6/rj1dudie2mdao07J5s3dCzt/werJTyI1yYqpQAAAABJRU5ErkJggg==) no-re" +
"peat 2px -34px;\r\n    }\r\n\r\n        /* Set to green check and text when valid */\r\n" +
"        .input-help li.valid {\r\n            color: #3a7d34;\r\n            backgro" +
"und-position: 2px 6px;\r\n        }\r\n\r\n    /* Set submit button */\r\n    form .disn" +
", form.ng-valid .btn[disabled] {\r\n        display: none;\r\n    }\r\n\r\n    form.ng-i" +
"nvalid .btn[disabled], form.ng-valid .btn {\r\n        /*margin-left: 400px;*/\r\n  " +
"      display: inline-block;\r\n    }\r\n\r\n    /*body {\r\n padding: 20px 0;   \r\n}*/\r\n" +
"    input {\r\n        width: 166px;\r\n    }\r\n    /*.form-horizontal .control-label" +
" {\r\n    width: 180px;\r\n}*/\r\n    /*.form-horizontal .controls {\r\n  position: rela" +
"tive;\r\n  margin-left: 200px;\r\n}*/\r\n</style>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"page-title\"");

WriteLiteral(">Change Password</h3>\r\n        <ul");

WriteLiteral(" class=\"page-breadcrumb breadcrumb\"");

WriteLiteral("></ul>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n<script");

WriteLiteral(" id=\"customMessageTemplate\"");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(">\r\n    <span class=\"validationError\" data-bind=\'validationMessage: field\'></span>" +
"\r\n</script>\r\n<div");

WriteLiteral(" class=\"portlet-body\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"table-toolbar\"");

WriteLiteral(">\r\n        <fieldset>\r\n\r\n            <form");

WriteLiteral(" ng-app=\"form-example\"");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(" novalidate>\r\n                <div");

WriteLiteral(" id=\"ChangePassword\"");

WriteLiteral(" data-bind=\"with: changepasswordModel\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-wizard\"");

WriteLiteral(" data-bind=\'validationOptions: { messageTemplate: \"customMessageTemplate\" }\'");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"control-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"controls\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"control-label col-md-5\"");

WriteLiteral(" for=\"inputPassword\"");

WriteLiteral(">User Name :</label>\r\n                                <label");

WriteLiteral(" class=\"control-label displaytxt\"");

WriteLiteral(" id=\"loginusername\"");

WriteLiteral(">");

            
            #line 223 "..\..\Views\Account\ForgotPassword.cshtml"
                                                                                      Write(ViewBag.UserName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"Username\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral("></input>\r\n                                ");

WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"control-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"controls form-group\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"control-label col-md-5\"");

WriteLiteral(" for=\"inputPassword\"");

WriteLiteral(">Current Password:</label>\r\n                                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" class=\"immediate-help form-control\"");

WriteLiteral(" style=\"width: 100%; background: none;border: 0px;\"");

WriteLiteral(" id=\"loginpassword\"");

WriteLiteral(" disabled");

WriteLiteral(" type=\"password\"");

WriteLiteral(" placeholder=\"Current Password\"");

WriteLiteral(" autocomplete=\"off\"");

WriteAttribute("value", Tuple.Create(" value=", 8843), Tuple.Create("", 8867)
            
            #line 232 "..\..\Views\Account\ForgotPassword.cshtml"
                                                                                                                                                      , Tuple.Create(Tuple.Create("", 8850), Tuple.Create<System.Object, System.Int32>(ViewBag.PassWord
            
            #line default
            #line hidden
, 8850), false)
);

WriteLiteral("\">\r\n                                    ");

WriteLiteral("\r\n                                    <label class=\"control-label displaytxt\" id=" +
"\"logTransId\" style=\"display:none;\">");

            
            #line 235 "..\..\Views\Account\ForgotPassword.cshtml"
                                                                                                             Write(ViewBag.LogTransId);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\r\n                                    ");

WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n\r\n                        <div class=\"control-group" +
"\">\r\n\r\n                            <div class=\"controls form-group\">\r\n           " +
"                     <label class=\"control-label col-md-5\" for=\"inputPassword\">N" +
"ew Password:</label>\r\n                                <div class=\"col-md-3\">\r\n  " +
"                                  <input ng-model=\"password\" style=\"width: 100%\"" +
" class=\"immediate-help form-control\" password-validate required type=\"password\" " +
"id=\"inputPassword\" placeholder=\"New Password\" data-bind=\"value: NewPassword\" onc" +
"opy=\"return false\" onpaste=\"return false\" oncut=\"return false\">\r\n               " +
"                     <div class=\"input-help\">\r\n                                 " +
"       <h4>New Password must meet the following requirements:</h4>\r\n            " +
"                            <ul>\r\n                                            <l" +
"i ng-class=\"pwdUpperLetter\">At least <strong>one upper letter</strong></li>\r\n   " +
"                                         <li ng-class=\"pwdLowerLetter\">At least " +
"<strong>one lower letter</strong></li>\r\n                                        " +
"    <li ng-class=\"pwdHasNumber\">At least <strong>one number</strong></li>\r\n     " +
"                                       <li ng-class=\"pwdSpecialChar\">At least <s" +
"trong>one special character</strong></li>\r\n                                     " +
"       <li ng-class=\"pwdValidLength\">At least <strong>8 characters long</strong>" +
"</li>\r\n\r\n                                        </ul>\r\n                        " +
"            </div>\r\n                                </div>\r\n                    " +
"        </div>\r\n                        </div>\r\n                        <div cla" +
"ss=\"control-group\">\r\n                            <div class=\"controls form-group" +
"\">\r\n                                <label class=\"control-label col-md-5\" for=\"i" +
"nputPassword\">Confirm Password:</label>\r\n                                <div cl" +
"ass=\"col-md-3\">\r\n                                    <input class=\"immediate-hel" +
"p form-control\" style=\"width: 100%\" type=\"password\" placeholder=\"Confirm Passwor" +
"d\" data-bind=\"value: ConfirmPassword\" oncopy=\"return false\" onpaste=\"return fals" +
"e\" oncut=\"return false\">\r\n                                </div>\r\n              " +
"              </div>\r\n                        </div>\r\n                        <d" +
"iv class=\"fluid\">\r\n                            <div class=\"row control-group \">\r" +
"\n                                <div class=\"col-md-5\">&nbsp;</div>\r\n           " +
"                     <div class=\"controls\" style=\"padding: 10px\">\r\n             " +
"                       <a href=\"#\" type=\"submit\" class=\"disn btn btn-xs green\" d" +
"ata-bind=\"click: $root.SubmitForgotPassword\">Submit</a>\r\n                       " +
"             <a href=\"#\" class=\"disn btn btn-xs green\" disabled data-bind=\"click" +
": $root.SubmitForgotPassword\">Submit</a>\r\n\r\n                                </di" +
"v>\r\n                            </div>\r\n                        </div>\r\n\r\n\r\n\r\n  " +
"                  </div>\r\n                </div>\r\n\r\n            </form>\r\n\r\n     " +
"   </fieldset>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
