#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Account\SessionExpired.cshtml"
    using PortKonnect.UserAccessManagement.UI;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/SessionExpired.cshtml")]
    public partial class _Views_Account_SessionExpired_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Account_SessionExpired_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Account\SessionExpired.cshtml"
  
    Layout = "~/Views/Shared/_LoginLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<body>\r\n    <div");

WriteLiteral(" style=\"background: #FFF; display: block\"");

WriteLiteral("></div>\r\n\r\n    <header");

WriteLiteral(" class=\"header navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"padding: 0px\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"header-inner\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"name\"");

WriteLiteral(" style=\"padding-left: 0px; margin-top: -5px;\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 400), Tuple.Create("\"", 443)
, Tuple.Create(Tuple.Create("", 406), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Images/eGate-HeaderLogo.png")
, 406), false)
);

WriteLiteral(" style=\"vertical-align: bottom;\"");

WriteLiteral("></span>\r\n                <ul");

WriteLiteral(" class=\"nav navbar-nav pull-right\"");

WriteLiteral(">\r\n\r\n                    ");

WriteLiteral("\r\n\r\n                    <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(" id=\"profileDropDown\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" data-hover=\"dropdown\"");

WriteLiteral(" data-close-others=\"true\"");

WriteLiteral(" onclick=\"onclickDropDown()\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-phone\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i>Contact Us &nbsp; &nbsp;</a>\r\n                        <ul");

WriteLiteral(" class=\"dropdown-menu extended inbox\"");

WriteLiteral(" style=\"width:300px !important;\"");

WriteLiteral(">\r\n                            <li>\r\n                                <p");

WriteLiteral(" style=\"background-color:#032f52;\"");

WriteLiteral("><b>KPCT Customer Service</b></p>\r\n                            </li>\r\n           " +
"                 <li>\r\n                                <ul");

WriteLiteral(" class=\"dropdown-menu-list scroller\"");

WriteLiteral(" style=\"height: 160px; padding: 10px; \"");

WriteLiteral(">\r\n                                    <li");

WriteLiteral(" style=\"color:#2FA1DB;\"");

WriteLiteral("><b>Krishnapatnam Port Container Terminal</b></li>\r\n                             " +
"       <li></li>\r\n                                    <span");

WriteLiteral(" style=\"font-size:11px;\"");

WriteLiteral(@"><li>P.O Bag No.1, Muthukur Mandal,</li>
                                        <li>SPSR Nellore District,</li>
                                        <li>Andhra Pradesh – 524 344, INDIA</li></span>
                                    <li><b>Customer Service – 24 x 7:</b></li>
                                    <span");

WriteLiteral(" style=\"font-size:11px;\"");

WriteLiteral("><li>Tel: +91 80086 12345, Fax: +91-0861-237 7046</li>\r\n                         " +
"               <li>E Mail: <a");

WriteLiteral(" href=\"mailto:cs.kpct@krishnapatnam.com\"");

WriteLiteral(">cs.kpct@krishnapatnamport.com</a></li>\r\n\r\n\r\n                                    " +
"    <li>URL: <a");

WriteLiteral(" href=\"http://www.krishnapatnam.com\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(@">www.krishnapatnamport.com</a></li>
                                    </span>
                                </ul>
                            </li>

                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </header>
    <div");

WriteLiteral(" style=\"height:100px;\"");

WriteLiteral(">&nbsp;</div>\r\n    <div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"form-title\"");

WriteLiteral(" style=\"color:#fff;\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">Your Session Has Expired</h3>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <div hidden>\r\n                <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" onclick=\"closeWindow()\"");

WriteLiteral(">close</a>\r\n                <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" onclick=\"CloseWindow1()\"");

WriteLiteral(">close1</a>\r\n                <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" onclick=\"CloseOpenerWindow()\"");

WriteLiteral(">close2</a>\r\n                <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" onclick=\"CloseOpenerHikks()\"");

WriteLiteral(">close3</a>\r\n                <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" onclick=\"closeWindow()\"");

WriteLiteral(">close4</a>\r\n            </div>\r\n            <h5");

WriteLiteral(" align=\"center\"");

WriteLiteral(" style=\"color:#fff;\"");

WriteLiteral(">Please  <a");

WriteLiteral(" onclick=\"RedirectToLogin()\"");

WriteLiteral(" class=\"btn btn-sm green button-previous\"");

WriteLiteral(">Click here <i");

WriteLiteral(" class=\"fa fa-angle-double-right\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i></a>  to Login again</h5>\r\n        </div>\r\n\r\n\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
      function CloseWindow1() {
          window.close();
      }

      function CloseOpenerWindow() {
          window.opener = window
          window.close();
      }

      function CloseOpenerHikks() {
          window.opener = ""HikksNotAtHome"";
          window.close();
      }

      function CloseWithWindowOpenTrick() {
          var objWindow = window.open(location.href, ""_self"");
          objWindow.close();
      }

      function closeWindow(){
          alert(""This will close the window"");
          window.open('', '_self', '');
          window.close();
      }
      function RedirectToLogin() {
          window.location = window.location.origin;
      }
        </script>
        ");

WriteLiteral("\r\n    </div>\r\n\r\n\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
