#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Account\SiteMaintainance.cshtml"
    using PortKonnect.UserAccessManagement.UI;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/SiteMaintainance.cshtml")]
    public partial class _Views_Account_SiteMaintainance_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Account_SiteMaintainance_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Account\SiteMaintainance.cshtml"
  
    Layout = "~/Views/Shared/_LoginLayout.cshtml";    

            
            #line default
            #line hidden
WriteLiteral("\r\n \r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n\r\n   <script");

WriteAttribute("src", Tuple.Create(" src=\"", 144), Tuple.Create("\"", 194)
, Tuple.Create(Tuple.Create("", 150), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/Model/UserModel.js")
, 150), false)
);

WriteLiteral("></script>\r\n   <script");

WriteAttribute("src", Tuple.Create(" src=\"", 217), Tuple.Create("\"", 275)
, Tuple.Create(Tuple.Create("", 223), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/ViewModel/UserViewModel.js")
, 223), false)
);

WriteLiteral("></script> \r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 302), Tuple.Create("\"", 351)
, Tuple.Create(Tuple.Create("", 308), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/CustomisedControls.js")
, 308), false)
);

WriteLiteral("></script>      \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 381), Tuple.Create("\"", 429)
, Tuple.Create(Tuple.Create("", 387), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/Model/ModuleModel.js")
, 387), false)
);

WriteLiteral("></script>  \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 455), Tuple.Create("\"", 511)
, Tuple.Create(Tuple.Create("", 461), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/ViewModel/ModuleViewModel.js")
, 461), false)
);

WriteLiteral("></script>    \r\n      \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 547), Tuple.Create("\"", 602)
, Tuple.Create(Tuple.Create("", 553), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/Model/NotificationsModel.js")
, 553), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 626), Tuple.Create("\"", 689)
, Tuple.Create(Tuple.Create("", 632), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/ViewModel/NotificationsViewModel.js")
, 632), false)
);

WriteLiteral("></script>  \r\n\r\n\r\n\r\n");

});

WriteLiteral("\r\n");

DefineSection("ko_apply", () => {

WriteLiteral(" \r\n   var viewModel = new eGateRoot.UserViewModel(application);\r\n  ko.applyBindin" +
"gsWithValidation(viewModel, $(\"#accountlogin\")[0], { insertMessages: false, mess" +
"agesOnModified: false, grouping: { deep: true }});\r\n");

});

WriteLiteral("   \r\n<script> var ParentUrl = \'\' </script>\r\n<style>\r\n    #classadd .backstretch i" +
"mg {display:none !important;}\r\n</style>\r\n\r\n<body>\r\n    <div");

WriteLiteral(" style=\"background: #FFF; display: block\"");

WriteLiteral("></div>\r\n\r\n    <header");

WriteLiteral(" class=\"header navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"padding: 0px\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"header-inner\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"name\"");

WriteLiteral(" style=\"padding-left: 0px; margin-top: -5px;\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 1371), Tuple.Create("\"", 1414)
, Tuple.Create(Tuple.Create("", 1377), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Images/eGate-HeaderLogo.png")
, 1377), false)
);

WriteLiteral(" style=\"vertical-align: bottom;\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n    </header>\r\n    <script");

WriteLiteral(" id=\"customMessageTemplate\"");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(">\r\n        <span class=\"validationError\" data-bind=\'validationMessage: field\'></s" +
"pan>\r\n    </script>\r\n\r\n\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n           <div");

WriteLiteral(" class=\"down-alert\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t<i");

WriteLiteral(" class=\"fa fa-cog fa-spin fa-3x fa-fw \"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i>\r\n                            <h4>e-Xpressway application is</h4>\r\n         " +
"                   <h2>under maintanance till 4 pm</h2>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</di" +
"v>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n        </div>\r\n\r\n   \r\n    <script>\r\n        eGateRoo" +
"t.rootPath = \'");

            
            #line 65 "..\..\Views\Account\SiteMaintainance.cshtml"
                         Write(Url.Content("~"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var application = {viewbag : ");

            
            #line 66 "..\..\Views\Account\SiteMaintainance.cshtml"
                                Write(Helpers.ToJson(Html, ViewBag));

            
            #line default
            #line hidden
WriteLiteral(@"};

        $('.register-form input').keypress(function (e) {
            if (e.which == 13) {
                if ($('.register-form').validate().form()) {
                    $('.register-form').submit();
                }
                return false;
            }
        });

        $('.forget-form input').keypress(function (e) {
            if (e.which == 13) {
                if ($('.forget-form').validate().form()) {
                    $('.forget-form').submit();
                }
                return false;
            }
        });

        jQuery('#forget-password').click(function () {
            jQuery('.login-form').hide();
            jQuery('.forget-form').show();
        });

        jQuery('#back-btn').click(function () {
            jQuery('.login-form').show();
            jQuery('.forget-form').hide();
        });


        jQuery(document).ready(function () { 
            Login.init();
        });

    	
      


    </script>
    


</body>
</html>

");

        }
    }
}
#pragma warning restore 1591
