#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_LoginLayout.cshtml"
    using PortKonnect.UserAccessManagement.UI;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_LoginLayout.cshtml")]
    public partial class _Views_Shared__LoginLayout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__LoginLayout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n<head>\r\n     <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <title>e-Xpressway</title>\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" content=\"\"");

WriteLiteral(" name=\"description\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" content=\"\"");

WriteLiteral(" name=\"author\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"MobileOptimized\"");

WriteLiteral(" content=\"320\"");

WriteLiteral(">\r\n\r\n     <link");

WriteAttribute("href", Tuple.Create(" href=\"", 432), Tuple.Create("\"", 476)
, Tuple.Create(Tuple.Create("", 439), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/font-awesome.min.css")
, 439), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n     <link");

WriteAttribute("href", Tuple.Create(" href=\"", 509), Tuple.Create("\"", 550)
, Tuple.Create(Tuple.Create("", 516), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/bootstrap.min.css")
, 516), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n     <link");

WriteAttribute("href", Tuple.Create(" href=\"", 583), Tuple.Create("\"", 626)
, Tuple.Create(Tuple.Create("", 590), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/uniform.default.css")
, 590), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n     <link");

WriteAttribute("href", Tuple.Create(" href=\"", 659), Tuple.Create("\"", 697)
, Tuple.Create(Tuple.Create("", 666), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/datepicker.css")
, 666), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n     <link");

WriteAttribute("href", Tuple.Create(" href=\"", 730), Tuple.Create("\"", 772)
, Tuple.Create(Tuple.Create("", 737), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/style-metronic.css")
, 737), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 804), Tuple.Create("\"", 837)
, Tuple.Create(Tuple.Create("", 811), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/style.css")
, 811), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 869), Tuple.Create("\"", 913)
, Tuple.Create(Tuple.Create("", 876), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/style-responsive.css")
, 876), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 945), Tuple.Create("\"", 983)
, Tuple.Create(Tuple.Create("", 952), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/grid-style.css")
, 952), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1015), Tuple.Create("\"", 1050)
, Tuple.Create(Tuple.Create("", 1022), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/plugins.css")
, 1022), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1082), Tuple.Create("\"", 1116)
, Tuple.Create(Tuple.Create("", 1089), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/custom.css")
, 1089), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1148), Tuple.Create("\"", 1192)
, Tuple.Create(Tuple.Create("", 1155), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/kendo.common.min.css")
, 1155), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1224), Tuple.Create("\"", 1269)
, Tuple.Create(Tuple.Create("", 1231), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/kendo.default.min.css")
, 1231), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1301), Tuple.Create("\"", 1336)
, Tuple.Create(Tuple.Create("", 1308), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/default.css")
, 1308), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1368), Tuple.Create("\"", 1402)
, Tuple.Create(Tuple.Create("", 1375), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/toastr.css")
, 1375), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1434), Tuple.Create("\"", 1471)
, Tuple.Create(Tuple.Create("", 1441), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/jquery-ui.css")
, 1441), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1503), Tuple.Create("\"", 1548)
, Tuple.Create(Tuple.Create("", 1510), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/jquery.ui.chatbox.css")
, 1510), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1580), Tuple.Create("\"", 1622)
, Tuple.Create(Tuple.Create("", 1587), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/jquery.confirm.css")
, 1587), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1654), Tuple.Create("\"", 1702)
, Tuple.Create(Tuple.Create("", 1661), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/jquery.fileupload-ui.css")
, 1661), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1734), Tuple.Create("\"", 1772)
, Tuple.Create(Tuple.Create("", 1741), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/login-soft.css")
, 1741), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1804), Tuple.Create("\"", 1848)
, Tuple.Create(Tuple.Create("", 1811), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/byrei-dyndiv_0.5.css")
, 1811), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    ");

WriteLiteral("\r\n\r\n     <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1973), Tuple.Create("\"", 2012)
, Tuple.Create(Tuple.Create("", 1979), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery-2.0.3.min.js")
, 1979), false)
);

WriteLiteral("></script>  \r\n      <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2040), Tuple.Create("\"", 2072)
, Tuple.Create(Tuple.Create("", 2046), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery-ui.js")
, 2046), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2099), Tuple.Create("\"", 2146)
, Tuple.Create(Tuple.Create("", 2105), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery-migrate-1.2.1.min.js")
, 2105), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2173), Tuple.Create("\"", 2209)
, Tuple.Create(Tuple.Create("", 2179), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/bootstrap.min.js")
, 2179), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2236), Tuple.Create("\"", 2280)
, Tuple.Create(Tuple.Create("", 2242), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery.slimscroll.min.js")
, 2242), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2307), Tuple.Create("\"", 2346)
, Tuple.Create(Tuple.Create("", 2313), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery.cokie.min.js")
, 2313), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2373), Tuple.Create("\"", 2415)
, Tuple.Create(Tuple.Create("", 2379), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery.validate.min.js")
, 2379), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2442), Tuple.Create("\"", 2492)
, Tuple.Create(Tuple.Create("", 2448), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery.bootstrap.wizard.min.js")
, 2448), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2519), Tuple.Create("\"", 2553)
, Tuple.Create(Tuple.Create("", 2525), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/spinner.min.js")
, 2525), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2580), Tuple.Create("\"", 2623)
, Tuple.Create(Tuple.Create("", 2586), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/bootstrap-datepicker.js")
, 2586), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2650), Tuple.Create("\"", 2690)
, Tuple.Create(Tuple.Create("", 2656), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery.dataTables.js")
, 2656), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2717), Tuple.Create("\"", 2752)
, Tuple.Create(Tuple.Create("", 2723), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/DT_bootstrap.js")
, 2723), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2779), Tuple.Create("\"", 2825)
, Tuple.Create(Tuple.Create("", 2785), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/bootstrap-maxlength.min.js")
, 2785), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2852), Tuple.Create("\"", 2894)
, Tuple.Create(Tuple.Create("", 2858), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/bootstrap.touchspin.js")
, 2858), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2921), Tuple.Create("\"", 2955)
, Tuple.Create(Tuple.Create("", 2927), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/select2.min.js")
, 2927), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2982), Tuple.Create("\"", 3008)
, Tuple.Create(Tuple.Create("", 2988), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/app.js")
, 2988), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3035), Tuple.Create("\"", 3073)
, Tuple.Create(Tuple.Create("", 3041), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/form-validation.js")
, 3041), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3100), Tuple.Create("\"", 3134)
, Tuple.Create(Tuple.Create("", 3106), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/form-wizard.js")
, 3106), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3161), Tuple.Create("\"", 3199)
, Tuple.Create(Tuple.Create("", 3167), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/form-components.js")
, 3167), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3226), Tuple.Create("\"", 3260)
, Tuple.Create(Tuple.Create("", 3232), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/grid-script.js")
, 3232), false)
);

WriteLiteral("></script>   \r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3290), Tuple.Create("\"", 3326)
, Tuple.Create(Tuple.Create("", 3296), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/kendo.web.min.js")
, 3296), false)
);

WriteLiteral("></script>\r\n\r\n      <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3354), Tuple.Create("\"", 3399)
, Tuple.Create(Tuple.Create("", 3360), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery.backstretch.min.js")
, 3360), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3426), Tuple.Create("\"", 3462)
, Tuple.Create(Tuple.Create("", 3432), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/kendo.all.min.js")
, 3432), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3489), Tuple.Create("\"", 3530)
, Tuple.Create(Tuple.Create("", 3495), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/kendo.sortable.min.js")
, 3495), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3557), Tuple.Create("\"", 3586)
, Tuple.Create(Tuple.Create("", 3563), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/toastr.js")
, 3563), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3613), Tuple.Create("\"", 3642)
, Tuple.Create(Tuple.Create("", 3619), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/moment.js")
, 3619), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3669), Tuple.Create("\"", 3708)
, Tuple.Create(Tuple.Create("", 3675), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/moment-range.min.js")
, 3675), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3735), Tuple.Create("\"", 3770)
, Tuple.Create(Tuple.Create("", 3741), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/moment-range.js")
, 3741), false)
);

WriteLiteral("></script>\r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3797), Tuple.Create("\"", 3841)
, Tuple.Create(Tuple.Create("", 3803), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/moment-range.bare.min.js")
, 3803), false)
);

WriteLiteral("></script>    \r\n       <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3872), Tuple.Create("\"", 3912)
, Tuple.Create(Tuple.Create("", 3878), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/moment-range.bare.js")
, 3878), false)
);

WriteLiteral("></script>       \r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3945), Tuple.Create("\"", 3982)
, Tuple.Create(Tuple.Create("", 3951), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery.confirm.js")
, 3951), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4006), Tuple.Create("\"", 4049)
, Tuple.Create(Tuple.Create("", 4012), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/knockout-3.0.0.debug.js")
, 4012), false)
);

WriteLiteral("></script>      \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4079), Tuple.Create("\"", 4123)
, Tuple.Create(Tuple.Create("", 4085), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/knockout-sortable.min.js")
, 4085), false)
);

WriteLiteral("></script>          \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4157), Tuple.Create("\"", 4199)
, Tuple.Create(Tuple.Create("", 4163), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/knockout.validation.js")
, 4163), false)
);

WriteLiteral("></script>  \r\n     <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4226), Tuple.Create("\"", 4272)
, Tuple.Create(Tuple.Create("", 4232), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/knockout.mapping-latest.js")
, 4232), false)
);

WriteLiteral("></script>      \r\n     <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4303), Tuple.Create("\"", 4344)
, Tuple.Create(Tuple.Create("", 4309), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/knockout-kendo.min.js")
, 4309), false)
);

WriteLiteral("></script>  \r\n    \r\n                   \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4409), Tuple.Create("\"", 4468)
, Tuple.Create(Tuple.Create("", 4415), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/twitter-bootstrap-hover-dropdown.min.js")
, 4415), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4506), Tuple.Create("\"", 4550)
, Tuple.Create(Tuple.Create("", 4512), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery.slimscroll.min.js")
, 4512), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4588), Tuple.Create("\"", 4629)
, Tuple.Create(Tuple.Create("", 4594), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery.blockui.min.js")
, 4594), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4667), Tuple.Create("\"", 4706)
, Tuple.Create(Tuple.Create("", 4673), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery.cokie.min.js")
, 4673), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4744), Tuple.Create("\"", 4785)
, Tuple.Create(Tuple.Create("", 4750), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery.uniform.min.js")
, 4750), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4823), Tuple.Create("\"", 4865)
, Tuple.Create(Tuple.Create("", 4829), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery.validate.min.js")
, 4829), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4903), Tuple.Create("\"", 4948)
, Tuple.Create(Tuple.Create("", 4909), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery.backstretch.min.js")
, 4909), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4986), Tuple.Create("\"", 5036)
, Tuple.Create(Tuple.Create("", 4992), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery.bootstrap.wizard.min.js")
, 4992), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5074), Tuple.Create("\"", 5108)
, Tuple.Create(Tuple.Create("", 5080), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/spinner.min.js")
, 5080), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5146), Tuple.Create("\"", 5189)
, Tuple.Create(Tuple.Create("", 5152), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/bootstrap-datepicker.js")
, 5152), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5227), Tuple.Create("\"", 5267)
, Tuple.Create(Tuple.Create("", 5233), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/jquery.dataTables.js")
, 5233), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5305), Tuple.Create("\"", 5340)
, Tuple.Create(Tuple.Create("", 5311), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/DT_bootstrap.js")
, 5311), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5378), Tuple.Create("\"", 5424)
, Tuple.Create(Tuple.Create("", 5384), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/bootstrap-maxlength.min.js")
, 5384), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5462), Tuple.Create("\"", 5504)
, Tuple.Create(Tuple.Create("", 5468), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/bootstrap.touchspin.js")
, 5468), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5542), Tuple.Create("\"", 5576)
, Tuple.Create(Tuple.Create("", 5548), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/select2.min.js")
, 5548), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5614), Tuple.Create("\"", 5640)
, Tuple.Create(Tuple.Create("", 5620), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/app.js")
, 5620), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5678), Tuple.Create("\"", 5716)
, Tuple.Create(Tuple.Create("", 5684), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/form-validation.js")
, 5684), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5754), Tuple.Create("\"", 5788)
, Tuple.Create(Tuple.Create("", 5760), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/form-wizard.js")
, 5760), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5826), Tuple.Create("\"", 5864)
, Tuple.Create(Tuple.Create("", 5832), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/form-components.js")
, 5832), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5902), Tuple.Create("\"", 5935)
, Tuple.Create(Tuple.Create("", 5908), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/login-soft.js")
, 5908), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5973), Tuple.Create("\"", 6006)
, Tuple.Create(Tuple.Create("", 5979), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/newsTicker.js")
, 5979), false)
);

WriteLiteral("></script>  \r\n                <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6044), Tuple.Create("\"", 6073)
, Tuple.Create(Tuple.Create("", 6050), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/toastr.js")
, 6050), false)
);

WriteLiteral("></script>  \r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6101), Tuple.Create("\"", 6150)
, Tuple.Create(Tuple.Create("", 6107), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/CustomisedControls.js")
, 6107), false)
);

WriteLiteral("></script>\r\n\r\n           <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6183), Tuple.Create("\"", 6223)
, Tuple.Create(Tuple.Create("", 6189), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/eGateRoot.js")
, 6189), false)
);

WriteLiteral("></script>\r\n\r\n    \r\n\r\n\r\n\r\n    <link");

WriteLiteral(" rel=\"shortcut icon\"");

WriteAttribute("href", Tuple.Create(" href=\"", 6279), Tuple.Create("\"", 6330)
            
            #line 106 "..\..\Views\Shared\_LoginLayout.cshtml"
, Tuple.Create(Tuple.Create("", 6286), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/Images/favicon.ico")
            
            #line default
            #line hidden
, 6286), false)
);

WriteLiteral("/>  \r\n\r\n\r\n<style>\r\n        .validationMessage {\r\n            background: none rep" +
"eat scroll 0% 0% #D45252;\r\n            border-radius: 3px;\r\n            color: #" +
"FFF;\r\n            margin: -5px 0px 0px;\r\n            font-size: 10px;\r\n         " +
"   padding: 0px 6px;\r\n            z-index: 999;\r\n            position: absolute;" +
"\r\n        }\r\n\r\n        .validationError {\r\n            background: #d45252;\r\n   " +
"         border-radius: 3px 3px 3px 3px;\r\n            color: white;\r\n           " +
" margin: -5px 0 0 0px;\r\n            font-size: 10px;\r\n            padding: 0px 6" +
"px;\r\n            z-index: 999;\r\n            position: absolute;\r\n            whi" +
"te-space: nowrap;\r\n            left: auto;\r\n        }\r\n\r\n        .inputError {\r\n" +
"            border: 1px solid #B94A48 !important;\r\n            border-color: #B9" +
"4A48;\r\n        }\r\n\r\n        .newsCss {\r\n            height: auto;\r\n            b" +
"order: 0px solid #c3501d;\r\n        }\r\n\r\n        .rem {\r\n            display: inl" +
"ine;\r\n        }\r\n\r\n        .shead {\r\n            background-color: #35aa47;\r\n   " +
"         color: #000; /*text-align:center; */\r\n            min-width: 150px;\r\n  " +
"          text-indent: 5px;\r\n            padding: 3px;\r\n            margin-botto" +
"m: 5px;\r\n            display: block;\r\n        }\r\n\r\n        #newsData {\r\n        " +
"    width: 100%;\r\n            display: inline-block;\r\n            opacity: 1;\r\n " +
"           filter: alpha(opacity=100);\r\n        }\r\n\r\n        .l {\r\n            b" +
"order: 0;\r\n            float: right;\r\n        }\r\n\r\n        .r { /*margin-right:-" +
"21px;*/\r\n            border: 0;\r\n            float: right;\r\n        }\r\n\r\n       " +
" .navbar-fixed-top, .navbar-fixed-bottom {\r\n            position: relative;\r\n   " +
"         right: 0;\r\n            left: 0;\r\n            z-index: 1030;\r\n        }\r" +
"\n\r\n        .portlet > .portlet-title > .tools > a.expand {\r\n            margin-b" +
"ottom: 2px;\r\n            background-image: url(/Content/Images/portlet-collapse-" +
"icon-white.png) !important;\r\n            width: 14px;\r\n            text-decorati" +
"on: none !important;\r\n        }\r\n\r\n        .portlet > .portlet-title > .tools > " +
"a.collapse {\r\n            margin-bottom: 2px;\r\n            background-image: url" +
"(/Content/Images/portlet-expand-icon-white.png) !important;\r\n            width: " +
"14px;\r\n            text-decoration: none !important;\r\n        }\r\n\r\n        .usel" +
"inkbg {\r\n            background-color: #ace33c;\r\n            border: 0px solid #" +
"f00;\r\n        }\r\n\r\n        .caption {\r\n            margin-left: -200px;\r\n       " +
"     color: #fff;\r\n            font-size: 14px;\r\n        }\r\n\r\n        .portlet.b" +
"ox.green {\r\n            border: 1px solid #35A446;\r\n            border-top: 0;\r\n" +
"            border-radius: 3px!important;\r\n        }\r\n\r\n            .portlet.box" +
".green > .portlet-title {\r\n                background-color: rgba(53, 170, 71, 0" +
");\r\n                padding: 7px;\r\n            }\r\n\r\n        .portlet > .portlet-" +
"title {\r\n            margin-bottom: 15px;\r\n            border-bottom: 0px solid " +
"#eee;\r\n        }\r\n\r\n        .portlet-body {\r\n            background-color: #fff " +
"!important;\r\n        }\r\n\r\n        .usereq div > a {\r\n            padding: 6px 0 " +
"6px 13px;\r\n            color: #333;\r\n            text-decoration: none;\r\n       " +
"     display: block;\r\n            clear: both;\r\n            font-weight: normal;" +
"\r\n            line-height: 18px;\r\n            white-space: nowrap;\r\n            " +
"font-size: 13px;\r\n        }\r\n\r\n            .usereq div > a:hover,\r\n            ." +
"usereq .active > a,\r\n            .usereq div .active > a:hover {\r\n              " +
"  text-decoration: none;\r\n                background-image: none;\r\n             " +
"   background-color: #eee;\r\n                color: #333;\r\n                filter" +
": none;\r\n            }\r\n\r\n        .bfont {\r\n            font-size: 13px !importa" +
"nt;\r\n        }\r\n\r\n        .dropdown-menu {\r\n            width: 238px !important;" +
"\r\n        }\r\n\r\n        .header .navbar-nav > li.dropdown .dropdown-toggle {\r\n   " +
"         margin: 3px;\r\n        }\r\n        .dropdown-links {display:inline; paddi" +
"ng:0px !important; border:0px !important; font-size: 14px;color: #032f52;text-de" +
"coration: underline;\r\n        }\r\n\r\n        .dropdown-menu.extended li:last-child" +
" a {border:0px !important; padding:0px !important; display:inline !important; fo" +
"nt-size: 12px;color: #0044cc;text-decoration: none; \r\n        }\r\n        .dropdo" +
"wn-menu.extended li a:hover {font-weight:bold; text-decoration:underline; backgr" +
"ound-color:#fff;\r\n        }\r\n        .btn {box-shadow: 1px 1px 1px #001528 !impo" +
"rtant;\r\n        }\r\n    </style>\r\n\r\n\r\n</head>\r\n<body");

WriteLiteral(" id=\"classadd\"");

WriteLiteral(" class=\"page-header-fixed page-footer-fixed page-sidebar-fixed\"");

WriteLiteral(">\r\n\r\n\r\n    <section");

WriteLiteral(" class=\"content-wrapper main-content clear-fix\"");

WriteLiteral(">  \r\n        \r\n");

WriteLiteral("                ");

            
            #line 278 "..\..\Views\Shared\_LoginLayout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("        \r\n    </section>\r\n\r\n");

WriteLiteral("    ");

            
            #line 281 "..\..\Views\Shared\_LoginLayout.cshtml"
Write(RenderSection("JavaScript", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 282 "..\..\Views\Shared\_LoginLayout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script>   \r\n    \teGateRoot.rootPath = \'");

            
            #line 284 "..\..\Views\Shared\_LoginLayout.cshtml"
                         Write(Url.Content("~"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    \tvar application = {viewbag : ");

            
            #line 285 "..\..\Views\Shared\_LoginLayout.cshtml"
                                Write(Helpers.ToJson(Html, ViewBag));

            
            #line default
            #line hidden
WriteLiteral("};\r\n \t\r\n    \tjQuery(document).ready(function () {\r\n    \t\tApp.init();\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t");

            
            #line 289 "..\..\Views\Shared\_LoginLayout.cshtml"
                               Write(RenderSection("ko_apply", required: false));

            
            #line default
            #line hidden
WriteLiteral(";\r\n    \t});\r\n    \t\r\n\r\n\r\n    </script>\r\n  \r\n</body>\r\n\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
