#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/User/User.cshtml")]
    public partial class _Views_User_User_cshtml : System.Web.Mvc.WebViewPage<PortKonnect.UserAccessManagement.Domain.DTOS.PrivilegeDTO>
    {
        public _Views_User_User_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\User\User.cshtml"
  
	ViewBag.Title = "User";
	Layout = "~/Views/Shared/_eGateLayout.cshtml";
    

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("<script");

WriteAttribute("src", Tuple.Create(" src=\"", 180), Tuple.Create("\"", 229)
, Tuple.Create(Tuple.Create("", 186), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/CustomisedControls.js")
, 186), false)
);

WriteLiteral("></script>\r\n\t<script");

WriteAttribute("src", Tuple.Create(" src=\"", 250), Tuple.Create("\"", 312)
, Tuple.Create(Tuple.Create("", 256), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/Model/UserRegistrationModel.js")
, 256), false)
);

WriteLiteral("></script>\r\n\t<script");

WriteAttribute("src", Tuple.Create(" src=\"", 333), Tuple.Create("\"", 403)
, Tuple.Create(Tuple.Create("", 339), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/ViewModel/UserRegistrationViewModel.js")
, 339), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

DefineSection("ko_apply", () => {

WriteLiteral("\r\n\tvar viewModel = new eGateRoot.UserRegistrationViewModel(\"");

            
            #line 15 "..\..\Views\User\User.cshtml"
                                                        Write(ViewBag.userId);

            
            #line default
            #line hidden
WriteLiteral("\",\"");

            
            #line 15 "..\..\Views\User\User.cshtml"
                                                                          Write(ViewBag.Path);

            
            #line default
            #line hidden
WriteLiteral("\");  \r\n  ko.applyBindingsWithValidation(viewModel, $(\"#User\")[0], { insertMessage" +
"s: false, messagesOnModified: false, grouping: { deep: true }});\r\n");

});

WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"User\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" data-bind=\"visible: viewMode() == \'Form\', template: { name: \'User-template\' }\"");

WriteLiteral("></div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n\r\n<div");

WriteLiteral(" class=\"portlet-body\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"table-toolbar\"");

WriteLiteral(">\r\n\r\n\t<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"User-template\"");

WriteLiteral(@">

	<div class=""portlet-body"">
	<div class=""table-toolbar"">
	<div class=""portlet portlet-body form"" data-bind=""loadingWhen: $root.viewModelHelper.isLoading"">
	<div class=""form-wizard"">
	<div class=""form-body form-horizontal"" data-bind=""with: UserRegistrationModel"">
	<div class=""row"">
	    <div class=""col-md-12"">
	        <h3 class=""page-title""><span id=""spnTitle""></span></h3>
	        <ul class=""page-breadcrumb breadcrumb""></ul>
	    </div>
	</div>


	");

WriteLiteral("\r\n\t<div class=\"tab-pane active\" id=\"tab1\">\r\n\t<div class=\"form-group\">\r\n\r\n\r\n\t<fiel" +
"dset>\r\n\t<legend>Users</legend>\r\n\t<div class=\"row\">\r\n\t    <div class=\"col-md-6 ie" +
"-validation moz-margin1\">\r\n\t        <div class=\"form-group\">\r\n\t            <labe" +
"l class=\"control-label col-md-5\">Partner Type :<span class=\"required\">*</span></" +
"label>\r\n\t            <div class=\"col-md-7\">\r\n\t                <div data-bind=\"vi" +
"sible: $root.IsPartnerTypelabel\" class=\"control-label\">\r\n\t                    <l" +
"abel class=\"displaytxt col-md-12\" data-bind=\"text: PartnerTypeCode\"></label>\r\n\t " +
"               </div>\r\n\t                <div data-bind=\"visible: $root.IsPartner" +
"TypeVisible\">\r\n\t                    <div class=\"form-control\" style=\"line-height" +
": 20px;\">\r\n\t                        <select id=\"ddlPartnerType\" name=\"\" data-bin" +
"d=\"kendoDropDownList: { data: $root.PartnerTypes, dataTextField: \'PartnerTypeNam" +
"e\', optionLabel: \'Select...\', dataValueField: \'PartnerTypeId\', value: PartnerTyp" +
"e, enable: $root.PartnerTypeenable }, event: { change: $parent.selectPartnerName" +
" }\"></select>\r\n\t                        <span class=\"validationError\" data-bind=" +
"\"validationMessage: PartnerType\"></span>\r\n\t                    </div>\r\n\t        " +
"        </div>\r\n\t            </div>\r\n\t        </div>\r\n\t    </div>\r\n\r\n\t    <div c" +
"lass=\"col-md-6 ie-validation moz-margin1\">\r\n\t        <div class=\"form-group\">\r\n\t" +
"            <label class=\"control-label col-md-5\">Partner :<span class=\"required" +
"\">*</span></label>\r\n\t            <div class=\"col-md-7\">\r\n\t                <div c" +
"lass=\"form-control\" style=\"line-height: 20px;\">\r\n\t                    <select id" +
"=\"ddlPartner\" name=\"\" data-bind=\"enable: $root.PartnerNameenable,kendoDropDownLi" +
"st: { data: $root.Partners, dataTextField: \'PartnerName\', optionLabel: \'Select.." +
".\', dataValueField: \'PartnerCode\', value: PartnerId }\"></select>\r\n\t             " +
"       <span class=\"validationError \" data-bind=\"validationMessage: PartnerId\"><" +
"/span>\r\n\t                </div>\r\n\t            </div>\r\n\t        </div>\r\n\t    </di" +
"v>\r\n\r\n\r\n\r\n\t</div>\r\n\t<div class=\"row\">\r\n\r\n\t    <div class=\"col-md-6\" data-bind=\"v" +
"isible: $root.displayForSpecialRoles\">\r\n\t        <div class=\"form-group\">\r\n\r\n\t  " +
"          <label class=\"control-label col-md-5\">User Name :<span class=\"required" +
"\">*</span></label>\r\n\t            <div class=\"col-md-7\">\r\n\r\n\t                <inp" +
"ut type=\"text\" id=\"userName1\" name=\"\" class=\"form-control\" data-bind=\"value: Use" +
"rName, event: { keypress: $root.validationHelper.ValidateAlphaNumeric, change: $" +
"root.validateUserName }, enable: $root.IsUserNameEnable\" maxlength=\"30\">\r\n\t     " +
"           <span class=\"validationError\" data-bind=\"validationMessage: UserName\"" +
"></span>\r\n\t            </div>\r\n\r\n\t        </div>\r\n\t    </div>\r\n\t    <div class=\"" +
"col-md-6\" data-bind=\"visible: $root.displayUsername\">\r\n\t        <div class=\"form" +
"-group\">\r\n\t            <div data-bind=\"\" class=\"control-label\">\r\n\r\n\t            " +
"</div>\r\n\t            <label class=\"control-label col-md-5\">User Name :<span clas" +
"s=\"required\">*</span></label>\r\n\t            <div class=\"col-md-7\">\r\n\t           " +
"     <label class=\"displaytxt control-label col-md-4\" data-bind=\"text: PartnerTy" +
"peId() + $root.UserNameSeperator() + MemberTypeCode() + $root.UserNameSeperator(" +
"), visible: $root.showLabels\"></label>\r\n\r\n\t                <div class=\"col-md-8\"" +
"><input type=\"text\" id=\"userName\" name=\"\" class=\"form-control\" data-bind=\"value:" +
" UserName, event: { keypress: $root.validationHelper.ValidateAlphaNumeric, chang" +
"e: $root.validateUserName }, enable: $root.IsUserNameEnable\" maxlength=\"24\">\r\n\t " +
"               </div>\r\n\t                <span class=\"validationError\" data-bind=" +
"\"validationMessage: UserName\" style=\"display: none;\"></span>\r\n\t            </div" +
">\r\n\r\n\t        </div>\r\n\t    </div>\r\n\t    <div class=\"col-md-6\">\r\n\t        <div cl" +
"ass=\"form-group\">\r\n\t            <label class=\"control-label col-md-5\">First Name" +
":<span class=\"required\">*</span></label>\r\n\t            <div class=\"col-md-7\">\r\n\r" +
"\n\t                <input type=\"text\" id=\"firstName\" name=\"\" class=\"form-control\"" +
" data-bind=\"value: FirstName, event: { keypress: $root.validationHelper.Validate" +
"AlphabetsWithSpaces_keypressEvent }, enable: $root.IsEnable\" maxlength=\"50\">\r\n\t " +
"               <span class=\"validationError\" data-bind=\"validationMessage: First" +
"Name\"></span>\r\n\t            </div>\r\n\t        </div>\r\n\t    </div>\r\n\t</div>\r\n\r\n\t<d" +
"iv class=\"row\">\r\n\r\n\t    <div class=\"col-md-6\">\r\n\t        <div class=\"form-group\"" +
">\r\n\t            <label class=\"control-label col-md-5\">Last Name:<span class=\"req" +
"uired\">*</span></label>\r\n\t            <div class=\"col-md-7\">\r\n\r\n\t               " +
" <input type=\"text\" id=\"lastName\" name=\"\" class=\"form-control\" data-bind=\"value:" +
" LastName, event: { keypress: $root.validationHelper.ValidateAlphabetsWithSpaces" +
"_keypressEvent }, enable: $root.IsEnable\" maxlength=\"50\">\r\n\t                <spa" +
"n class=\"validationError\" data-bind=\"validationMessage: LastName\"></span>\r\n\t    " +
"        </div>\r\n\t        </div>\r\n\t    </div>\r\n\r\n\t    <div class=\"col-md-6\">\r\n\t  " +
"      <div class=\"form-group\">\r\n\t            <label class=\"control-label col-md-" +
"5\">User Ports :<span class=\"required\">*</span></label>\r\n\t            <div class=" +
"\"col-md-7\">\r\n\t                <input id=\"userPort\" data-bind=\"kendoMultiSelect: " +
"{ data: $root.Ports, dataTextField: \'PortName\', dataValueField: \'PortCode\', valu" +
"e: UserPortArray, enable: $root.IsEnable }\"/>\r\n\r\n\t                <span class=\"v" +
"alidationError\" data-bind=\"validationMessage: UserPortArray\"></span>\r\n\t         " +
"   </div>\r\n\r\n\t        </div>\r\n\t    </div>\r\n\r\n\t</div>\r\n\r\n\t<div class=\"row\">\r\n\r\n\t " +
"   <div class=\"col-md-6\">\r\n\t        <div class=\"form-group\">\r\n\t            <labe" +
"l class=\"control-label col-md-5\">Email Id :<span class=\"required\">*</span></labe" +
"l>\r\n\t            <div class=\"col-md-7\">\r\n\t                <input type=\"text\" id=" +
"\"emailId\" name=\"\" onchange=\" validateEmailId() \" class=\"form-control\" data-bind=" +
"\"value: EmailId, event: { keypress: $root.validationHelper.ValidateAlphanumericE" +
"mail }, enable: $root.IsEnable\" maxlength=\"50\">\r\n\t                <span class=\"v" +
"alidationError\" id=\"validationEmailId\"></span>\r\n\t            </div>\r\n\r\n\t        " +
"</div>\r\n\t    </div>\r\n\r\n\t    <div class=\"col-md-6\">\r\n\t        <div class=\"form-gr" +
"oup\">\r\n\t            <label class=\"control-label col-md-5 \">Contact Number :<span" +
" class=\"required\">*</span></label>\r\n\t            <div class=\"col-md-7 ie-validat" +
"ion moz-margin1\">\r\n\r\n\t                <input type=\"text\" id=\"contactNumber\" name" +
"=\"\" class=\"form-control\" data-bind=\"value: ContactNumber, event: { keypress: $ro" +
"ot.validationHelper.ValidateNumeric }, enable: $root.IsEnable\" maxlength=\"13\">\r\n" +
"\t                <span class=\"validationError \" id=\"contactNum\" data-bind=\"valid" +
"ationMessage: ContactNumber\"></span>\r\n\t            </div>\r\n\t        </div>\r\n\t   " +
" </div>\r\n\r\n\r\n\t</div>\r\n\r\n\t<div class=\"row\">\r\n\t    <div class=\"col-md-6\">\r\n\t      " +
"  <div class=\"form-group\">\r\n\t            <label id=\"lblheading4\" class=\"col-md-5" +
" control-label\">Roles:<span class=\"required\" style=\"color: red\">*</span></label>" +
"\r\n\t            <div class=\"col-md-7\">\r\n\r\n\t                <input id=\"userRole\" o" +
"nchange=\" validateRole(this); \" data-bind=\"kendoMultiSelect: { data: $root.Roles" +
"List, dataTextField: \'RoleName\', dataValueField: \'RoleId\', value: UserRoleArray," +
" enable: $root.IsEnable }\"/>\r\n\r\n\t                <span id=\"spnrole\" class=\"valid" +
"ationError\"></span>\r\n\t            </div>\r\n\t        </div>\r\n\t    </div>\r\n\r\n\t</div" +
">\r\n\t<div class=\"row\">\r\n\t    <div class=\"col-md-6\" data-bind=\"visible: $root.IsRe" +
"cordStatus\">\r\n\t        <div class=\"form-group\">\r\n\t            <label class=\"cont" +
"rol-label col-md-5\">Status :<span class=\"required\">&nbsp;&nbsp;</span></label>\r\n" +
"\t            <div class=\"col-md-7 control-label\">\r\n\t                <label class" +
"=\"displaytxt col-md-12\" data-bind=\"text: RecordStatus\"></label>\r\n\t            </" +
"div>\r\n\t        </div>\r\n\t    </div>\r\n\r\n\t</div>\r\n\t<fieldset data-bind=\"visible: $r" +
"oot.IsUpdate\" >\r\n\t    <legend>Log In Details</legend>\r\n\t    <div class=\"row\" >\r\n" +
"\t        <div class=\"col-md-4\">\r\n\t            <div class=\"form-group\">\r\n\t       " +
"         <label class=\"control-label col-md-6\">Password Expiry Date :<span class" +
"=\"required\">&nbsp;&nbsp;</span></label>\r\n\t                <div class=\"col-md-5\">" +
"\r\n\t                    ");

WriteLiteral("\r\n\t                    <input type=\"text\" id=\"datetimePwdExpiryDate\" class=\"form-" +
"control date-picker\" onkeydown=\"\" data-bind=\"value: PwdExpiryDate \" name=\"\" maxl" +
"ength=\"12\"/>\r\n\t                </div>\r\n\r\n\t            </div>\r\n\t        </div>\r\n\t" +
"        <div class=\"col-md-4\">\r\n\t            <div class=\"form-group\">\r\n\t        " +
"        <label class=\"control-label col-md-6\">Valid To Date :<span class=\"requir" +
"ed\">&nbsp;&nbsp;</span></label>\r\n\t                <div class=\"col-md-5\">\r\n\t     " +
"               <input type=\"text\" id=\"datetimeValidToDate\" class=\"form-control d" +
"ate-picker\" onkeydown=\"\" data-bind=\" value: validToDate\" name=\"\" maxlength=\"12\"/" +
">\r\n\t                </div>\r\n\r\n\t            </div>\r\n\t        </div>\r\n\t        <di" +
"v class=\"col-md-4\">\r\n\t            <div class=\"form-group\">\r\n\t                <la" +
"bel class=\"control-label col-md-6\">Last Log In Date :<span class=\"required\">&nbs" +
"p;&nbsp;</span></label>\r\n\t                <div class=\"col-md-5\">\r\n\t             " +
"       <input type=\"text\" id=\"datetimeLogTime\" class=\"form-control date-picker\" " +
" data-bind=\" value: LogTime \" name=\"\" maxlength=\"12\"/>\r\n\r\n\t                </div" +
">\r\n\r\n\t            </div>\r\n\t        </div>\r\n\t    </div>\r\n\r\n\t    <div class=\"row\">" +
"\r\n\t        <div class=\"col-md-4\">\r\n\t            <div class=\"form-group\">\r\n\t     " +
"           <label class=\"control-label col-md-6\">Is Dormant User? :<span class=\"" +
"required\">&nbsp;&nbsp;</span></label>\r\n\t                <div class=\"col-md-5\">\r\n" +
"\t                    <input type=\"Checkbox\" id=\"IsDormantUser\" name=\"IsDormantUs" +
"er\" data-bind=\"checked: $parent.isDormantUser, enable: $root.isDormantEnable\" di" +
"sabled=\"\">\r\n\t                </div>\r\n\r\n\t            </div>\r\n\t        </div>\r\n\t  " +
"      <div class=\"col-md-4\">\r\n\t            <div class=\"form-group\">\r\n\t          " +
"      <label class=\"control-label col-md-6\">InCorrect Logins :<span class=\"requi" +
"red\">&nbsp;&nbsp;</span></label>\r\n\t                <div class=\"col-md-5\">\r\n\t    " +
"                <input type=\"text\" class=\"form-control\" id=\"InCorrectLogins\" nam" +
"e=\"InCorrectLogins\" data-bind=\"value: InCorrectLogins,event: { keypress: $root.v" +
"alidationHelper.ValidateNumericChange }\" maxlength=\"2\">\r\n\t                </div>" +
"\r\n\r\n\t            </div>\r\n\t        </div>\r\n            <div class=\"col-md-4\"></di" +
"v>\r\n            </div>\r\n\r\n            </fieldset>\r\n\r\n\r\n\r\n            <fieldset>\r" +
"\n                <legend>Notification Required</legend>\r\n                <div cl" +
"ass=\"row\">\r\n                    <div class=\"form-group\">\r\n                      " +
"  <div class=\"col-md-4\" data-bind=\"with: UserPreference\">\r\n                     " +
"       <label class=\"control-label col-md-6\">Is Email Required :</label>\r\n      " +
"                      <div class=\"col-md-6\">\r\n                                <i" +
"nput type=\"checkbox\" name=\"\" id=\"isEmail\" class=\"form-control\" data-bind=\"    ch" +
"ecked: SendNotificationEmail, enable: $root.IsEnable\">\r\n                        " +
"    </div>\r\n                        </div>\r\n                        <div class=\"" +
"col-md-4\" data-bind=\"with: UserPreference\">\r\n                            <label " +
"class=\"control-label col-md-6\">Is SMS Required :</label>\r\n                      " +
"      <div class=\"col-md-6\">\r\n                                <input type=\"check" +
"box\" name=\"\" id=\"isSms\" class=\"form-control\" data-bind=\"    checked: SendNotific" +
"ationSms, enable: $root.IsEnable\">\r\n                            </div>\r\n        " +
"                </div>\r\n                        <div class=\"col-md-4\" data-bind=" +
"\"with: UserPreference\">\r\n                            <label class=\"control-label" +
" col-md-8\">Is System Notification Required :</label>\r\n                          " +
"  <div class=\"col-md-4\">\r\n                                <input type=\"checkbox\"" +
" name=\"\" id=\"isNotification\" class=\"form-control\" data-bind=\"    checked: SendSy" +
"stemNotification, enable: $root.IsEnable\">\r\n                            </div>\r\n" +
"                        </div>\r\n                    </div>\r\n                </di" +
"v>\r\n\r\n            </fieldset>\r\n\r\n\r\n\r\n\r\n\r\n        </fieldset>\r\n\r\n\r\n\r\n\r\n\t\t\t\t\t\t\t\t\t\t" +
"<div class=\"btns-group form-actions fluid\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" val" +
"ue=\"Save\" class=\"btn green\" data-bind=\"click: $root.SaveScreen, visible: $root.I" +
"sSave\" class=\"btn green\" />\r\n\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" value=\"Update\" cl" +
"ass=\"btn green\" data-bind=\"click: $root.UpdateScreen, visible: $root.IsUpdate\" /" +
">\r\n\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn blue\" data-bind=\"click: $root.Res" +
"etScreen, visible: $root.IsReset\">Reset</button>\r\n\t\t\t\t\t\t\t\t\t\t\t<button type=\"submi" +
"t\" class=\"btn default button-previous\" data-bind=\"click: $root.ExitScreen\"><i cl" +
"ass=\"m-icon-swapleft\"></i>Back</button>\r\n\r\n\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" clas" +
"s=\"btn blue\" data-bind=\"click: $root.Activate, visible: $root.IsActive\">Activate" +
"</button>\r\n\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn red\" data-bind=\"click: $r" +
"oot.DeActivate, visible: $root.IsInActive\">Deactivate</button>\r\n\r\n\t\t\t\t\t\t\t\t\t\t</di" +
"v>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t\t\t</div>\r\n\r\n\r\n\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t<" +
"/div>\r\n\r\n\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\r\n\t\t</script>\r\n\t</div>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
