#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/User/UserView.cshtml")]
    public partial class _Views_User_UserView_cshtml : System.Web.Mvc.WebViewPage<PortKonnect.UserAccessManagement.Domain.DTOS.PrivilegeDTO>
    {
        public _Views_User_UserView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\User\UserView.cshtml"
  
    ViewBag.Title = "User";    
    Layout = "~/Views/Shared/_eGateLayout.cshtml";
    

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("<script");

WriteAttribute("src", Tuple.Create(" src=\"", 190), Tuple.Create("\"", 239)
, Tuple.Create(Tuple.Create("", 196), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/CustomisedControls.js")
, 196), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 259), Tuple.Create("\"", 321)
, Tuple.Create(Tuple.Create("", 265), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/Model/UserRegistrationModel.js")
, 265), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 341), Tuple.Create("\"", 415)
, Tuple.Create(Tuple.Create("", 347), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/ViewModel/UserRegistrationViewViewModel.js")
, 347), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

DefineSection("ko_apply", () => {

WriteLiteral("\r\n  var viewModel = new eGateRoot.UserRegistrationViewViewModel(\"");

            
            #line 15 "..\..\Views\User\UserView.cshtml"
                                                          Write(ViewBag.userId);

            
            #line default
            #line hidden
WriteLiteral("\");  \r\n  ko.applyBindingsWithValidation(viewModel, $(\"#User\")[0], { insertMessage" +
"s: false, messagesOnModified: false, grouping: { deep: true }});\r\n");

});

WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"page-title\"");

WriteLiteral("><span");

WriteLiteral(" id=\"spnTitle\"");

WriteLiteral("></span></h3>\r\n        <ul");

WriteLiteral(" class=\"page-breadcrumb breadcrumb\"");

WriteLiteral("></ul>\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"User\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" data-bind=\"visible: viewMode() == \'Form\', template: { name: \'User-template\' }\"");

WriteLiteral("></div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n\r\n<div");

WriteLiteral(" class=\"portlet-body\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"table-toolbar\"");

WriteLiteral(">\r\n\r\n        <script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"User-template\"");

WriteLiteral(@">

            <div class=""portlet-body"">
                <div class=""table-toolbar"">



                    <div class=""portlet portlet-body form"" data-bind=""loadingWhen: $root.viewModelHelper.isLoading"">
                        <div class=""form-wizard"">
                            <div class=""form-body form-horizontal"" data-bind=""with: UserRegistrationModel"">
                                <div class=""tab-pane active"" id=""tab1"">
                                    <div class=""form-group"">
                                        <div class=""row"">
                                            <div class=""col-md-11""></div>
                                            <div class=""col-md-1"">
");

            
            #line 50 "..\..\Views\User\UserView.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\User\UserView.cshtml"
                                                 if (Model.HasPrivilege("eGateUserView")) //TODO: Need to implment Entity Functions as Enums
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                                <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"Edit\"");

WriteLiteral(" class=\"btn blue\"");

WriteLiteral(" data-bind=\"click: $root.EditUser\"");

WriteLiteral(" />\r\n");

            
            #line 53 "..\..\Views\User\UserView.cshtml"
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                            </div>\r\n                             " +
"           </div>\r\n\r\n                                        <fieldset>\r\n       " +
"                                     <legend>Users</legend>\r\n                   " +
"                         <div class=\"row\">\r\n                                    " +
"            <div class=\"col-md-5\">\r\n                                            " +
"        <div class=\"form-group\">\r\n                                              " +
"          <label class=\"control-label col-md-3\">Partner Type :</label>\r\n        " +
"                                                <div class=\"col-md-5 control-lab" +
"el\">\r\n                                                            <label class=\"" +
"displaytxt col-md-12\" data-bind=\"text: PartnerType\"></label>\r\n\r\n\r\n              " +
"                                          </div>\r\n                              " +
"                      </div>\r\n                                                </" +
"div>\r\n\r\n                                                <div class=\"col-md-6\">\r\n" +
"                                                    <div class=\"form-group\">\r\n  " +
"                                                      <label class=\"control-labe" +
"l col-md-6\">Partner :</label>\r\n                                                 " +
"       <div class=\"col-md-6 control-label\">\r\n                                   " +
"                         <label class=\"displaytxt col-md-12\" data-bind=\"text: Pa" +
"rtnerId\"></label>\r\n\r\n                                                        </d" +
"iv>\r\n                                                    </div>\r\n               " +
"                                 </div>\r\n\r\n\r\n\r\n                                 " +
"           </div>\r\n                                            <div class=\"row\">" +
"\r\n                                                <div class=\"col-md-5\">\r\n      " +
"                                              <div class=\"form-group\">\r\n\r\n      " +
"                                                  <label class=\"control-label co" +
"l-md-3\">User Name :</label>\r\n                                                   " +
"     <div class=\"col-md-5 control-label\">\r\n                                     " +
"                       <label class=\"displaytxt col-md-12\" data-bind=\"text: User" +
"Name\"></label>\r\n\r\n                                                        </div>" +
"\r\n\r\n                                                    </div>\r\n                " +
"                                </div>\r\n                                        " +
"        <div class=\"col-md-6\">\r\n                                                " +
"    <div class=\"form-group\">\r\n                                                  " +
"      <label class=\"control-label col-md-6\">First Name:</label>\r\n               " +
"                                         <div class=\"col-md-4 control-label\">\r\n " +
"                                                           <label class=\"display" +
"txt col-md-12\" data-bind=\"text: FirstName\"></label>\r\n\r\n\r\n                       " +
"                                 </div>\r\n                                       " +
"             </div>\r\n                                                </div>\r\n   " +
"                                         </div>\r\n\r\n                             " +
"               <div class=\"row\">\r\n\r\n                                            " +
"    <div class=\"col-md-5\">\r\n                                                    " +
"<div class=\"form-group\">\r\n                                                      " +
"  <label class=\"control-label col-md-3\">Last Name:</label>\r\n                    " +
"                                    <div class=\"col-md-5 control-label\">\r\n      " +
"                                                      <label class=\"displaytxt c" +
"ol-md-12\" data-bind=\"text: LastName\"></label>\r\n\r\n                               " +
"                         </div>\r\n                                               " +
"     </div>\r\n                                                </div>\r\n\r\n         " +
"                                       <div class=\"col-md-6\">\r\n                 " +
"                                   <div class=\"form-group\">\r\n                   " +
"                                     <label class=\"control-label col-md-6\">User " +
"Ports :</label>\r\n                                                        <div cl" +
"ass=\"col-md-4 control-label\">\r\n                                                 " +
"           <label class=\"displaytxt col-md-12\" data-bind=\"text: UserPortArray\"><" +
"/label>\r\n\r\n                                                        </div>\r\n\r\n   " +
"                                                 </div>\r\n                       " +
"                         </div>\r\n\r\n                                            <" +
"/div>\r\n\r\n\r\n                                            <div class=\"row\">\r\n\r\n\r\n\r\n" +
"                                                <div class=\"col-md-5\">\r\n        " +
"                                            <div class=\"form-group\">\r\n          " +
"                                              <label class=\"control-label col-md" +
"-3\">Email Id :</label>\r\n                                                        " +
"<div class=\"col-md-5 control-label\">\r\n                                          " +
"                  <label class=\"displaytxt col-md-12\" data-bind=\"text: EmailId\">" +
"</label>\r\n\r\n                                                        </div>\r\n\r\n  " +
"                                                  </div>\r\n                      " +
"                          </div>\r\n\r\n                                            " +
"    <div class=\"col-md-6\">\r\n                                                    " +
"<div class=\"form-group\">\r\n                                                      " +
"  <label class=\"control-label col-md-6\">Contact Number :</label>\r\n              " +
"                                          <div class=\"col-md-4 control-label\">\r\n" +
"                                                            <label class=\"displa" +
"ytxt col-md-12\" id=\"contactNumber\" data-bind=\"text: ContactNumber\"></label>\r\n\r\n\r" +
"\n                                                        </div>\r\n               " +
"                                     </div>\r\n                                   " +
"             </div>\r\n\r\n                                            </div>\r\n\r\n\r\n\r" +
"\n\r\n\r\n                                            <div class=\"row\">\r\n\r\n\r\n\r\n      " +
"                                          <div class=\"col-md-5\">\r\n              " +
"                                      <div class=\"form-group\">\r\n                " +
"                                        <label class=\"control-label col-md-3\">St" +
"atus : </label>\r\n                                                        <div cl" +
"ass=\"col-md-5 control-label\">\r\n                                                 " +
"           <label class=\"displaytxt col-md-12\" data-bind=\"text: RecordStatus\"></" +
"label>\r\n                                                        </div>\r\n        " +
"                                            </div>\r\n                            " +
"                    </div>\r\n\r\n                                            </div>" +
"\r\n\r\n                                            <div class=\"row\">\r\n\r\n\r\n\r\n       " +
"                                         <div class=\"col-md-5\" data-bind=\"visibl" +
"e:$root.isDormantVisible\">\r\n                                                    " +
"<div class=\"form-group\">\r\n                                                      " +
"  <label class=\"control-label col-md-3\">Dormant Status : </label>\r\n             " +
"                                           <div class=\"col-md-5 control-label\">\r" +
"\n                                                            <label class=\"displ" +
"aytxt col-md-12\" data-bind=\"text: DormantStatus\"></label>\r\n                     " +
"                                   </div>\r\n                                     " +
"               </div>\r\n                                                </div>\r\n\r" +
"\n                                            </div>\r\n\r\n                         " +
"                   <div class=\"row\">\r\n                                          " +
"      <div class=\"form-group\">\r\n                                                " +
"    <div class=\"col-md-4\" data-bind=\"with: UserPreference\">\r\n                   " +
"                                     <label class=\"control-label col-md-6\">Is Em" +
"ail Required :</label><input type=\"checkbox\" name=\"\" id=\"isEmail\" class=\"form-co" +
"ntrol\" data-bind=\"checked: SendNotificationEmail, enable: $root.ISCheckBox\">\r\n  " +
"                                                  </div>\r\n                      " +
"                              <div class=\"col-md-4\" data-bind=\"with: UserPrefere" +
"nce\">\r\n                                                        <label class=\"con" +
"trol-label col-md-6\">Is SMS Required :</label><input type=\"checkbox\" name=\"\" id=" +
"\"isEmail\" class=\"form-control\" data-bind=\"checked: SendNotificationSms, enable: " +
"$root.ISCheckBox\">\r\n                                                    </div>\r\n" +
"                                                    <div class=\"col-md-4\" data-b" +
"ind=\"with: UserPreference\">\r\n                                                   " +
"     <label class=\"control-label col-md-8\">Is System Notification Required :</la" +
"bel><input type=\"checkbox\" name=\"\" id=\"isEmail\" class=\"form-control\" data-bind=\"" +
"checked: SendSystemNotification, enable: $root.ISCheckBox\">\r\n                   " +
"                                 </div>\r\n                                       " +
"         </div>\r\n                                            </div>\r\n\r\n\r\n       " +
"                                 </fieldset>\r\n\r\n\r\n                              " +
"          <div class=\"btns-group form-actions fluid\">\r\n                         " +
"                   <input type=\"button\" value=\"Save\" class=\"btn green\" data-bind" +
"=\"click: $root.SaveScreen, visible: $root.IsSave\" class=\"btn green\" />\r\n\r\n      " +
"                                      <input type=\"button\" value=\"Update\" class=" +
"\"btn green\" data-bind=\"click: $root.UpdateScreen, visible: $root.IsUpdate\" />\r\n " +
"                                           <button type=\"submit\" class=\"btn blue" +
"\" data-bind=\"click: $root.ResetScreen, visible: $root.IsRest\">Reset</button>\r\n  " +
"                                          <button type=\"submit\" class=\"btn red\" " +
"data-bind=\"click: $root.ExitScreen\">Exit</button>\r\n\r\n                           " +
"                 <button type=\"submit\" class=\"btn blue\" data-bind=\"visible: $roo" +
"t.IsUpdate, visible: $root.IsUpdate\">Activate</button>\r\n                        " +
"                    <button type=\"submit\" class=\"btn red\" data-bind=\"visible: $r" +
"oot.IsUpdate, visible: $root.IsUpdate\">Deactivate</button>\r\n\r\n                  " +
"                      </div>\r\n                                    </div>\r\n      " +
"                          </div>\r\n\r\n                            </div>\r\n\r\n\r\n\r\n  " +
"                      </div>\r\n                    </div>\r\n\r\n\r\n                </" +
"div>\r\n            </div>\r\n\r\n        </script>\r\n    </div>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
