#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Role/Role.cshtml")]
    public partial class _Views_Role_Role_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Role_Role_cshtml()
        {
        }
        public override void Execute()
        {
DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32), Tuple.Create("\"", 80)
, Tuple.Create(Tuple.Create("", 38), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/kendo.all-v2016.2.607.min.js")
, 38), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 100), Tuple.Create("\"", 150)
, Tuple.Create(Tuple.Create("", 106), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/Model/RoleModel.js")
, 106), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 170), Tuple.Create("\"", 228)
, Tuple.Create(Tuple.Create("", 176), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/ViewModel/RoleViewModel.js")
, 176), false)
);

WriteLiteral("></script>\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 246), Tuple.Create("\"", 299)
, Tuple.Create(Tuple.Create("", 253), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/kendo.common-material.min.css")
, 253), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 327), Tuple.Create("\"", 373)
, Tuple.Create(Tuple.Create("", 334), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/kendo.material.min.css")
, 334), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 401), Tuple.Create("\"", 453)
, Tuple.Create(Tuple.Create("", 408), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/kendo.default.mobile.min.css")
, 408), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

});

WriteLiteral("\r\n");

DefineSection("ko_apply", () => {

WriteLiteral("\r\n    var viewModel = new eGateRoot.RoleViewModel(\"");

            
            #line 13 "..\..\Views\Role\Role.cshtml"
                                            Write(ViewBag.roleId);

            
            #line default
            #line hidden
WriteLiteral("\");  \r\n  ko.applyBindingsWithValidation(viewModel, $(\"#Role\")[0], { insertMessage" +
"s: false, messagesOnModified: false, grouping: { deep: true }});\r\n");

});

WriteLiteral(@"<style>
	.demo-section .k-checkbox:checked + .k-checkbox-label:before {
		background-color: #032F52 !important;
		border-color: #032F52 !important;
		color: #fff !important;
	}

	.demo-section .k-state-hover:hover {
		color: #444;
		background-color: #F1F6FA !important;
		border-color: #F1F6FA !important;
		font-weight: bold;
	}

	.demo-section .k-state-focused {
		color: #444;
		background-color: #F1F6FA !important;
		border-color: #F1F6FA !important;
		font-weight: bold;
	}

	.demo-section .k-checkbox:indeterminate + .k-checkbox-label:before {
		border-color: #ccc !important;
	}

	.demo-section .k-checkbox:indeterminate + .k-checkbox-label:before {
		border-width: 3px !important;
	}

	.demo-section .k-checkbox:indeterminate + .k-checkbox-label:after {
		background-color: #3687C8 !important;
		background-image: none;
		border-color: #3687C8 !important;
		border-radius: 0;
	}

	.demo-section .k-state-selected {
		color: #f00 !important;
		font-weight: bold;
	}

	.demo-section input.k-checkbox + label {
		margin-top: -9px;
	}

	.k-button {
		text-transform: none !important;
	}
</style>

<!-- BEGIN CONTENT -->
<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n\t\t<h3");

WriteLiteral(" class=\"page-title\"");

WriteLiteral("><span");

WriteLiteral(" id=\"spnTitle\"");

WriteLiteral("></span></h3>\r\n\t\t<ul");

WriteLiteral(" class=\"page-breadcrumb breadcrumb\"");

WriteLiteral("></ul>\r\n\t</div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"Role\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" data-bind=\"visible: viewMode() == \'Form\', template: { name: \'Role-template\' }\"");

WriteLiteral("></div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n\r\n<div");

WriteLiteral(" class=\"portlet-body\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"table-toolbar\"");

WriteLiteral(">\r\n\t\t<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"Role-template\"");

WriteLiteral(">\r\n\t\t\t<div class=\"portlet portlet-body form\" data-bind=\"loadingWhen: $root.viewMo" +
"delHelper.isLoading\">\r\n\t\t\t\t<div class=\"form-wizard\">\r\n\t\t\t\t\t<div class=\"form-body" +
" form-horizontal\" data-bind=\"with: roleModel\">\r\n\t\t\t\t\t\t");

WriteLiteral("\r\n\t\t\t\t\t\t<div class=\"tab-pane active\" id=\"tab1\">\r\n\t\t\t\t\t\t\t<div class=\"form-group\">\r" +
"\n\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"col-md-11\"></div>\r\n\t\t\t\t\t\t\t\t</di" +
"v>\r\n\t\t\t\t\t\t\t\t<fieldset>\r\n\t\t\t\t\t\t\t\t\t<legend>Role</legend>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row" +
"\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t" +
"\t\t\t\t\t\t\t<label class=\"control-label col-md-6\">Role Code :<span class=\"required\">*" +
"</span></label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"t" +
"ext\" id=\"applicationEntityCode\" name=\"\" class=\"form-control\" data-bind=\"value: R" +
"oleCode, enable: $root.IsRoleCodeEnable, event: { keypress: $root.validationHelp" +
"er.ValidateAlphaNumeric }\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"validationError\" data-bin" +
"d=\"validationMessage: RoleCode\"></span>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t\t\t\t\t\t\t</div>" +
"\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"for" +
"m-group\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label col-md-4\">Role Name:<span cla" +
"ss=\"required\">*</span></label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t" +
"\t<input type=\"text\" id=\"applicationName\" name=\"\" class=\"form-control\" data-bind=" +
"\"value: RoleName, enable: $root.IsRoleCodeEnable\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"va" +
"lidationError\" data-bind=\"validationMessage: RoleName\"></span>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</di" +
"v>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"r" +
"ow\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t" +
"\t\t\t\t\t\t\t\t\t\t<label class=\"control-label col-md-3\">Partner Types :<span class=\"requ" +
"ired\">*</span></label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<div cl" +
"ass=\"form-control\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"userPort\" data-bind=\"kendoMultiSe" +
"lect: { dataTextField: \'PartnerTypeName\', dataValueField: \'PartnerTypeId\', data:" +
" $parent.PartnerTypes, value: PartnerTypeArray }, event: { change: $root.changev" +
"alidatePartnerType }\"></select>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"validationError\" id=" +
"\"validatePartnerType\"></span>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t" +
"\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t\t\t\t\t<div>\r\n\t\t\t\t\t\t\t\t\t\t<field" +
"set>\r\n\t\t\t\t\t\t\t\t\t\t\t<legend>Modules & Sub Modules</legend>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"" +
"row demo-section \">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<div clas" +
"s=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label col-md-1\"></label>\r\n\t" +
"\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-9\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"Role1\" style=\"overf" +
"low: hidden\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"demo-section \" style=\"overflow: hidde" +
"n\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"treeview\" style=\"overflo" +
"w: hidden\"></div>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t\t" +
"\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t" +
"\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</fieldset>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t</f" +
"ieldset>\r\n\t\t\t\t\t\t\t\t<div class=\"btns-group form-actions fluid\">\r\n\t\t\t\t\t\t\t\t\t<input t" +
"ype=\"button\" value=\"Save\" class=\"btn green\" data-bind=\"click: $root.SaveRole, vi" +
"sible: $root.IsSave\" />\r\n\t\t\t\t\t\t\t\t\t<input type=\"button\" value=\"Update\" class=\"btn" +
" green\" data-bind=\"click: $root.UpdateRole, visible: $root.IsUpdate\" />\r\n\t\t\t\t\t\t\t" +
"\t\t<button type=\"submit\" class=\"btn blue\" data-bind=\"click: $root.ResetRole\">Rese" +
"t</button>\r\n\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn default button-previous\" d" +
"ata-bind=\"click: $root.ExitScreen\"><i class=\"m-icon-swapleft\"></i>Back</button>\r" +
"\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</di" +
"v>\r\n\t\t</script>\r\n\t</div>\r\n</div>\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
