#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Role/Roles.cshtml")]
    public partial class _Views_Role_Roles_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Role_Roles_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Role\Roles.cshtml"
      
    ViewBag.Title = "Roles";
    Layout = "~/Views/Shared/_eGateLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 127), Tuple.Create("\"", 177)
, Tuple.Create(Tuple.Create("", 133), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/Model/RoleModel.js")
, 133), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 197), Tuple.Create("\"", 259)
, Tuple.Create(Tuple.Create("", 203), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/ViewModel/RoleListViewModel.js")
, 203), false)
);

WriteLiteral("></script>\r\n\r\n");

});

WriteLiteral("\r\n");

DefineSection("ko_apply", () => {

WriteLiteral("\r\nvar viewModel = new eGateRoot.RoleListViewModel();\r\nko.applyBindingsWithValidat" +
"ion(viewModel, $(\"#Roles\")[0], { insertMessages: false, messagesOnModified: fals" +
"e, grouping: { deep: true }});\r\n");

});

WriteLiteral("\r\n<!-- BEGIN CONTENT -->\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n\t\t<h3");

WriteLiteral(" class=\"page-title\"");

WriteLiteral("><span");

WriteLiteral(" id=\"spnTitle\"");

WriteLiteral("></span></h3>\r\n\t\t<ul");

WriteLiteral(" class=\"page-breadcrumb breadcrumb\"");

WriteLiteral("></ul>\r\n\t</div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"Roles\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" data-bind=\"visible: viewMode() == \'List\', template: { name: \'Roles-template\' }\"");

WriteLiteral("></div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"portlet-body\"");

WriteLiteral(">\r\n\t\t<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"Roles-template\"");

WriteLiteral(">\r\n\t\t\t");

WriteLiteral("\r\n\r\n            <div id=\"tableheader\">\r\n\t\t\t\t<a class=\"button gbtngreen\" data-bind" +
"=\"click: $root.AddRole\"><i class=\"fa fa-plus\"></i>&nbsp;<strong>New Role</strong" +
"></a>\r\n\t\t\t</div>\r\n\t\t\t<div data-bind=\"kendoGrid: {\r\n\tdata: RolesList,\r\n\tgroupable" +
": false,\r\n\tsortable: true,\r\n\tscrollable: true,\r\n\tfilterable: {\r\n\t\textra: false, " +
"operators: {\r\n\t\t\tstring: {\r\n\t\t\t\tstartswith: \'Starts with\',\r\n\t\t\t\teq: \'Is equal to" +
"\',\r\n\t\t\t\tneq: \'Is not equal to\',\r\n\t\t\t\tcontains: \'Contains\',\r\n\t\t\t\tdoesnotcontain: " +
"\'Does not Contain\'\r\n\t\t\t},\r\n\t\t\tnumber: { eq: \'Is equal to\' }\r\n\t\t}\r\n\t},\r\n\trowTempl" +
"ate: \'rowTmpl\',\r\n\tuseKOTemplates: true,\r\n\tcolumns: [\r\n { title: \'Actions\', width" +
": 50, filterable: false },\r\n        { field: \'RoleCodeSort\', title: \'Role Code\'," +
" width: 70, filterable: true },\r\n        { field: \'RoleNameSort\', title: \'Role N" +
"ame\', width: 70, filterable: true },\r\n  { field: \'RecordStatusSort\', title: \'Sta" +
"tus\', width: 70, filterable: true },\r\n\r\n\t]\r\n}\">\r\n\t\t\t</div>\r\n\t\t\t<script id=\"rowTm" +
"pl\" type=\"text/html\">\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<td align=\"center\">\r\n\t\t\t\t\t\t<div class=\"now" +
"rap\">\r\n\t\t\t\t\t\t\t<a href=\"#\" title=\"View\" data-bind=\"click: $parent.ViewRole\"><i cl" +
"ass=\"fa fa-eye\"></i></a>\r\n\t\t\t\t\t\t\t<a href=\"#\" title=\"Edit\" data-bind=\"click: $par" +
"ent.EditRole\"><i class=\"fa fa-edit\t\"></i></a>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</td>\r\n\t\t\t\t\t<t" +
"d>\r\n\t\t\t\t\t\t<div class=\"nowrap\"><span data-bind=\"text: RoleCode\"></span></div>\r\n\t\t" +
"\t\t\t</td>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\t<div class=\"nowrap\"><span data-bind=\"text: RoleName\">" +
"</span></div>\r\n\t\t\t\t\t</td>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\t<div class=\"nowrap\"><span data-bind=" +
"\"text: RecordStatus\"></span></div>\r\n\t\t\t\t\t</td>\r\n\r\n\t\t\t\t</tr>\r\n\t\t\t</script>\r\n\t\t</s" +
"cript>\r\n\t</div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
