#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partner/Partner.cshtml")]
    public partial class _Views_Partner_Partner_cshtml : System.Web.Mvc.WebViewPage<PortKonnect.UserAccessManagement.Domain.DTOS.PrivilegeDTO>
    {
        public _Views_Partner_Partner_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Partner\Partner.cshtml"
  
    ViewBag.Title = "Partner";
    Layout = "~/Views/Shared/_eGateLayout.cshtml";
    

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("<script");

WriteAttribute("src", Tuple.Create(" src=\"", 189), Tuple.Create("\"", 238)
, Tuple.Create(Tuple.Create("", 195), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/CustomisedControls.js")
, 195), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 262), Tuple.Create("\"", 315)
, Tuple.Create(Tuple.Create("", 268), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/Model/PartnerModel.js")
, 268), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 339), Tuple.Create("\"", 400)
, Tuple.Create(Tuple.Create("", 345), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/ViewModel/PartnerViewModel.js")
, 345), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

DefineSection("ko_apply", () => {

WriteLiteral("\r\n    var viewModel = new eGateRoot.PartnerViewModel(\"");

            
            #line 15 "..\..\Views\Partner\Partner.cshtml"
                                               Write(ViewBag.PartnerId);

            
            #line default
            #line hidden
WriteLiteral("\",\"");

            
            #line 15 "..\..\Views\Partner\Partner.cshtml"
                                                                    Write(ViewBag.Path);

            
            #line default
            #line hidden
WriteLiteral("\");  \r\n  ko.applyBindingsWithValidation(viewModel, $(\"#Partner\")[0], { insertMess" +
"ages: false, messagesOnModified: false, grouping: { deep: true }});\r\n");

});

WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"page-title\"");

WriteLiteral("><span");

WriteLiteral(" id=\"spnTitle\"");

WriteLiteral("></span></h3>\r\n        <ul");

WriteLiteral(" class=\"page-breadcrumb breadcrumb\"");

WriteLiteral("></ul>\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"Partner\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" data-bind=\"visible: viewMode() == \'Form\', template: { name: \'Partner-template\' }" +
"\"");

WriteLiteral("></div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n\r\n<div");

WriteLiteral(" class=\"portlet-body\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"table-toolbar\"");

WriteLiteral(">\r\n\r\n        <script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"Partner-template\"");

WriteLiteral(@">

            <div class=""portlet portlet-body form"" data-bind=""loadingWhen: $root.viewModelHelper.isLoading"">
                <div class=""form-wizard"">
                    <div class=""form-body form-horizontal"" data-bind=""with: PartnerModel"">
						");

WriteLiteral(@"
                        <div class=""tab-pane active"" id=""tab1"">
                            <div class=""form-group"">
                                <div class=""row"">
                                    <div class=""col-md-11""></div>
                                    <div class=""col-md-1"" style=""display: none;"">
");

            
            #line 49 "..\..\Views\Partner\Partner.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Partner\Partner.cshtml"
                                         if (Model.HasPrivilege("eGatePartnerEdit")) //TODO: Need to implment Entity Functions as Enums
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"Edit\"");

WriteLiteral(" class=\"btn blue\"");

WriteLiteral(" data-bind=\"click: $root.EditPartner, visible: $root.IsEdit\"");

WriteLiteral(" />\r\n");

            
            #line 52 "..\..\Views\Partner\Partner.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </div>\r\n                                </div" +
">\r\n                                <fieldset>\r\n                                 " +
"   <legend>Partner Details</legend>\r\n                                    <div cl" +
"ass=\"row\">\r\n                                        <div class=\"col-md-6\">\r\n    " +
"                                        <div class=\"form-group\">\r\n              " +
"                                  <label class=\"control-label col-md-5\">Partner " +
"Code:<span class=\"required\">*</span></label>\r\n                                  " +
"              <div class=\"col-md-7\">\r\n\r\n                                        " +
"            <input type=\"text\" id=\"PartnerCode\" name=\"\" class=\"form-control\" dat" +
"a-bind=\"value: PartnerCode, event: { keypress: $root.validationHelper.ValidateAl" +
"phaNumeric }, enable: $root.EditMode, enable: $parent.PartnerCodeEnable,\" maxlen" +
"gth=\"25\">\r\n                                                    <span class=\"vali" +
"dationError\" data-bind=\"validationMessage: PartnerCode\"></span>\r\n\r\n             " +
"                                   </div>\r\n\r\n                                   " +
"         </div>\r\n                                        </div>\r\n               " +
"                         <div class=\"col-md-6\">\r\n                               " +
"             <div class=\"form-group\">\r\n                                         " +
"       <label class=\"control-label col-md-5\">Partner Type :<span class=\"required" +
"\">*</span></label>\r\n                                                <div class=\"" +
"col-md-7\">\r\n                                                    <input id=\"mulse" +
"lectPartnerType\"  data-bind=\"kendoMultiSelect: { dataTextField: \'PartnerTypeName" +
"\', dataValueField: \'PartnerTypeId\', data: $parent.PartnerTypes, enabled: $root.E" +
"ditMode, value: PartnerTypeArray }, event: { blur: $root.DupliacteValidation, ch" +
"ange: $root.validatepartnerType }\" />\r\n                                         " +
"           ");

WriteLiteral("\r\n                                                    <span class=\"validationErro" +
"r\" id=\"validationParterType\"></span>\r\n\r\n                                        " +
"        </div>\r\n                                            </div>\r\n            " +
"                            </div>\r\n                                    </div>\r\n" +
"                                    <br />\r\n                                    " +
"<br />\r\n                                    <br />\r\n                            " +
"        <br />\r\n                                    <div class=\"row\">\r\n         " +
"                               <div class=\"col-md-6\">\r\n                         " +
"                   <div class=\"form-group\">\r\n                                   " +
"             <label class=\"control-label col-md-5\">Partner Name :<span class=\"re" +
"quired\">*</span></label>\r\n                                                <div c" +
"lass=\"col-md-7\">\r\n                                                    <input typ" +
"e=\"text\" id=\"partnerName\" name=\"\" class=\"form-control\" data-bind=\"value: Partner" +
"Name, event: { keypress: $root.validationHelper.ValidateAlphabetsWithSpacesAndSp" +
"ecialChars_keypressEvent }, enable: $root.EditMode\" maxlength=\"50\">\r\n           " +
"                                         <span class=\"validationError\" data-bind" +
"=\"validationMessage: PartnerName\"></span>\r\n                                     " +
"           </div>\r\n                                            </div>\r\n         " +
"                               </div>\r\n                                        <" +
"div class=\"col-md-6\">\r\n                                            <div class=\"f" +
"orm-group\">\r\n                                                <label class=\"contr" +
"ol-label col-md-5\">Partner Port :<span class=\"required\">*</span></label>\r\n      " +
"                                          <div class=\"col-md-7\">\r\n              " +
"                                      <input id=\"mulselectPartnerPort\" data-bind" +
"=\"kendoMultiSelect: { dataTextField: \'PortName\', dataValueField: \'PortCode\', dat" +
"a: $parent.Ports, enabled: $parent.applicationDisabled, value: PartnerPortArray " +
"}\" />\r\n                                                    <span class=\"validati" +
"onError\" data-bind=\"validationMessage: PartnerPort\"></span>\r\n                   " +
"                             </div>\r\n                                           " +
" </div>\r\n                                        </div>\r\n                       " +
"             </div>\r\n                                    <div class=\"row\">\r\n    " +
"                                    <div class=\"col-md-6\">\r\n                    " +
"                        <div class=\"form-group\">\r\n                              " +
"                  <label class=\"control-label col-md-5\">Application :<span class" +
"=\"required\">*</span></label>\r\n                                                <d" +
"iv class=\"col-md-7\">\r\n                                                    <selec" +
"t id=\"ddlport\" name=\"\" class=\"form-control\" data-bind=\"options: $root.Applicatio" +
"ns, optionsText: \'ApplicationName\', optionsValue: \'ApplicationId\', enable: $root" +
".applicationDisabled, value: Application\"></select>\r\n                           " +
"                         <span class=\"validationError\" data-bind=\"validationMess" +
"age: Application\"></span>\r\n                                                    ");

WriteLiteral("\r\n\r\n                                                </div>\r\n                     " +
"                       </div>\r\n                                        </div>\r\n\r" +
"\n                                    </div>\r\n\r\n                                <" +
"/fieldset>\r\n                                <fieldset>\r\n                        " +
"            <legend>Partner Address</legend>\r\n                                  " +
"  <div class=\"row\">\r\n                                        <div class=\"col-md-" +
"6\">\r\n                                            <div class=\"form-group\">\r\n     " +
"                                           <label class=\"control-label col-md-5\"" +
">House Number:<span class=\"required\">*</span></label>\r\n                         " +
"                       <div class=\"col-md-7\" data-bind=\"with: PartnerAddress\">\r\n" +
"                                                    <div>\r\n                     " +
"                                   <input type=\"text\" id=\"houseNumber\" name=\"\" c" +
"lass=\"form-control\" data-bind=\"value: HouseNumber, enable: $root.EditMode, event" +
": { keypress: $root.validationHelper.ValidateAlphaNumericWithSpacesAndSpecialCha" +
"rsForHouseNo_keypressEvent }\" onchange=\"validateHouseNumber()\" maxlength=\"100\">\r" +
"\n                                                        <span class=\"validation" +
"Error\" id=\"validationHouseNumber\"></span>\r\n                                     " +
"               </div>\r\n                                                </div>\r\n\r" +
"\n                                            </div>\r\n                           " +
"             </div>\r\n                                        <div class=\"col-md-" +
"6\">\r\n                                            <div class=\"form-group\">\r\n     " +
"                                           <label class=\"control-label col-md-5\"" +
">Street Name:<span class=\"required\">*</span></label>\r\n                          " +
"                      <div class=\"col-md-7\" data-bind=\"with: PartnerAddress\">\r\n " +
"                                                  <input type=\"text\" id=\"streetN" +
"ame\" name=\"\" class=\"form-control\" data-bind=\"value: StreetName, enable: $root.Ed" +
"itMode, event: { keypress: $root.validationHelper.ValidateAlphaNumericWithSpaces" +
" }\" onchange=\"validateStreetName()\" maxlength=\"100\">\r\n                          " +
"                         <span class=\"validationError\" id=\"validationStreetName\"" +
"></span>\r\n                                                </div>\r\n              " +
"                              </div>\r\n                                        </" +
"div>\r\n                                    </div>\r\n                              " +
"     \r\n                                    <div class=\"row\">\r\n                  " +
"                      <div class=\"col-md-6\">\r\n                                  " +
"          <div class=\"form-group\">\r\n                                            " +
"    <label class=\"control-label col-md-5\">Area Name :<span class=\"required\">*</s" +
"pan></label>\r\n                                                <div class=\"col-md" +
"-7\" data-bind=\"with: PartnerAddress\">\r\n                                         " +
"           <div>\r\n                                                        <input" +
" type=\"text\" id=\"areaName\" name=\"\" class=\"form-control\" data-bind=\"value: AreaNa" +
"me, enable: $root.EditMode, event: { keypress: $root.validationHelper.ValidateAl" +
"phabetsWithSpaces_keypressEvent }\" onchange=\"validateareaName()\" maxlength=\"100\"" +
">\r\n                                                        <span class=\"validati" +
"onError\" id=\"validationAreaName\"></span>\r\n                                      " +
"              </div>\r\n                                                </div>\r\n  " +
"                                          </div>\r\n                              " +
"          </div>\r\n                                        <div class=\"col-md-6\">" +
"\r\n                                            <div class=\"form-group\">\r\n        " +
"                                        <label class=\"control-label col-md-5\">To" +
"wn Or City :<span class=\"required\">*</span></label>\r\n                           " +
"                     <div class=\"col-md-7\" data-bind=\"with: PartnerAddress\">\r\n  " +
"                                                  <div>\r\n                       " +
"                                 <input type=\"text\" id=\"townOrCity\" name=\"\" clas" +
"s=\"form-control\" data-bind=\"value: TownOrCity, enable: $root.EditMode, event: { " +
"keypress: $root.validationHelper.ValidateAlphabetsWithSpaces_keypressEvent }\" on" +
"change=\"validatetownOrCity()\" maxlength=\"50\">\r\n                                 " +
"                       <span class=\"validationError\" id=\"validationTownOrCity\"><" +
"/span>\r\n                                                    </div>\r\n            " +
"                                    </div>\r\n                                    " +
"        </div>\r\n                                        </div>\r\n                " +
"                    </div>\r\n                                    <div class=\"row\"" +
">\r\n                                        <div class=\"col-md-6\">\r\n             " +
"                               <div class=\"form-group\">\r\n                       " +
"                         <label class=\"control-label col-md-5\">Zip Code:<span cl" +
"ass=\"required\">*</span></label>\r\n                                               " +
" <div class=\"col-md-7\" data-bind=\"with: PartnerAddress\">\r\n                      " +
"                              <div>\r\n                                           " +
"             <input type=\"text\" id=\"zipCode\" name=\"\" class=\"form-control\" data-b" +
"ind=\"value: ZipCode, enable: $root.EditMode, event: { keypress: $root.validation" +
"Helper.ValidateNumeric }\" onchange=\"validatezipCode()\" maxlength=\"6\">\r\n         " +
"                                               <span class=\"validationError\" id=" +
"\"validationZipCode\"></span>\r\n                                                   " +
" </div>\r\n                                                </div>\r\n               " +
"                             </div>\r\n                                        </d" +
"iv>\r\n                                        <div class=\"col-md-6\">\r\n           " +
"                                 <div class=\"form-group\">\r\n                     " +
"                           <label class=\"control-label col-md-5\">Country :<span " +
"class=\"required\">*</span></label>\r\n                                             " +
"   <div class=\"col-md-7\" data-bind=\"with: PartnerAddress\">\r\n                    " +
"                                <div>\r\n                                         " +
"               <select id=\"ddlCountry\" name=\"\" class=\"form-control\" data-bind=\"o" +
"ptions: $root.Countries, optionsText: \'CountryName\', optionsCaption: \'Select...\'" +
", optionsValue: \'CountryCode\', value: Country, enable: $root.EditMode, event: { " +
"change: $root.SelectStates }\" onchange=\"validateCountry()\"></select>\r\n          " +
"                                              <span class=\"validationError\" id=\"" +
"validationCountry\"></span>\r\n                                                    " +
"</div>\r\n                                                </div>\r\n                " +
"                            </div>\r\n                                        </di" +
"v>\r\n\r\n                                    </div>\r\n                              " +
"      <div class=\"row\">\r\n                                        <div class=\"col" +
"-md-6\">\r\n                                            <div class=\"form-group\">\r\n " +
"                                               <label class=\"control-label col-m" +
"d-5\">State :<span class=\"required\">*</span></label>\r\n                           " +
"                     <div class=\"col-md-7\" data-bind=\"with: PartnerAddress\">\r\n  " +
"                                                  <div>\r\n                       " +
"                                 <select id=\"ddlState\" name=\"\" class=\"form-contr" +
"ol\" data-bind=\"options: $root.States, optionsText: \'StateName\', optionsCaption: " +
"\'Select...\', optionsValue: \'StateCode\', enable: $root.EditMode, value: State\" on" +
"change=\"validateState()\"></select>\r\n                                            " +
"            <span class=\"validationError\" id=\"validationState\"></span>\r\n        " +
"                                            </div>\r\n                            " +
"                    </div>\r\n                                            </div>\r\n" +
"                                        </div>\r\n                                " +
"        <div class=\"col-md-6  ie-validation moz-margin1\">\r\n                     " +
"                       <div class=\"form-group\">\r\n                               " +
"                 <label class=\"control-label col-md-5\">Contact Number :<span cla" +
"ss=\"required\">*</span></label>\r\n                                                " +
"<div class=\"col-md-7\" data-bind=\"with: PartnerAddress\">\r\n                       " +
"                             <div>\r\n                                            " +
"            <input type=\"text\" id=\"contactNumber\" name=\"\" class=\"form-control\" d" +
"ata-bind=\"value: ContactNumber, enable: $root.EditMode, event: { keypress: $root" +
".validationHelper.ValidateNumeric }\" onchange=\"validateContactNumber()\" maxlengt" +
"h=\"15\">\r\n                                                        <span class=\"va" +
"lidationError\" id=\"validationContactNumber\"></span>\r\n                           " +
"                         </div>\r\n                                               " +
" </div>\r\n                                            </div>\r\n                   " +
"                     </div>\r\n\r\n\r\n                                    </div>\r\n\r\n " +
"                                   <div class=\"row\">\r\n                          " +
"              <div class=\"col-md-6\">\r\n                                          " +
"  <div class=\"form-group\">\r\n                                                <lab" +
"el class=\"control-label col-md-5\">Email Id :<span class=\"required\">*</span></lab" +
"el>\r\n                                                <div class=\"col-md-7\" data-" +
"bind=\"with: PartnerAddress\">\r\n                                                  " +
"  <div>\r\n                                                        <input type=\"te" +
"xt\" id=\"emailId\" name=\"\" class=\"form-control\" data-bind=\"value: EmailId, enable:" +
" $root.EditMode, event: { keypress: $root.validationHelper.ValidateAlphanumericE" +
"mail }\" onchange=\"validateEmailId()\" maxlength=\"50\">\r\n                          " +
"                              <span class=\"validationError\" id=\"validationEmailI" +
"d\"></span>\r\n                                                    </div>\r\n        " +
"                                        </div>\r\n                                " +
"            </div>\r\n                                        </div>\r\n\r\n          " +
"                              <div class=\"col-md-6\">\r\n                          " +
"                  <div class=\"form-group\">\r\n                                    " +
"            <label class=\"control-label col-md-5\">Web Site :<span class=\"require" +
"d\">&nbsp;&nbsp;</span></label>\r\n                                                " +
"<div class=\"col-md-7\" data-bind=\"with: PartnerAddress\">\r\n                       " +
"                             <div>\r\n                                            " +
"            <input type=\"text\" id=\"webSite\" name=\"\" class=\"form-control\" data-bi" +
"nd=\"value: WebSite, enable: $root.EditMode, event: { keypress: $root.validationH" +
"elper.ValidateAlphabetsWithSpacesAndSpecialCharsForWebSite_keypressEvent }\" maxl" +
"ength=\"50\">\r\n                                                        <span class" +
"=\"validationError\" id=\"validationWebSite\"></span>\r\n                             " +
"                       </div>\r\n                                                <" +
"/div>\r\n                                            </div>\r\n                     " +
"                   </div>\r\n\r\n\r\n\r\n                                    </div>\r\n   " +
"                                 <div class=\"row\">\r\n                            " +
"            ");

WriteLiteral("\r\n\r\n                                        <div class=\"row\">\r\n                  " +
"                          <div class=\"col-md-6\">\r\n                              " +
"                  <div class=\"row form-group\">\r\n                                " +
"                    <label class=\"control-label col-md-5\">Logo :<span class=\"req" +
"uired\">&nbsp;&nbsp;</span></label>\r\n                                            " +
"        <div class=\"col-md-7\" style=\"border:1px solid #ccc; border-radius:5px;\">" +
"\r\n                                                        <table style=\"width:10" +
"0%; height:20px;\" >\r\n                                                           " +
" <tr>\r\n                                                                <td>\r\n   " +
"                                                                 <img id=\"sigIma" +
"ge\" src=\"#\" height=\"60\" data-bind=\"visible: (PartnerAddress().LogoPath() != \'\' &" +
"& PartnerAddress().LogoPath() != null)\">\r\n                                      " +
"                              <span class=\"validationError\" id=\"validationLogo\">" +
"</span>\r\n                                                                </td>\r\n" +
"                                                            </tr>\r\n             " +
"                                           </table>\r\n                           " +
"                         </div>\r\n                                               " +
" </div>\r\n                                                <div class=\"row\">\r\n    " +
"                                                <label class=\"control-label col-" +
"md-5\"></label>\r\n                                                    <div class=\"" +
"col-md-6\">\r\n                                                        <table>\r\n   " +
"                                                         <tbody data-bind=\"with:" +
" PartnerAddress\">\r\n                                                             " +
"   <tr>\r\n                                                                    <td" +
" data-bind=\"visible: (LogoPath() != \'\' && LogoPath() != null)\">\r\n               " +
"                                                         <a href=\"\" id=\"fileName" +
"Link\" data-bind=\"attr: { href:application.viewbag.appSettings.uamapiUrl+\'/FileUp" +
"loads/Logo/\' + LogoPath() }\" target=\"_blank\"><span data-bind=\"\ttext: LogoFileNam" +
"e\"></span></a>\r\n                                                                " +
"        ");

WriteLiteral("\r\n                                                                    </td>\r\n    " +
"                                                            </tr>\r\n             " +
"                                                   \r\n                           " +
"                                 </tbody>\r\n                                     " +
"                   </table>\r\n                                                   " +
" </div>\r\n                                                </div>\r\n               " +
"                             \r\n                                            <div " +
"class=\"row\">\r\n                                                    <label class=\"" +
"control-label col-md-5\"></label>\r\n                                              " +
"  <div class=\"col-md-7\">\r\n                                            <div class" +
"=\"fileupload-buttonbar\">\r\n                                                <div c" +
"lass=\"form-group\">\r\n                                                    <div cla" +
"ss=\"col-md-6\" data-bind=\"visible: $parent.IsUpload\">\r\n                          " +
"                              <span class=\"btn btn-xs green fileinput-button\">\r\n" +
"                                                            <i class=\"fa fa-plus" +
"\"></i>\r\n                                                            <span data-b" +
"ind=\"visible: $parent.IsUpload\">Browse\r\n                                        " +
"                    </span>\r\n                                                   " +
"         <input type=\"file\" class=\"upload\" name=\"files[]\" id=\"fileToUpload\" mult" +
"iple />\r\n                                                        </span>\r\n      " +
"                                                  <button type=\"button\" id=\"Capt" +
"urePicture\" data-icon=\"upload\" data-role=\"button\" data-bind=\"click: $root.upload" +
"File, visible: $root.IsUpload\" class=\"btn btn-xs blue start\">\r\n                 " +
"                                           <i class=\"fa fa-upload\"></i>\r\n       " +
"                                                     <span>Upload\r\n             " +
"                                               </span>\r\n\r\n                      " +
"                                  </button>\r\n                                   " +
"                 </div>\r\n                                                </div>\r" +
"\n                                            </div></div></div></div>\r\n         " +
"                               </div>\r\n                                </fieldse" +
"t>\r\n\r\n                                <div class=\"btns-group form-actions fluid\"" +
">\r\n                                    <input type=\"button\" value=\"Save\" class=\"" +
"btn green\" data-bind=\"click: $root.SaveScreen, visible: $root.IsSave\" />\r\n      " +
"                              <input type=\"button\" value=\"Update\" class=\"btn gre" +
"en\" data-bind=\"click: $root.UpdateScreen, visible: $root.IsUpdate\" />\r\n         " +
"                           <button type=\"submit\" class=\"btn blue\" data-bind=\"cli" +
"ck: $root.ResetScreen, visible: $root.IsReset\">Reset</button>\r\n\t\t\t\t\t\t\t\t\t<button " +
"type=\"submit\" class=\"btn default button-previous\" data-bind=\"click: $root.ExitSc" +
"reen\"><i class=\"m-icon-swapleft\"></i> Back</button>\r\n                           " +
"     </div>\r\n                            </div>\r\n                        </div>\r" +
"\n\r\n                    </div>\r\n\r\n                    ");

WriteLiteral("\r\n\r\n                </div>\r\n            </div>\r\n\r\n        </script>\r\n    </div>\r\n" +
"</div>\r\n");

        }
    }
}
#pragma warning restore 1591
