#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Partner/Partners.cshtml")]
    public partial class _Views_Partner_Partners_cshtml : System.Web.Mvc.WebViewPage<PortKonnect.UserAccessManagement.Domain.DTOS.PrivilegeDTO>
    {
        public _Views_Partner_Partners_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Partner\Partners.cshtml"
      
    ViewBag.Title = "Partners";
    Layout = "~/Views/Shared/_eGateLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 196), Tuple.Create("\"", 249)
, Tuple.Create(Tuple.Create("", 202), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/Model/PartnerModel.js")
, 202), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 269), Tuple.Create("\"", 334)
, Tuple.Create(Tuple.Create("", 275), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/ViewModel/PartnerListViewModel.js")
, 275), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

DefineSection("ko_apply", () => {

WriteLiteral("\r\nvar viewModel = new eGateRoot.PartnerListViewModel();\r\nko.applyBindingsWithVali" +
"dation(viewModel, $(\"#Partners\")[0], { insertMessages: false, messagesOnModified" +
": false, grouping: { deep: true }});\r\n");

});

WriteLiteral("\r\n<!-- BEGIN CONTENT -->\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n\t\t<h3");

WriteLiteral(" class=\"page-title\"");

WriteLiteral("><span");

WriteLiteral(" id=\"spnTitle\"");

WriteLiteral("></span></h3>\r\n\t\t<ul");

WriteLiteral(" class=\"page-breadcrumb breadcrumb\"");

WriteLiteral("></ul>\r\n\t</div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"Partners\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" data-bind=\"visible: viewMode() == \'List\', template: { name: \'Partners-template\' " +
"}\"");

WriteLiteral("></div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"portlet-body\"");

WriteLiteral(">\r\n\r\n\t\t<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"Partners-template\"");

WriteLiteral(">\r\n\r\n\t\t\t<div class=\"table-toolbar\">\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<div class=\"portlet box advb" +
"g\">\r\n\t\t\t\t\t\t<div class=\"portlet-title\">\r\n\t\t\t\t\t\t\t<div class=\"caption\">\r\n\t\t\t\t\t\t\t\t<i" +
" class=\"fa fa-search\" aria-hidden=\"true\"></i>Advance Search\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t" +
"\t\t\t<div class=\"tools\">\r\n\t\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"expand\"></a>\r\n\t\t\t\t" +
"\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div class=\"portlet-body\" data-bind=\"with: Partne" +
"rGridModel\" style=\"display:none;\">\r\n\t\t\t\t\t\t\t<div class=\"form-wizard form-horizont" +
"al\">\r\n\t\t\t\t\t\t\t\t<div class=\"form-body\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t\t\t\t\t<di" +
"v class=\"col-md-4\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<label cla" +
"ss=\"control-label col-md-4\">Partner Name:</label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-m" +
"d-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"SearchPartnerName\" class=\"form-contro" +
"l\" data-bind=\"value: PartnerName, event: { keypress: $root.validationHelper.Vali" +
"dateAlphabetsWithSpacesAndSpecialChars_keypressEvent }\" maxlength=\"50\">\r\n\t\t\t\t\t\t\t" +
"\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4" +
"\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label" +
" col-md-4\">Partner Type:</label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n\t\t\t\t\t\t\t\t\t\t" +
"\t\t\t<select id=\"ddlPartnerType\" name=\"\" class=\"form-control\" data-bind=\"options: " +
"$root.PartnerTypes, optionsText: \'PartnerTypeName\', optionsCaption: \'Select...\'," +
" optionsValue: \'PartnerTypeId\', value: PartnerType\"></select>\r\n\r\n\r\n\t\t\t\t\t\t\t\t\t\t\t\t<" +
"/div>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t" +
"\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label col-m" +
"d-4\">Email Id:</label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<input " +
"type=\"text\" id=\"SearchEmailId\" class=\"form-control\" data-bind=\"value: EmailId, e" +
"vent: { keypress: $root.validationHelper.ValidateAlphanumericEmail }\" maxlength=" +
"\"50\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\r" +
"\n\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div" +
" class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label col-md-4\">Contact " +
"Number:</label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"t" +
"ext\" id=\"SearchContactNumber\" class=\"form-control\" data-bind=\"value: ContactNumb" +
"er\" maxlength=\"50\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t" +
"\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t\t" +
"\t<label class=\"control-label col-md-4\"></label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-" +
"6\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div cla" +
"ss=\"col-md-4\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group \">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"" +
"control-label col-md-4\"></label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n\r\n\t\t\t\t\t\t\t\t" +
"\t\t\t\t\t<button type=\"submit\" class=\"btn btn-xs green\" data-bind=\"click: $root.Filt" +
"erpartner\">Search</button>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-xs" +
" blue\" data-bind=\"click: $root.ResetFilters\">Reset</button>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</div>\r" +
"\n\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\r\n\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t" +
"\t\t\t\t</div>\r\n\r\n\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\r\n\t\t\t\t<div id=\"tableheade" +
"r\">\r\n");

            
            #line 123 "..\..\Views\Partner\Partners.cshtml"
					
            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\Partner\Partners.cshtml"
                     if (Model.HasPrivilege("eGatePartnerAdd")) //TODO: Need to implment Entity Functions as Enums
                    {


            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteLiteral(" class=\"button gbtngreen\"");

WriteLiteral(" data-bind=\"click: $root.AddPartner \"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-plus\"");

WriteLiteral("></i>&nbsp;<strong>New Partner</strong></a>\r\n");

            
            #line 127 "..\..\Views\Partner\Partners.cshtml"
					}

            
            #line default
            #line hidden
WriteLiteral(@"
				</div>
				<div id=""Grid"" data-bind=""kendoGrid: {
	data: PartnerList,
	groupable: false,
	sortable: true,
	scrollable: true,
	filterable: {
		extra: false, operators: {
			string: {
				startswith: 'Starts with',
				eq: 'Is equal to',
				neq: 'Is not equal to',
				contains: 'Contains',
				doesnotcontain: 'Does not Contain'
			},
			number: { eq: 'Is equal to' }
		}
	},
	rowTemplate: 'rowTmpl',
	useKOTemplates: true,
	columns: [
{ title: 'Actions', width: 30, filterable: false },
        { field: 'PartnerCodeSort', title: 'Partner Code', width: 70, filterable: true },
        { field: 'PartnerNameSort', title: 'Partner Name', width: 70, filterable: true },
  { field: 'PartnerTypeSort', title: 'Partner Type', width: 100, filterable: true },
        { field: 'EmailSort', title: 'Partner Email', width: 70, filterable: true },
  { field: 'ContactNumberSort', title: 'Contact Number', width: 70, filterable: true },
 { field: 'SubscribedPortSort', title: 'Partner Port', width: 50, filterable: true }

	]
}"">
				</div>
				<script id=""rowTmpl"" type=""text/html"">
					<tr>

						<td align=""center"">
							<div class=""nowrap"">
");

            
            #line 166 "..\..\Views\Partner\Partners.cshtml"
								
            
            #line default
            #line hidden
            
            #line 166 "..\..\Views\Partner\Partners.cshtml"
                                 if (Model.HasPrivilege("eGatePartnerView")) //TODO: Need to implment Entity Functions as Enums
                                {

            
            #line default
            #line hidden
WriteLiteral("                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"View\"");

WriteLiteral(" data-bind=\"click: $parent.ViewPartner\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-eye\"");

WriteLiteral("></i></a>\r\n");

            
            #line 169 "..\..\Views\Partner\Partners.cshtml"


            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t<a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Edit\"");

WriteLiteral(" data-bind=\"click: $parent.EditPartner\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-edit\"");

WriteLiteral("></i></a>\r\n");

            
            #line 171 "..\..\Views\Partner\Partners.cshtml"

								}

            
            #line default
            #line hidden
WriteLiteral(@"							</div>
						</td>
						<td>
							<div class=""nowrap""><span data-bind=""text: PartnerCode, attr: { title: PartnerCode }""></span></div>
						</td>
						<td>
							<div class=""nowrap""><span data-bind=""text: PartnerName, attr: { title: PartnerName }""></span></div>
						</td>
						<td>
							<div class=""nowrap""><span data-bind=""text: PartnerTypeArrays, attr: { title: PartnerTypeArrays }""></span></div>
						</td>
						<td style=""word-wrap:break-word;"">
							<div class=""nowrap""><span data-bind=""text: EmailId, attr: { title: EmailId }""></span></div>
						</td>
						<td>
							<div class=""nowrap""><span data-bind=""text: ContactNumber, attr: { title: ContactNumber }""></span></div>
						</td>

						<td>
							<div class=""nowrap""><span data-bind=""text: SubscribedPort, attr: { title: SubscribedPort }""></span></div>
						</td>


					</tr>
				</script>

			</div>
		</script>
	</div>

</div>



");

        }
    }
}
#pragma warning restore 1591
