#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PartnerRegistration/PartnerRegistrationView.cshtml")]
    public partial class _Views_PartnerRegistration_PartnerRegistrationView_cshtml : System.Web.Mvc.WebViewPage<PortKonnect.UserAccessManagement.Domain.DTOS.PrivilegeDTO>
    {
        public _Views_PartnerRegistration_PartnerRegistrationView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\PartnerRegistration\PartnerRegistrationView.cshtml"
      
   Layout = "~/Views/Shared/_eGateLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 158), Tuple.Create("\"", 227)
, Tuple.Create(Tuple.Create("", 164), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/Model/ViewPartnerRegistrationModel.js")
, 164), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 247), Tuple.Create("\"", 324)
, Tuple.Create(Tuple.Create("", 253), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/ViewModel/PartnerRegistrationViewViewModel.js")
, 253), false)
);

WriteLiteral("></script>\r\n\r\n");

});

DefineSection("ko_apply", () => {

WriteLiteral("\r\nvar viewModel = new eGateRoot.PartnerRegistrationViewViewModel(\'");

            
            #line 14 "..\..\Views\PartnerRegistration\PartnerRegistrationView.cshtml"
                                                           Write(ViewBag.RequisitionNo);

            
            #line default
            #line hidden
WriteLiteral("\',\'");

            
            #line 14 "..\..\Views\PartnerRegistration\PartnerRegistrationView.cshtml"
                                                                                    Write(ViewBag.FormMode);

            
            #line default
            #line hidden
WriteLiteral("\');\r\nko.applyBindingsWithValidation(viewModel, $(\"#KYCForm\")[0], { insertMessages" +
": false, messagesOnModified: false, grouping: { deep: true }});\r\n");

});

WriteLiteral(@"
<style>
    .k-upload-status .k-upload-status-total {
        visibility: hidden;
        display: none;
    }

    .k-icon .k-i-tick {
        visibility: hidden;
        display: none;
    }

    .k-upload-status .k-upload-status-total {
        visibility: hidden;
        display: none;
    }

    .k-upload-button > span {
        padding: 8px !important;
    }

    .k-dropzone strong {
        display: none;
    }

    .k-upload-empty > validationError {
        position: relative !important;
    }

    .k-upload-status {
        display: none;
    }

    .k-widget {
        border-color: #F1F6FA;
    }
    .modal-dialog {width: 500px !important;}
      .clipped {
      overflow: hidden;
      white-space: nowrap;
      text-overflow: ellipsis;
    }
      .gridhead {margin-bottom:0px !important;}
</style>


<div");

WriteLiteral(" id=\"KYCForm\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" data-bind=\"visible: viewMode() == \'Form\', template: { name: \'Form-template\' }\"");

WriteLiteral("></div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n\r\n<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"Form-template\"");

WriteLiteral(">\r\n<div class=\"row\">\r\n    <div class=\"col-md-12\">\r\n        <h3 class=\"page-title\"" +
"><span id=\"spnTitle\" data-bind=\"text: \'");

            
            #line 71 "..\..\Views\PartnerRegistration\PartnerRegistrationView.cshtml"
                                                                Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("\'\"></span></h3>\r\n        <ul class=\"page-breadcrumb breadcrumb\"></ul>\r\n    </div>" +
"\r\n</div>\r\n<div class=\"portlet-body\">\r\n<div class=\"table-toolbar\">\r\n\r\n<div class=" +
"\"portlet portlet-body form\" data-bind=\"loadingWhen: $root.viewModelHelper.isLoad" +
"ing\">\r\n<div class=\"form-wizard\">\r\n<div class=\"form-body form-horizontal\">\r\n<div " +
"class=\"form-group\" data-bind=\"with: ViewPartnerRegistrationModel\">\r\n<div class=\"" +
"row\">\r\n    <div class=\"col-md-6\"><h4 align=\"right\"> Partner Registration : </h4>" +
"\r\n    </div>\r\n    <div class=\"col-md-6\">\r\n        <h4 > &nbsp;<span data-bind=\"t" +
"ext: RequisitionNo\"></span></h4>\r\n    </div>\r\n</div>\r\n\r\n<fieldset>\r\n    <legend>" +
"Partner Selection</legend>\r\n    <div class=\"row\">\r\n        <div class=\"\">\r\n     " +
"       <div class=\"form-group\">\r\n                <label class=\"control-label col" +
"-md-2\">Partner Selection:</label>\r\n                <div class=\"col-md-5\">\r\n     " +
"               <div class=\"radio-list\">\r\n                        <input type=\"ra" +
"dio\" id=\"partVOA\" name=\"partnerselection\" value=\"VesselOperatingAgent\" data-bind" +
"=\"checked: PartnerType, event: { click: $root.GetDocTypes }, enable: false\">\r\n  " +
"                      <label class=\"radio-inline\">VOA</label>&nbsp;&nbsp;&nbsp;&" +
"nbsp;\r\n                        <input type=\"radio\" id=\"partCOA\" name=\"partnersel" +
"ection\" value=\"ContainerOperatorAgent\" data-bind=\"checked: PartnerType, event: {" +
" click: $root.GetDocTypes }, enable: false\">\r\n                        <label cla" +
"ss=\"radio-inline\">COA</label>&nbsp;&nbsp;&nbsp;&nbsp;\r\n                        <" +
"input type=\"radio\" id=\"partCHA\" name=\"partnerselection\" value=\"CustomHouseAgent\"" +
" data-bind=\"checked: PartnerType, event: { click: $root.GetDocTypes }, enable: f" +
"alse\">\r\n                        <label class=\"radio-inline\">CHA / FF</label>&nbs" +
"p;&nbsp;&nbsp;&nbsp;\r\n                        <input type=\"radio\" id=\"partCFS\" n" +
"ame=\"partnerselection\" value=\"ContainerFreightStation\" data-bind=\"checked: Partn" +
"erType, event: { click: $root.GetDocTypes }, enable: false\">\r\n                  " +
"      <label class=\"radio-inline\">CFS</label>&nbsp;&nbsp;&nbsp;&nbsp;\r\n         " +
"               <input type=\"radio\" id=\"partM&R\" name=\"partnerselection\" value=\"M" +
"andR\" data-bind=\"checked: PartnerType, event: { click: $root.GetDocTypes }, enab" +
"le: false\">\r\n                        <label class=\"radio-inline\">M&R</label>\r\n  " +
"                  </div>\r\n                </div>\r\n            </div>\r\n        </" +
"div>\r\n    </div>\r\n</fieldset>\r\n\r\n\r\n<fieldset>\r\n<legend>Establishment Details</le" +
"gend>\r\n<div class=\"row\">\r\n    <div class=\"col-md-6\">\r\n        <div class=\"form-g" +
"roup\">\r\n            <label class=\"control-label col-md-6\">Name:<span class=\"requ" +
"ired\">*</span></label>\r\n            <div class=\"col-md-6\">\r\n                <div" +
">\r\n                    <input type=\"text\" id=\"partnerName\" name=\"\" class=\"form-c" +
"ontrol clipped\" data-bind=\"value: PartnerName, event: { keypress: $root.validati" +
"onHelper.ValidateAlphabetsWithSpacesAndSpecialChars_keypressEvent, change: $root" +
".CheckUniquePartnerName }, enable: $root.Isview, attr: { title: PartnerName }\" m" +
"axlength=\"50\">\r\n                    <span class=\"validationError\" data-bind=\"val" +
"idationMessage: PartnerName\"></span>\r\n                </div>\r\n            </div>" +
"\r\n\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"col-md-6\">\r\n        <div class" +
"=\"form-group\">\r\n            <label class=\"control-label col-md-6\">Corporate Iden" +
"tification Number (CIN) (in case of company / LLP):<span class=\"required\">*</spa" +
"n></label>\r\n            <div class=\"col-md-6\">\r\n                <input type=\"tex" +
"t\" id=\"txtCIN\" name=\"\" style=\"text-transform: uppercase\" class=\"form-control\" ma" +
"xlength=\"21\" data-bind=\"value: CIN, event: { keypress: $root.validationHelper.Va" +
"lidateAlphaNumeric, change: $root.CheckUniqueCIN }, enable: $root.Isview\">\r\n\r\n  " +
"              <span class=\"validationError\" id=\"validationCIN\"></span>\r\n        " +
"    </div>\r\n        </div>\r\n    </div>\r\n\r\n</div>\r\n<div class=\"row\">\r\n    <div cl" +
"ass=\"col-md-6\">\r\n        <div class=\"form-group\">\r\n            <label class=\"con" +
"trol-label col-md-6\">Year of Incorporation:<span class=\"required\">*</span></labe" +
"l>\r\n            <div class=\"col-md-6\">\r\n\r\n                <select id=\"txtYear\" n" +
"ame=\"\" class=\"form-control\" data-bind=\"options: $root.YearsList, optionsCaption:" +
" \'Select...\', value: Year,enable: $root.Isview\"></select>\r\n                <span" +
" class=\"validationError\" data-bind=\"validationMessage: Year\"></span>\r\n          " +
"  </div>\r\n        </div>\r\n    </div>\r\n    <div class=\"col-md-6\">\r\n        <div c" +
"lass=\"form-group\">\r\n            <label class=\"control-label col-md-6\">Permanent " +
"Account Number (PAN):<span class=\"required\">*</span></label>\r\n            <div c" +
"lass=\"col-md-6\">\r\n                <div>\r\n                    <input type=\"text\" " +
"style=\"text-transform: uppercase\" id=\"txtPAN\" name=\"\" class=\"form-control\" maxle" +
"ngth=\"10\" data-bind=\"value: PAN, event: { keypress: $root.validationHelper.Valid" +
"ateAlphaNumeric, change: $root.CheckUniquePAN }, enable: $root.Isview\" onchange=" +
"\" validatePAN() \">\r\n                    <span class=\"validationError\" data-bind=" +
"\"validationMessage: PAN\"></span>\r\n                </div>\r\n            </div>\r\n  " +
"      </div>\r\n    </div>\r\n</div>\r\n<div class=\"row\">\r\n    <div class=\"col-md-6\">\r" +
"\n        <div class=\"form-group\">\r\n            <label class=\"control-label col-m" +
"d-6\">Address Line 1:<span class=\"required\">*</span></label>\r\n            <div cl" +
"ass=\"col-md-6\" data-bind=\"with: PartnerRegistrationAddress\">\r\n                <d" +
"iv>\r\n                    <input type=\"text\" id=\"houseNumber\" name=\"\" class=\"form" +
"-control clipped\" data-bind=\"value: HouseNumber, event: { keypress: $root.valida" +
"tionHelper.ValidateAlphaNumericWithSpacesAndSpecialCharsForHouseNo_keypressEvent" +
" }, enable: $root.Isview, attr: { title: HouseNumber }\" onchange=\" validateHouse" +
"Number() \" maxlength=\"100\">\r\n                    <span class=\"validationError\" i" +
"d=\"validationHouseNumber\"></span>\r\n                </div>\r\n            </div>\r\n\r" +
"\n        </div>\r\n    </div>\r\n\r\n    <div class=\"col-md-6\">\r\n        <div class=\"f" +
"orm-group\">\r\n            <label class=\"control-label col-md-6\">Tax Deduction Acc" +
"ount Number (TAN):<span class=\"required\" data-bind=\"visible: PartnerType() != \'C" +
"ustomHouseAgent\'\">*</span></label>\r\n            <div class=\"col-md-6\">\r\n        " +
"        <div>\r\n                    <input type=\"text\" id=\"txtTAN\" style=\"text-tr" +
"ansform: uppercase\" name=\"\" class=\"form-control\" maxlength=\"10\" data-bind=\"value" +
": TAN, event: { keypress: $root.validationHelper.ValidateAlphaNumeric, change: $" +
"root.CheckUniqueTAN }, enable: $root.Isview\">\r\n                    <span class=\"" +
"validationError\" data-bind=\"validationMessage: TAN\"></span>\r\n                </d" +
"iv>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<div class=\"row\">" +
"\r\n\r\n    <div class=\"col-md-6\">\r\n        <div class=\"form-group\">\r\n            <l" +
"abel class=\"control-label col-md-6\">Address Line 2:&nbsp;&nbsp;</label>\r\n       " +
"     <div class=\"col-md-6\" data-bind=\"with: PartnerRegistrationAddress\">\r\n      " +
"          <input type=\"text\" id=\"streetName\" name=\"\" class=\"form-control clipped" +
"\" onchange=\" validateStreetName() \" maxlength=\"100\" data-bind=\"value: StreetName" +
", enable: $root.Isview, attr: { title: StreetName }\">\r\n                <span cla" +
"ss=\"validationError\" id=\"validationStreetName\"></span>\r\n            </div>\r\n    " +
"    </div>\r\n    </div>\r\n\r\n    <div class=\"col-md-6\">\r\n        <div class=\"form-g" +
"roup\">\r\n            <label class=\"control-label col-md-6\">Establishment Regn. No" +
".:<span class=\"required\">*</span></label>\r\n            <div class=\"col-md-6\">\r\n " +
"               <div>\r\n                    <input type=\"text\" id=\"registrationNo\"" +
" name=\"\" class=\"form-control\" maxlength=\"10\" data-bind=\"value: RegistrationNo, e" +
"vent: { keypress: $root.validationHelper.ValidateAlphaNumeric, change: $root.Che" +
"ckUniqueRegistrationNo }, enable: $root.Isview\">\r\n                    <span clas" +
"s=\"validationError\" data-bind=\"validationMessage: RegistrationNo\"></span>\r\n     " +
"           </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<di" +
"v class=\"row\">\r\n    <div class=\"col-md-6\">\r\n        <div class=\"form-group\">\r\n  " +
"          <label class=\"control-label col-md-6\">Address Line 3:&nbsp;&nbsp;</lab" +
"el>\r\n            <div class=\"col-md-6\" data-bind=\"with: PartnerRegistrationAddre" +
"ss\">\r\n                <div>\r\n                    <input type=\"text\" id=\"areaName" +
"\" name=\"\" class=\"form-control clipped\" maxlength=\"100\" data-bind=\"value: AreaNam" +
"e, enable: $root.Isview, attr: { title: AreaName }\" onchange=\" validateareaName(" +
") \">\r\n                    <span class=\"validationError\" id=\"validationAreaName\">" +
"</span>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r" +
"\n\r\n    <div class=\"col-md-6\">\r\n        <div class=\"form-group\">\r\n            <la" +
"bel class=\"control-label col-md-6\">Registration Place:<span class=\"required\">*</" +
"span></label>\r\n            <div class=\"col-md-6\">\r\n                <div>\r\n      " +
"              <input type=\"text\" id=\"txtPlace\" name=\"\" class=\"form-control clipp" +
"ed\" maxlength=\"50\" data-bind=\"value: Place, event: { keypress: $root.validationH" +
"elper.ValidateAlphaNumericWithSpaces_keypressEvent }, enable: $root.Isview, attr" +
": { title: Place }\">\r\n\r\n                    <span class=\"validationError\" data-b" +
"ind=\"validationMessage: Place\"></span>\r\n                </div>\r\n            </di" +
"v>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<div class=\"row\">\r\n    <div class=\"col" +
"-md-6\">\r\n        <div class=\"form-group\">\r\n            <label class=\"control-lab" +
"el col-md-6\">Town / City :<span class=\"required\">*</span></label>\r\n            <" +
"div class=\"col-md-6\" data-bind=\"with: PartnerRegistrationAddress\">\r\n            " +
"    <div>\r\n                    <input type=\"text\" id=\"townOrCity\" name=\"\" class=" +
"\"form-control\" maxlength=\"50\" data-bind=\"value: TownOrCity, enable: $root.Isview" +
"\" onchange=\" validatetownOrCity() \">\r\n                    <span class=\"validatio" +
"nError\" id=\"validationTownOrCity\"></span>\r\n                </div>\r\n            <" +
"/div>\r\n        </div>\r\n    </div>\r\n    <div class=\"col-md-6\">\r\n        <div clas" +
"s=\"form-group\">\r\n            <label class=\"control-label col-md-6\">GST / Service" +
" Tax / VAT Regn. No.:<span class=\"required\">*</span></label>\r\n            <div c" +
"lass=\"col-md-6\">\r\n                <div>\r\n                    <input type=\"text\" " +
"id=\"txtVAT\" name=\"\" style=\"text-transform: uppercase\" class=\"form-control\" maxle" +
"ngth=\"15\" data-bind=\"value: VAT, event: { keypress: $root.validationHelper.Valid" +
"ateAlphaNumeric, change: $root.CheckUniqueVAT }, enable: $root.Isview\">\r\n       " +
"             <span class=\"validationError\" data-bind=\"validationMessage: VAT\"></" +
"span>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n<" +
"/div>\r\n\r\n<div class=\"row\">\r\n    <div class=\"col-md-6\">\r\n        <div class=\"form" +
"-group\">\r\n            <label class=\"control-label col-md-6\">Country :<span class" +
"=\"required\">*</span></label>\r\n            <div class=\"col-md-6\" data-bind=\"with:" +
" PartnerRegistrationAddress\">\r\n                <div>\r\n                    <selec" +
"t id=\"ddlCountry\" name=\"\" class=\"form-control\" data-bind=\"options: $root.Countri" +
"es, optionsText: \'CountryName\', optionsCaption: \'Select...\', optionsValue: \'Coun" +
"tryCode\', value: Country, event: { change: $root.SelectStates }, enable: $root.I" +
"sview\" onchange=\" validateCountry() \"></select>\r\n                    <span class" +
"=\"validationError\" id=\"validationCountry\"></span>\r\n                </div>\r\n     " +
"       </div>\r\n        </div>\r\n    </div>\r\n    <div class=\"col-md-6\">\r\n        <" +
"div class=\"form-group\">\r\n            <label class=\"control-label col-md-6\">Email" +
" Id:<span class=\"required\">*</span></label>\r\n            <div class=\"col-md-6\" d" +
"ata-bind=\"with: PartnerRegistrationAddress\">\r\n                <div>\r\n           " +
"         <input type=\"text\" id=\"PartnerEmailId\" name=\"\" class=\"form-control clip" +
"ped\" data-bind=\"value: Email, event: { keypress: $root.validationHelper.Validate" +
"AlphanumericEmail }, enable: $root.Isview, attr: { title: Email }\" maxlength=\"20" +
"0\" onchange=\" validatePartnerEmail() \">\r\n                    <span class=\"valida" +
"tionError\" data-bind=\"validationMessage: Email\"></span>\r\n                </div>\r" +
"\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div class=\"row\">\r\n    " +
"<div class=\"col-md-6\">\r\n        <div class=\"form-group\">\r\n            <label cla" +
"ss=\"control-label col-md-6\">State :<span class=\"required\">*</span></label>\r\n    " +
"        <div class=\"col-md-6\" data-bind=\"with: PartnerRegistrationAddress\">\r\n   " +
"             <div>\r\n                    <select id=\"ddlState\" name=\"\" class=\"for" +
"m-control\" data-bind=\"options: $root.States, optionsText: \'StateName\', optionsCa" +
"ption: \'Select...\', optionsValue: \'StateCode\', value: State, enable: $root.Isvie" +
"w\" onchange=\" validateState() \"></select>\r\n                    <span class=\"vali" +
"dationError\" id=\"validationState\"></span>\r\n                </div>\r\n            <" +
"/div>\r\n        </div>\r\n    </div>\r\n    <div class=\"col-md-6\">\r\n        <div clas" +
"s=\"form-group\">\r\n            <label class=\"control-label col-md-6\">Mobile Number" +
" :<span class=\"required\">*</span></label>\r\n            <div class=\"col-md-6\" dat" +
"a-bind=\"with: PartnerRegistrationAddress\">\r\n                <div>\r\n             " +
"       <input type=\"text\" id=\"txtMobileNo\" name=\"\" class=\"form-control\" data-bin" +
"d=\"value: MobileNumber, event: { keypress: $root.validationHelper.ValidateNumeri" +
"cOnly },enable: $root.Isview\" onchange=\" validatePartnerMobile() \">\r\n           " +
"         <span class=\"validationError\" id=\"validationPartnerMobile\"></span>\r\n   " +
"             </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n\r\n</div>\r" +
"\n\r\n<div class=\"row\">\r\n    <div class=\"col-md-6\">\r\n        <div class=\"form-group" +
"\">\r\n            <label class=\"control-label col-md-6\">Zip Code:<span class=\"requ" +
"ired\">*</span></label>\r\n            <div class=\"col-md-6\" data-bind=\"with: Partn" +
"erRegistrationAddress\">\r\n                <div>\r\n                    <input type=" +
"\"text\" id=\"zipCode\" name=\"\" class=\"form-control\" maxlength=\"6\" data-bind=\"value:" +
" ZipCode, event: { keypress: $root.validationHelper.ValidateNumeric }, enable: $" +
"root.Isview\" onchange=\" validatezipCode() \">\r\n                    <span class=\"v" +
"alidationError\" id=\"validationZipCode\"></span>\r\n                </div>\r\n        " +
"    </div>\r\n        </div>\r\n    </div>\r\n    <div class=\"col-md-6\">\r\n        <div" +
" class=\"form-group\">\r\n            <label class=\"control-label col-md-6\">Status :" +
"<span class=\"required\">*</span></label>\r\n            <div class=\"col-md-6\">\r\n   " +
"             <div>\r\n                    <select id=\"ddlStatus\" name=\"\" class=\"fo" +
"rm-control\" data-bind=\"options: $root.StatusList, optionsCaption: \'Select...\', v" +
"alue: Status, enable: $root.Isview\">\r\n                    </select>\r\n           " +
"         <span class=\"validationError\" data-bind=\"validationMessage: Status\"></s" +
"pan>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</" +
"div>\r\n\r\n\r\n<div class=\"row\">\r\n    <div class=\"row\">\r\n        <div class=\"col-md-6" +
"\">\r\n            <div class=\"row form-group\">\r\n                <label class=\"cont" +
"rol-label col-md-6\">Logo :<span class=\"required\">&nbsp;&nbsp;</span></label>\r\n  " +
"              <div class=\"col-md-6\" style=\"border: 1px solid #ccc; border-radius" +
": 5px;\">\r\n                    <table style=\"width: 100%; height: 20px;\">\r\n      " +
"                  <tr>\r\n                            <td>\r\n                      " +
"          <img id=\"sigImage\" src=\"#\" height=\"60\" data-bind=\"visible: (PartnerReg" +
"istrationAddress().LogoPath() != \'\' && PartnerRegistrationAddress().LogoPath() !" +
"= null)\">\r\n                                <span class=\"validationError\" id=\"val" +
"idationLogo\"></span>\r\n                            </td>\r\n                       " +
" </tr>\r\n                    </table>\r\n                </div>\r\n            </div>" +
"\r\n\r\n            <div class=\"row\">\r\n                <div class=\"col-md-12\">\r\n    " +
"                <label class=\"control-label col-md-6\"></label>\r\n                " +
"    <div class=\"col-md-6\">\r\n                        <span style=\"color: red\">Pre" +
"ferred Dimensions : 90 X 30</span>\r\n                    </div>\r\n                " +
"</div>\r\n            </div>\r\n            <div class=\"row\">\r\n                <labe" +
"l class=\"control-label col-md-6\"></label>\r\n                <div class=\"col-md-6\"" +
">\r\n                    <table>\r\n                        <tbody data-bind=\"with: " +
"PartnerRegistrationAddress\">\r\n                        <tr>\r\n                    " +
"        <td data-bind=\"visible: (LogoPath() != \'\' && LogoPath() != null)\">\r\n    " +
"                            <a href=\"\" id=\"fileNameLink\" data-bind=\"attr: { href" +
": application.viewbag.appSettings.uamapiUrl + \'/FileUploads/Logo/\' + LogoPath() " +
"}\" target=\"_blank\"><span data-bind=\"    text: LogoFileName\"></span></a>\r\n\r\n     " +
"                       </td>\r\n                        </tr>\r\n\r\n                 " +
"       </tbody>\r\n                    </table>\r\n                </div>\r\n         " +
"   </div>\r\n            <div class=\"row\">\r\n                <label class=\"control-" +
"label col-md-6\"></label>\r\n                <div class=\"col-md-6\">\r\n              " +
"      <div class=\"fileupload-buttonbar\">\r\n                        <div class=\"fo" +
"rm-group\">\r\n                            <div class=\"col-md-12\" data-bind=\"visibl" +
"e:  $root.Isview\">\r\n                                <span class=\"btn btn-xs gree" +
"n fileinput-button\">\r\n                  <i class=\"fa fa-plus\"></i>\r\n            " +
"      <span>Browse\r\n                  </span>\r\n                  <input type=\"fi" +
"le\" class=\"upload\" name=\"files[]\" id=\"fileToUpload\" multiple />\r\n              <" +
"/span>\r\n                                <button type=\"button\" id=\"CapturePicture" +
"\" data-icon=\"upload\" data-role=\"button\" data-bind=\"click: $root.uploadFile\" clas" +
"s=\"btn btn-xs blue start\">\r\n                                    <i class=\"fa fa-" +
"upload\"></i>\r\n                                    <span>Upload\r\n                " +
"  </span>\r\n\r\n                                </button>\r\n                        " +
"    </div>\r\n                        </div>\r\n                    </div>\r\n        " +
"        </div>\r\n            </div>\r\n\r\n        </div>\r\n        <div class=\"col-md" +
"-6\">\r\n            <div class=\"form-group\">\r\n                <label class=\"contro" +
"l-label col-md-6\">Nature of Business:<span class=\"required\">*</span></label>\r\n  " +
"              <div class=\"col-md-6\">\r\n                    <div>\r\n               " +
"         <input type=\"text\" id=\"txtNatureOfBusiness\" name=\"\" class=\"form-control" +
"\" maxlength=\"50\" data-bind=\"value: NatureOfBusiness, event: { keypress: $root.va" +
"lidationHelper.ValidateAlphaNumericWithSpaces }, enable: $root.Isview\">\r\n       " +
"                 <span class=\"validationError\" data-bind=\"validationMessage: Nat" +
"ureOfBusiness\"></span>\r\n                    </div>\r\n                </div>\r\n    " +
"        </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n</fieldset>\r\n\r\n<fieldset>\r\n " +
"   <legend>Details of Directors/Partners/Promoters</legend>\r\n    <div class=\"row" +
"\">\r\n        <div class=\"table-toolbar\">\r\n            <div id=\"tableheader\" data-" +
"bind=\"visible:$root.Isview\">\r\n                <a class=\"button gbtngreen\" id=\"bt" +
"nAddNew\" data-bind=\"click: $root.AddNewDetails\"><i class=\"fa fa-plus\"></i>Add Ne" +
"w</a>\r\n            </div>\r\n            <div class=\"table-scrollable\">\r\n         " +
"       <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" id=\"tblmovementsdetails" +
"\" class=\"table tinytable\">\r\n                    <thead>\r\n                    <tr" +
">\r\n                        <th data-bind=\"visible: $root.Isview\">Action</th>\r\n  " +
"                      <th>Name</th>\r\n                        <th>Permanent Accou" +
"nt Number (PAN)</th>\r\n                        <th>Address</th>\r\n                " +
"        <th>Mobile</th>\r\n                        <th>Telephone</th>\r\n           " +
"             <th>Email</th>\r\n                    </tr>\r\n                    </th" +
"ead>\r\n                    <tbody data-bind=\"foreach: PartnerDirectorDetailss\">\r\n" +
"                    <!-- ko if: Type()==\'Director\' -->\r\n                    <tr " +
"data-bind=\"css: { trhighlight: ErrorStatus() }\">\r\n                        <td st" +
"yle=\"text-align: center;\" data-bind=\"visible: $root.Isview\">\r\n                  " +
"          <a href=\'#\' id=\"btnRemove\" data-bind=\'click: $root.RemoveDetails\' titl" +
"e=\"Remove\"><i class=\"fa fa-ban ban-before\"></i></a></td>\r\n                      " +
"  <td>\r\n                            <input type=\"text\" class=\"form-control clipp" +
"ed\" maxlength=\"20\" data-bind=\"value: PDirectorName, event: { keypress: $root.val" +
"idationHelper.ValidateAlphabetsWithSpaces_keypressEvent }, enable: $root.Isview," +
" attr: { title: PDirectorName }\"></td>\r\n                        <td style=\"width" +
": 14%\">\r\n                            <input type=\"text\" class=\"form-control\" sty" +
"le=\"text-transform: uppercase\" maxlength=\"10\" data-bind=\"value: PDirectorPAN, ev" +
"ent: { keypress: $root.validationHelper.ValidateAlphaNumeric }, enable: $root.Is" +
"view\"></td>\r\n                        <td style=\"width: 25%\">\r\n                  " +
"          <textarea class=\"form-control clipped\" style=\"resize: none;\" rows=\"1\" " +
"data-bind=\"value: PDirectorAddress, event: { keypress: $root.validationHelper.Va" +
"lidateAlphabetsWithSpaces_keypressEvent }, enable: $root.Isview, attr: { title: " +
"PDirectorAddress }\"></textarea></td>\r\n                        <td style=\"width: " +
"14%\">\r\n                            <div class=\"col-md-12\">\r\n                    " +
"            <div class=\"col-md-1\" style=\"text-align: -webkit-right;\"> +</div>\r\n " +
"                               <div class=\"col-md-3\">\r\n                         " +
"           <input type=\"text\" class=\"form-control\" data-bind=\"value: PCountryCod" +
"e, event: { keypress: $root.validationHelper.ValidateNumeric }, attr: { id: \'cou" +
"ntryCode\' + $index() }, enable: $root.Isview\" maxlength=\"3\">\r\n                  " +
"              </div>\r\n                                <div class=\"col-md-8\">\r\n  " +
"                                  <input type=\"text\" class=\"form-control\" maxlen" +
"gth=\"15\" data-bind=\"value: PDirectorMobile, event: { keypress: $root.validationH" +
"elper.ValidateNumeric }, attr: { id: \'pDirectorMobile\' + $index(), title: PDirec" +
"torMobile }, enable: $root.Isview\">\r\n                                </div>\r\n   " +
"                         </div></td>\r\n                        <td style=\"width: " +
"13%\">\r\n                            <input type=\"text\" class=\"form-control\" maxle" +
"ngth=\"11\" data-bind=\"value: PDirectorTele, event: { keypress: $root.validationHe" +
"lper.ValidateNumeric }, enable: $root.Isview\"></td>\r\n                        <td" +
">\r\n                        <input type=\"text\" id=\"emailId\" name=\"\" class=\"form-c" +
"ontrol clipped\" data-bind=\"value: PDirectorEmail, event: { keypress: $root.valid" +
"ationHelper.ValidateAlphanumericEmail }, enable: $root.Isview, attr: { title: PD" +
"irectorEmail }\" maxlength=\"254\">\r\n                    </tr>\r\n                   " +
" <!-- /ko -->\r\n                    </tbody>\r\n                </table>\r\n         " +
"   </div>\r\n        </div>\r\n\r\n    </div>\r\n</fieldset>\r\n<fieldset>\r\n    <legend>Ba" +
"nk Details</legend>\r\n    <div class=\"row\">\r\n        <div class=\"col-md-6\">\r\n    " +
"        <div class=\"form-group\">\r\n                <label class=\"control-label co" +
"l-md-6\">Bank Name:<span class=\"required\">*</span></label>\r\n                <div " +
"class=\"col-md-6\">\r\n                    <input type=\"text\" name=\"\" class=\"form-co" +
"ntrol clipped\" maxlength=\"20\" data-bind=\"value: BankName, event: { keypress: $ro" +
"ot.validationHelper.ValidateAlphabetsWithSpaces_keypressEvent }, enable: $root.I" +
"sview, attr: { title: BankName }\">\r\n                    <span class=\"validationE" +
"rror\" data-bind=\"validationMessage: BankName\"></span>\r\n                </div>\r\n " +
"           </div>\r\n        </div>\r\n        <div class=\"col-md-6\">\r\n            <" +
"div class=\"form-group\">\r\n                <label class=\"control-label col-md-6\">A" +
"ccount No.:<span class=\"required\">*</span></label>\r\n                <div class=\"" +
"col-md-6\">\r\n                    <input type=\"text\" name=\"\" class=\"form-control\" " +
"maxlength=\"18\" data-bind=\"value: AccountNo, event: { keypress: $root.validationH" +
"elper.ValidateNumeric }, enable: $root.Isview\">\r\n                    <span class" +
"=\"validationError\" data-bind=\"validationMessage: AccountNo\"></span>\r\n\r\n         " +
"       </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <div class=" +
"\"row\">\r\n        <div class=\"col-md-6\">\r\n            <div class=\"form-group\">\r\n  " +
"              <label class=\"control-label col-md-6\">Bank Address :<span class=\"r" +
"equired\">*</span></label>\r\n                <div class=\"col-md-6\">\r\n             " +
"       <textarea name=\"\" class=\"form-control clipped\" maxlength=\"40\" style=\"resi" +
"ze: none;\" data-bind=\"value: BankAddress, event: { keypress: $root.validationHel" +
"per.ValidateAlphaNumericWithSpaces_keypressEvent }, enable: $root.Isview, attr: " +
"{ title: BankAddress }\"></textarea>\r\n                    <span class=\"validation" +
"Error\" data-bind=\"validationMessage: BankAddress\"></span>\r\n                </div" +
">\r\n            </div>\r\n        </div>\r\n        <div class=\"col-md-6\">\r\n         " +
"   <div class=\"form-group\">\r\n                <label class=\"control-label col-md-" +
"6\">IFSC Code :<span class=\"required\">*</span></label>\r\n                <div clas" +
"s=\"col-md-6\">\r\n                    <input type=\"text\" name=\"\" class=\"form-contro" +
"l\" maxlength=\"11\" data-bind=\"value: IFSCCode, event: { keypress: $root.validatio" +
"nHelper.ValidateAlphaNumeric }, enable: $root.Isview\">\r\n\r\n                    <s" +
"pan class=\"validationError\" data-bind=\"validationMessage: IFSCCode\"></span>\r\n   " +
"             </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n\r\n</field" +
"set>\r\n\r\n\r\n<fieldset>\r\n    <legend>Details of Representatives</legend>\r\n    <div " +
"class=\"row\">\r\n\r\n        <div class=\"col-md-6\">\r\n            <div style=\"width: 9" +
"7%;\">\r\n                <div class=\"table-toolbar\">\r\n\r\n                    <div i" +
"d=\"tableheader\" data-bind=\"visible:$root.Isview\">\r\n                        <a cl" +
"ass=\"button gbtngreen\" id=\"btnAddNewOperation\" data-bind=\"click: $root.AddNewOpe" +
"rationsDetails\"><i class=\"fa fa-plus\"></i>Add New</a>\r\n                    </div" +
">\r\n                    <div class=\"gridhead\">Operations <span class=\"required\">*" +
"</span></div>\r\n                    <div class=\"table-scrollable\" style=\"min-heig" +
"ht: 42px;\">\r\n                        <table cellpadding=\"0\" cellspacing=\"0\" bord" +
"er=\"0\" id=\"tblmovementsdetails\" class=\"table tinytable\">\r\n                      " +
"      <thead>\r\n                            <tr>\r\n                               " +
" <th data-bind=\"visible: $root.Isview\">Action</th>\r\n                            " +
"    <th>Name</th>\r\n                                <th>Mobile</th>\r\n            " +
"                    <th>Email</th>\r\n                            </tr>\r\n         " +
"                   </thead>\r\n                            <tbody data-bind=\"forea" +
"ch: PartnerOperationsDetailss\">\r\n                            <tr data-bind=\"visi" +
"ble: IsDeleted()==\'N\',css: { trhighlight: ErrorStatusOperations() }\">\r\n         " +
"                       <td style=\"text-align: center; width: 25px;\" data-bind=\"v" +
"isible: $root.Isview\">\r\n                                    <a href=\'#\' id=\"btnR" +
"emoveOperations\" data-bind=\'click: $root.RemoveOperationsDetails\' title=\"Remove\"" +
"><i class=\"fa fa-ban ban-before\"></i></a>\r\n                                </td>" +
"\r\n                                <td>\r\n                                    <inp" +
"ut type=\"text\" class=\"form-control clipped\" maxlength=\"50\" id=\"OperationsName\" d" +
"ata-bind=\"    value: PDirectorName, event: { keypress: $root.validationHelper.Va" +
"lidateAlphabetsWithSpaces_keypressEvent }, enable: $root.Isview, attr: { title: " +
"PDirectorName }\"></td>\r\n                                <td style=\"width: 26%\">\r" +
"\n                                    <div class=\"col-md-12\">\r\n                  " +
"                      <div class=\"col-md-1\" style=\"text-align: -webkit-right;\">+" +
"</div>\r\n                                        <div class=\"col-md-3\">\r\n        " +
"                                    <input type=\"text\" class=\"form-control\" data" +
"-bind=\"value: PCountryCode, event: { keypress: $root.validationHelper.ValidateNu" +
"meric }, attr: { id: \'countryCode\' + $index() }, enable: $root.Isview\" maxlength" +
"=\"3\">\r\n                                        </div>\r\n                         " +
"               <div class=\"col-md-8\">\r\n                                         " +
"   <input type=\"text\" class=\"form-control clipped\" data-bind=\"value: PDirectorMo" +
"bile, event: { keypress: $root.validationHelper.ValidateNumeric }, attr: { id: \'" +
"pOperationsMobile\' + $index(), title: PDirectorMobile }, enable: $root.Isview\">\r" +
"\n                                        </div>\r\n                               " +
"     </div>\r\n                                </td>\r\n                            " +
"    <td>\r\n                                    <input type=\"text\" id=\"OperationEm" +
"ailId\" name=\"\" class=\"form-control clipped\" data-bind=\"value: PDirectorEmail, ev" +
"ent: { keypress: $root.validationHelper.ValidateAlphanumericEmail }, enable: $ro" +
"ot.Isview, attr: { title: PDirectorEmail }\" maxlength=\"100\"></td>\r\n\r\n           " +
"                 </tr>\r\n\r\n                            </tbody>\r\n                " +
"        </table>\r\n                    </div>\r\n                </div>\r\n          " +
"  </div>\r\n        </div>\r\n        <div class=\"col-md-6\">\r\n            <div style" +
"=\"width: 98%;\">\r\n                <div class=\"table-toolbar\">\r\n                  " +
"  <div id=\"tableheader\" data-bind=\"visible:$root.Isview\">\r\n                     " +
"   <a class=\"button gbtngreen\" id=\"btnAddNewIT\" data-bind=\"click: $root.AddNewIT" +
"Details\"><i class=\"fa fa-plus\"></i>Add New</a>\r\n                    </div>\r\n    " +
"                <div class=\"gridhead\">IT <span class=\"required\">*</span></div>\r\n" +
"                    <div class=\"table-scrollable\" style=\"min-height: 42px;\">\r\n  " +
"                      <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" id=\"tblm" +
"ovementsdetails\" class=\"table tinytable\">\r\n                            <thead>\r\n" +
"                            <tr>\r\n                                <th data-bind=" +
"\"visible: $root.Isview\">Action</th>\r\n                                <th>Name</t" +
"h>\r\n                                <th>Mobile</th>\r\n                           " +
"     <th>Email</th>\r\n                            </tr>\r\n                        " +
"    </thead>\r\n                            <tbody data-bind=\"foreach: PartnerITDe" +
"tailss\">\r\n                            <tr data-bind=\"visible: IsDeleted()==\'N\',c" +
"ss: { trhighlight: ErrorStatusIT() }\">\r\n                                <td styl" +
"e=\"text-align: center; width: 25px;\" data-bind=\"visible: $root.Isview\">\r\n       " +
"                             <a href=\'#\' id=\"btnRemoveIT\" data-bind=\'click: $roo" +
"t.RemoveITDetails\' title=\"Remove\"><i class=\"fa fa-ban ban-before\"></i></a></td>\r" +
"\n                                <td>\r\n                                    <inpu" +
"t type=\"text\" class=\"form-control clipped\" maxlength=\"50\" id=\"ITName\" data-bind=" +
"\"    value: PDirectorName, event: { keypress: $root.validationHelper.ValidateAlp" +
"habetsWithSpaces_keypressEvent }, enable: $root.Isview, attr: { title: PDirector" +
"Name }\"></td>\r\n                                <td style=\"width: 26%\">\r\n        " +
"                            <div class=\"col-md-12\">\r\n                           " +
"             <div class=\"col-md-1\" style=\"text-align: -webkit-right;\">+</div>\r\n " +
"                                       <div class=\"col-md-3\">\r\n                 " +
"                           <input type=\"text\" class=\"form-control\" data-bind=\"va" +
"lue: PCountryCode, event: { keypress: $root.validationHelper.ValidateNumeric }, " +
"attr: { id: \'countryCode\' + $index() }, enable: $root.Isview\" maxlength=\"3\">\r\n  " +
"                                      </div>\r\n                                  " +
"      <div class=\"col-md-8\">\r\n                                            <input" +
" type=\"text\" class=\"form-control clipped\" data-bind=\"value: PDirectorMobile, eve" +
"nt: { keypress: $root.validationHelper.ValidateNumeric }, attr: { id: \'pITMobile" +
"\' + $index(), title: PDirectorMobile }, enable: $root.Isview\">\r\n                " +
"                        </div>\r\n                                    </div>\r\n    " +
"                            </td>\r\n                                <td>\r\n       " +
"                             <input type=\"text\" id=\"ITemailId\" name=\"\" class=\"fo" +
"rm-control clipped\" data-bind=\"value: PDirectorEmail, event: { keypress: $root.v" +
"alidationHelper.ValidateAlphanumericEmail }, enable: $root.Isview, attr: { title" +
": PDirectorEmail }\" maxlength=\"100\"></td>\r\n\r\n                            </tr>\r\n" +
"\r\n                            </tbody>\r\n                        </table>\r\n      " +
"              </div>\r\n                </div>\r\n            </div>\r\n        </div>" +
"\r\n    </div>\r\n    <div class=\"row\">\r\n\r\n        <div class=\"col-md-6\">\r\n         " +
"   <div style=\"width: 97%;\">\r\n                <div class=\"table-toolbar\">\r\n     " +
"               <div id=\"tableheader\" data-bind=\"visible:$root.Isview\">\r\n        " +
"                <a class=\"button gbtngreen\" id=\"btnAddNewFinance\" data-bind=\"cli" +
"ck: $root.AddNewFinanceDetails\"><i class=\"fa fa-plus\"></i>Add New</a>\r\n         " +
"           </div>\r\n                    <div class=\"gridhead\">Finance <span class" +
"=\"required\">*</span></div>\r\n                    <div class=\"table-scrollable\" st" +
"yle=\"min-height: 42px;\">\r\n                        <table cellpadding=\"0\" cellspa" +
"cing=\"0\" border=\"0\" id=\"tblmovementsdetails\" class=\"table tinytable\">\r\n         " +
"                   <thead>\r\n                            <tr>\r\n                  " +
"              <th data-bind=\"visible: $root.Isview\">Action</th>\r\n               " +
"                 <th>Name</th>\r\n                                <th>Mobile</th>\r" +
"\n                                <th>Email</th>\r\n                            </t" +
"r>\r\n                            </thead>\r\n                            <tbody dat" +
"a-bind=\"foreach: PartnerFinanceDetailss\">\r\n                            <tr data-" +
"bind=\"visible: IsDeleted()==\'N\',css: { trhighlight: ErrorStatusFinance() }\">\r\n  " +
"                              <td style=\"text-align: center; width: 25px;\" data-" +
"bind=\"visible: $root.Isview\">\r\n                                    <a href=\'#\' i" +
"d=\"btnRemoveFinance\" data-bind=\'click: $root.RemoveFinanceDetails\' title=\"Remove" +
"\"><i class=\"fa fa-ban ban-before\"></i></a>\r\n                                </td" +
">\r\n                                <td>\r\n                                    <in" +
"put type=\"text\" class=\"form-control clipped\" maxlength=\"50\" id=\"PFinanceName\" da" +
"ta-bind=\"    value: PDirectorName, event: { keypress: $root.validationHelper.Val" +
"idateAlphabetsWithSpaces_keypressEvent }, enable: $root.Isview, attr: { title: P" +
"DirectorName }\"></td>\r\n                                <td style=\"width: 26%\">\r\n" +
"                                    <div class=\"col-md-12\">\r\n                   " +
"                     <div class=\"col-md-1\" style=\"text-align: -webkit-right;\">+<" +
"/div>\r\n                                        <div class=\"col-md-3\">\r\n         " +
"                                   <input type=\"text\" class=\"form-control\" data-" +
"bind=\"value: PCountryCode, event: { keypress: $root.validationHelper.ValidateNum" +
"eric }, attr: { id: \'countryCode\' + $index() }, enable: $root.Isview\" maxlength=" +
"\"3\">\r\n                                        </div>\r\n                          " +
"              <div class=\"col-md-8\">\r\n                                          " +
"  <input type=\"text\" class=\"form-control clipped\" data-bind=\"value: PDirectorMob" +
"ile, event: { keypress: $root.validationHelper.ValidateNumeric }, attr: { id: \'p" +
"FinanceMobile\' + $index(), title: PDirectorMobile }, enable: $root.Isview\">\r\n   " +
"                                     </div>\r\n                                   " +
" </div>\r\n                                </td>\r\n                                " +
"<td>\r\n                                    <input type=\"text\" id=\"FinanceEmailId\"" +
" name=\"\" class=\"form-control clipped\" data-bind=\"value: PDirectorEmail, event: {" +
" keypress: $root.validationHelper.ValidateAlphanumericEmail }, enable: $root.Isv" +
"iew, attr: { title: PDirectorEmail }\" maxlength=\"100\"></td>\r\n\r\n                 " +
"           </tr>\r\n\r\n                            </tbody>\r\n                      " +
"  </table>\r\n                    </div>\r\n                </div>\r\n            </di" +
"v>\r\n        </div>\r\n        <div class=\"col-md-6\">\r\n            <div style=\"widt" +
"h: 98%;\">\r\n                <div class=\"table-toolbar\">\r\n                    <div" +
" id=\"tableheader\" data-bind=\"visible:$root.Isview\">\r\n                        <a " +
"class=\"button gbtngreen\" id=\"btnAddNewSales\" data-bind=\"click: $root.AddNewSales" +
"Details\"><i class=\"fa fa-plus\"></i>Add New</a>\r\n                    </div>\r\n    " +
"                <div class=\"gridhead\">Sales</div>\r\n                    <div clas" +
"s=\"table-scrollable\" style=\"min-height: 42px;\">\r\n                        <table " +
"cellpadding=\"0\" cellspacing=\"0\" border=\"0\" id=\"tblmovementsdetails\" class=\"table" +
" tinytable\">\r\n                            <thead>\r\n                            <" +
"tr>\r\n                                <th data-bind=\"visible: $root.Isview\">Actio" +
"n</th>\r\n                                <th>Name</th>\r\n                         " +
"       <th>Mobile</th>\r\n                                <th>Email</th>\r\n        " +
"                    </tr>\r\n                            </thead>\r\n               " +
"             <tbody data-bind=\"foreach: PartnerSalesDetailss\">\r\n                " +
"            <tr data-bind=\"visible:(IsDeleted()==\'N\'),css: { trhighlight: ErrorS" +
"tatusSales() }\">\r\n                                <td style=\"text-align: center;" +
" width: 25px;\" data-bind=\"visible: $root.Isview\">\r\n                             " +
"       <a href=\'#\' id=\"btnRemoveSales\" data-bind=\'click: $root.RemoveSalesDetail" +
"s\' title=\"Remove\"><i class=\"fa fa-ban ban-before\"></i></a>\r\n                    " +
"            </td>\r\n                                <td>\r\n                       " +
"             <input type=\"text\" class=\"form-control clipped\" maxlength=\"50\" id=\"" +
"PSalesName\" data-bind=\"    value: PDirectorName, event: { keypress: $root.valida" +
"tionHelper.ValidateAlphabetsWithSpaces_keypressEvent }, enable: $root.Isview, at" +
"tr: { title: PDirectorName }\"></td>\r\n                                <td style=\"" +
"width: 26%\">\r\n                                    <div class=\"col-md-12\">\r\n     " +
"                                   <div class=\"col-md-1\" style=\"text-align: -web" +
"kit-right;\">+</div>\r\n                                        <div class=\"col-md-" +
"3\">\r\n                                            <input type=\"text\" class=\"form-" +
"control\" data-bind=\"value: PCountryCode, event: { keypress: $root.validationHelp" +
"er.ValidateNumeric }, attr: { id: \'countryCode\' + $index() }, enable: $root.Isvi" +
"ew\" maxlength=\"3\">\r\n                                        </div>\r\n            " +
"                            <div class=\"col-md-8\">\r\n                            " +
"                <input type=\"text\" class=\"form-control clipped\" data-bind=\"value" +
": PDirectorMobile, event: { keypress: $root.validationHelper.ValidateNumeric }, " +
"attr: { id: \'pSalesMobile\' + $index(), title: PDirectorMobile }, enable: $root.I" +
"sview\">\r\n                                        </div>\r\n                       " +
"             </div>\r\n                                </td>\r\n                    " +
"            <td>\r\n                                    <input type=\"text\" id=\"Sal" +
"esEmailId\" name=\"\" class=\"form-control clipped\" data-bind=\"value: PDirectorEmail" +
", event: { keypress: $root.validationHelper.ValidateAlphanumericEmail }, enable:" +
" $root.Isview, attr: { title: PDirectorEmail }\" maxlength=\"100\"></td>\r\n\r\n       " +
"                     </tr>\r\n\r\n                            </tbody>\r\n            " +
"            </table>\r\n                    </div>\r\n                </div>\r\n      " +
"      </div>\r\n        </div>\r\n    </div>\r\n</fieldset>\r\n\r\n\r\n\r\n");

WriteLiteral("\r\n\r\n\r\n\r\n<fieldset>\r\n    <legend>Documents Upload (All documents to be self attest" +
"ed with Company Seal)</legend>\r\n\r\n\r\n    <div class=\"row\" data-bind=\"visible:$roo" +
"t.Isview\">\r\n\r\n        <div class=\"table-responsive\">\r\n            <table class=\"" +
"tinytable\">\r\n                <thead>\r\n                <tr>\r\n                    " +
"<th class=\"bg-dark font-color1\" style=\"width: 50px;\">S.No.</th>\r\n               " +
"     <th class=\"bg-dark font-color1\">Document Type</th>\r\n                    <th" +
" class=\"bg-dark font-color1\">Upload</th>\r\n                    <th class=\"bg-dark" +
" font-color1\">Document Name</th>\r\n                    <th class=\"bg-dark font-co" +
"lor1\" style=\"width: 100px;\">Valid Till</th>\r\n                    <th class=\"bd-d" +
"ark font-color1\" style=\"width: 100px;\">Action</th>\r\n\r\n                </tr>\r\n   " +
"             </thead>\r\n                <tbody data-bind=\"foreach: DocumentDTOs\">" +
"\r\n                <tr data-bind=\"css: { trhighlight: ErrorStatusDocument() }\">\r\n" +
"                    <td data-bind=\"text: $index() + 1\" style=\"text-align: center" +
";\"></td>\r\n                    <td data-bind=\"text: DocumentType\"></td>\r\n        " +
"            <td>\r\n                        <input class=\"btn btn\" data-bind=\"kend" +
"oUpload: {\r\n    async: {\r\n        saveUrl: \'/api/MultipleFileUpload/DocType_Copy" +
"/KPCT\',\r\n        autoUpload: true\r\n    }, localization: {\r\n        select: \'Uplo" +
"ad Document\', dropFilesHere: \'\'\r\n    }, enabled: $root.IsbuttonsEnable, multiple" +
": false, select: SelectFile, upload: $root.Upload, success: $root.FileSuccess,\r\n" +
"    showFileList: false\r\n}, attr: { id: \'upload\' + $index() }\"\r\n                " +
"               type=\"file\" multiple=\"multiple\" title=\"Upload Document\"/></td>\r\n " +
"                   <td><a data-bind=\"text: FileName, attr: { href: \'/FileUploads" +
"/\' + FileName() }\" target=\"_blank\" style=\"text-decoration: underline;\"></a></td>" +
"\r\n                    <td>\r\n\r\n                        <div data-bind=\"attr: { id" +
": \'IsvalidTill\' + $index() }\" style=\"display: none\">\r\n                          " +
"  ");

WriteLiteral("\r\n                            <input type=\"text\" class=\"date-picker\" onkeypress=\"" +
" return false; \" data-bind=\"kendoDatePicker: { value: ValidTill, format: \'dd-MM-" +
"yyyy\', readonly: true }, attr: { id: \'validTill\' + $index(), enable: false }\" na" +
"me=\"ValidTill\"/>\r\n                            <span class=\"validationError\" id=\"" +
"validTilltxt\"></span>\r\n                        </div>\r\n                    </td>" +
"\r\n                    <td style=\"text-align: center;\">\r\n                        " +
"<a href=\"#\" title=\"Remove\" data-bind=\"click: $root.RemoveDocument, visible: (Fil" +
"eName() !== null && FileName() !== \'\')\"><i class=\"fa fa-ban ban-before\" data-bin" +
"d=\"    attr: { id: $index() }\"></i></a>\r\n                    </td>\r\n            " +
"    </tr>\r\n                </tbody>\r\n            </table>\r\n        </div>\r\n    <" +
"/div>\r\n\r\n    <div class=\"portlet box advbg\" data-bind=\"visible:!$root.Isview()\">" +
"\r\n        <div class=\"portlet-title\">\r\n            <div class=\"caption\">\r\n      " +
"          Uploaded Files\r\n            </div>\r\n            <div class=\"tools\">\r\n " +
"               <a href=\"javascript:;\" class=\"collapse\"></a>\r\n            </div>\r" +
"\n        </div>\r\n        <div class=\"portlet-body\">\r\n            <div class=\"row" +
"\">\r\n                <div>\r\n                    <div style=\"height: 5px;\"></div>\r" +
"\n                    <div class=\"row\">\r\n                        <div class=\"tabl" +
"e-responsive\">\r\n                            <table class=\"tinytable\">\r\n         " +
"                       <thead>\r\n                                <tr>\r\n          " +
"                          <th class=\"bg-dark font-color1\" style=\"width: 50px;\">S" +
".No.</th>\r\n                                    <th class=\"bg-dark font-color1\">D" +
"ocument Type</th>\r\n                                    <th class=\"bg-dark font-c" +
"olor1\">Document Name</th>\r\n                                    <th class=\"bg-dar" +
"k font-color1\" style=\"width: 100px;\">Valid Till</th>\r\n\r\n                        " +
"        </tr>\r\n                                </thead>\r\n                       " +
"         <tbody data-bind=\"foreach: DocumentDTOs\">\r\n                            " +
"    <tr>\r\n                                    <td data-bind=\"text: $index() + 1\"" +
" style=\"text-align: center;\"></td>\r\n                                    <td data" +
"-bind=\"text: DocumentType\" style=\"text-align: left;\"></td>\r\n                    " +
"                <td><a data-bind=\"text: FileName, attr: { href: \'/FileUploads/\' " +
"+ FileName() }\" target=\"_blank\" style=\"text-decoration: underline;\"></a></td>\r\n " +
"                                   <td data-bind=\"text: ValidTill\" style=\"text-a" +
"lign: center;\"></td>\r\n\r\n                                </tr>\r\n                 " +
"               </tbody>\r\n                            </table>\r\n                 " +
"       </div>\r\n                    </div>\r\n\r\n\r\n                </div>\r\n         " +
"   </div>\r\n        </div>\r\n    </div>\r\n\r\n\r\n\r\n</fieldset>\r\n\r\n<div class=\"row\">\r\n " +
"   <div class=\"col-md-1\" align=\"right\">\r\n        <input class=\"k-header k-with-i" +
"con k-filterable\" type=\'Checkbox\' data-bind=\"checked: IsAccept, enable: false\"/>" +
"\r\n    </div>\r\n    <div class=\"col-md-11\">I / We hereby declare that the above st" +
"ated information is true and correct and will be held liable for any omission, i" +
"ncorrect, incomplete of misdeclaration to herein above. We undertake to keep you" +
"r office informed of any changes to the above details and re-submit the relevant" +
" documents along with revised KYC Form</div>\r\n</div>\r\n<div class=\"row\">&nbsp;</d" +
"iv>\r\n\r\n\r\n\r\n");

WriteLiteral("\r\n\r\n<div id=\"rejectBulk\" class=\"modal fade\" tabindex=\"-1\">\r\n    <div class=\"modal" +
"-dialog\" id=\"stk\">\r\n        <div class=\"modal-content\">\r\n            <div class=" +
"\"modal-body\">\r\n                <button type=\"button\" class=\"close\" id=\"rejectBul" +
"kClose\" data-dismiss=\"modal\" data-bind=\"visible: false\"></button>\r\n             " +
"   <div class=\"form-wizard\">\r\n                    <div class=\"col-md-12 form-gro" +
"up\">\r\n                        <h3 id=\"lblMainHeading\" style=\"border-bottom: 2px " +
"solid #ccc; margin-top: 1px; padding-bottom: 5px;\"></h3>\r\n                    </" +
"div>\r\n                    <div data-always-visible=\"1\" data-rail-visible1=\"1\">\r\n" +
"                        <div class=\"form-group\">\r\n                            <l" +
"abel id=\"lblRejectsContainer\"></label>\r\n                        </div>\r\n        " +
"                <div data-bind=\"visible: $root.IsRemarksVisible\">\r\n             " +
"               <fieldset>\r\n                                <form action=\"#\" id=\"" +
"form_sample_2\" class=\"form-horizontal\">\r\n\r\n                                    <" +
"div class=\"row\" data-bind=\"if: $root.IsReject\">\r\n                               " +
"         <div class=\"form-group\">\r\n                                            <" +
"label id=\"lblheadingReject\" class=\"col-md-6 control-label\">Reason For Reject:<sp" +
"an class=\"required\" style=\"color: red\">*</span></label>\r\n                       " +
"                     <div class=\"col-md-6\">\r\n                                   " +
"             <textarea class=\"form-control\" onchange=\" HandleValidateRejectRemar" +
"ks(this); \" id=\"txtAreaRejectsRemarks\" style=\"resize: none; width: 100%; border:" +
" 1px solid #ccc;\" data-bind=\"value: $root.Remarks, visible: $root.IsReject\" maxl" +
"ength=\"500\"></textarea>\r\n                                                <span i" +
"d=\"spanReject\" class=\"validationError\"></span>\r\n                                " +
"            </div>\r\n                                        </div>\r\n            " +
"                        </div>\r\n\r\n                                    <div class" +
"=\"row\" data-bind=\"if: $root.IsApprove\">\r\n                                       " +
" <div class=\"form-group\">\r\n                                            <label id" +
"=\"lblheadingApprove\" class=\"col-md-6 control-label\">Partner Code:<span class=\"re" +
"quired\" style=\"color: red\">*</span></label>\r\n                                   " +
"         <div class=\"col-md-6\">\r\n                                               " +
" <input type=\"text\" class=\"form-control\" onchange=\" HandleValidateRejectRemarks(" +
"this); \" id=\"txtAreaPartnerCode\" style=\"resize: none; width: 100%; border: 1px s" +
"olid #ccc;\" data-bind=\"value: $root.PartnerCode, visible: $root.IsApprove, event" +
": { keypress: $root.validationHelper.ValidateAlphaNumeric, change: $root.Dupliac" +
"teValidation }\" maxlength=\"25\"/>\r\n                                              " +
"  <span id=\"spanApprove\" class=\"validationError\"></span>\r\n                      " +
"                      </div>\r\n                                        </div>\r\n  " +
"                                  </div>\r\n\r\n                                    " +
"<div class=\"row\" data-bind=\"if: $root.IsApprove\">\r\n                             " +
"           <div class=\"form-group\">\r\n                                           " +
" <label id=\"lblheading1\" class=\"col-md-6 control-label\">User Name:<span class=\"r" +
"equired\" style=\"color: red\">*</span></label>\r\n                                  " +
"          <div class=\"col-md-6\">\r\n                                              " +
"  <input class=\"form-control\" type=\"text\" onchange=\" HandleValidateRejectRemarks" +
"(this); \" id=\"txtAreaUserName\" style=\"resize: none;\" data-bind=\"value: $root.Use" +
"rName, visible: $root.IsApprove, event: { keypress: $root.validationHelper.Valid" +
"ateAlphaNumeric, change: $root.validateUserName }\" maxlength=\"30\"/>\r\n           " +
"                                     <span id=\"spanUserName\" class=\"validationEr" +
"ror\"></span>\r\n                                            </div>\r\n              " +
"                          </div>\r\n                                    </div>\r\n\r\n" +
"                                    <div class=\"row\" data-bind=\"if: $root.IsAppr" +
"ove\">\r\n                                        <div class=\"form-group\">\r\n       " +
"                                     <label id=\"lblheading2\" class=\"col-md-6 con" +
"trol-label\">First Name:<span class=\"required\" style=\"color: red\">*</span></label" +
">\r\n                                            <div class=\"col-md-6\">\r\n         " +
"                                       <input type=\"text\" class=\"form-control\" o" +
"nchange=\" changeFirstname(this); \" id=\"txtAreaFirstName\" style=\"resize: none; wi" +
"dth: 100%; border: 1px solid #ccc;\" data-bind=\"value: $root.FirstName, visible: " +
"$root.IsApprove, event: { keypress: $root.validationHelper.ValidateAlphabetsWith" +
"Spaces_keypressEvent }\" maxlength=\"50\"/>\r\n                                      " +
"          <span id=\"spanFirstName\" class=\"validationError\"></span>\r\n            " +
"                                </div>\r\n                                        " +
"</div>\r\n                                    </div>\r\n\r\n                          " +
"          <div class=\"row\" data-bind=\"if: $root.IsApprove\">\r\n                   " +
"                     <div class=\"form-group\">\r\n                                 " +
"           <label id=\"lblheading3\" class=\"col-md-6 control-label\">Last Name:<spa" +
"n class=\"required\" style=\"color: red\">*</span></label>\r\n                        " +
"                    <div class=\"col-md-6\">\r\n                                    " +
"            <input type=\"text\" class=\"form-control\" onchange=\" changeLastname(th" +
"is); \" id=\"txtAreaLastName\" style=\"resize: none; width: 100%; border: 1px solid " +
"#ccc;\" data-bind=\"value: $root.LastName, visible: $root.IsApprove, event: { keyp" +
"ress: $root.validationHelper.ValidateAlphabetsWithSpaces_keypressEvent }\" maxlen" +
"gth=\"50\"/>\r\n                                                <span id=\"spanLastNa" +
"me\" class=\"validationError\"></span>\r\n                                           " +
" </div>\r\n                                        </div>\r\n                       " +
"             </div>\r\n                                    <div class=\"row\" data-b" +
"ind=\"if: $root.IsApprove\">\r\n                                        <div class=\"" +
"form-group\">\r\n                                            <label id=\"lblheading4" +
"\" class=\"col-md-6 control-label\">Roles:<span class=\"required\" style=\"color: red\"" +
">*</span></label>\r\n                                            <div class=\"col-m" +
"d-6\">\r\n\r\n                                                <input class=\"displaytx" +
"t col-md-12\" id=\"userPort\" onchange=\" validateRole(this); \" data-bind=\"kendoMult" +
"iSelect: { dataTextField: \'RoleName\', dataValueField: \'RoleId\', data: $parent.Ro" +
"les, value: UserRoleArray }\"/>\r\n\r\n                                              " +
"  <span id=\"spnrole\" style=\"margin: 15px -0px 0px 0px\" class=\"validationError\"><" +
"/span>\r\n\r\n                                            </div>\r\n                  " +
"                      </div>\r\n                                    </div>\r\n      " +
"                          </form>\r\n                            </fieldset>\r\n    " +
"                    </div>\r\n                    </div>\r\n                    <div" +
" class=\"btns-group fluid \" data-bind=\"loadingWhen: $root.viewModelHelper.isLoadi" +
"ng\">\r\n                        <button type=\"submit\" class=\"btn green\" data-bind=" +
"\"click: $parent.RejectsForm, visible: $root.IsReject\" value=\"POST VAL\">Save</but" +
"ton>\r\n                        <button type=\"submit\" class=\"btn green\" data-bind=" +
"\"click: $parent.ApproveForm, visible: $root.IsApprove\" value=\"POST VAL\">Save</bu" +
"tton>\r\n                        <button type=\"submit\" class=\"btn green\" data-bind" +
"=\"click: $parent.VerifyForm, visible: $root.IsVerify\" value=\"POST VAL\">Yes</butt" +
"on>\r\n                        <button type=\"submit\" class=\"btn green\" data-bind=\"" +
"click: $parent.UpdateForm, visible: $root.IsUpdate\" value=\"POST VAL\">Yes</button" +
">\r\n                        <button id=\"btnPopUpNo\" type=\"submit\" class=\"btn red\"" +
" data-bind=\"click: $parent.closeRejectBulkPopup,text:($root.IsVerify()?\'No\':\'Can" +
"cel\')\"></button>\r\n                    </div>\r\n                </div>\r\n          " +
"  </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n\r\n\r\n\r\n<div class=\"btns-group for" +
"m-actions fluid\">\r\n    <button type=\"button\" class=\"btn green\" id=\"btnVerify0\" d" +
"ata-bind=\"click: $root.validateContainersPopup,visible:(\'");

            
            #line 1161 "..\..\Views\PartnerRegistration\PartnerRegistrationView.cshtml"
                                                                                                                 Write(ViewBag.UserRole);

            
            #line default
            #line hidden
WriteLiteral("\' == \'ACC\' && WFStatus()==\'New\')\">Verify</button>\r\n    <button type=\"button\" clas" +
"s=\"btn red\" id=\"btnRejectVerification0\" data-bind=\"click: $root.validateContaine" +
"rsPopup,visible:(\'");

            
            #line 1162 "..\..\Views\PartnerRegistration\PartnerRegistrationView.cshtml"
                                                                                                                           Write(ViewBag.UserRole);

            
            #line default
            #line hidden
WriteLiteral("\' == \'ACC\' && WFStatus()==\'New\')\">Reject</button>\r\n    <button type=\"button\" clas" +
"s=\"btn green\" id=\"btnApprove0\" data-bind=\"click: $root.validateContainersPopup,v" +
"isible:(\'");

            
            #line 1163 "..\..\Views\PartnerRegistration\PartnerRegistrationView.cshtml"
                                                                                                                  Write(ViewBag.UserRole);

            
            #line default
            #line hidden
WriteLiteral("\' == \'TerminalOperator\' && WFStatus()==\'Verified\')\">Approve</button>\r\n    <button" +
" type=\"button\" class=\"btn red\" id=\"btnReject0\" data-bind=\"click: $root.validateC" +
"ontainersPopup,visible:(\'");

            
            #line 1164 "..\..\Views\PartnerRegistration\PartnerRegistrationView.cshtml"
                                                                                                               Write(ViewBag.UserRole);

            
            #line default
            #line hidden
WriteLiteral("\' == \'TerminalOperator\' && WFStatus()==\'Verified\')\">Reject</button>\r\n    <button " +
"type=\"button\" class=\"btn green\" id=\"btnUpdate0\" data-bind=\"click: $root.validate" +
"ContainersPopup,visible:((\'");

            
            #line 1165 "..\..\Views\PartnerRegistration\PartnerRegistrationView.cshtml"
                                                                                                                  Write(ViewBag.UserRole);

            
            #line default
            #line hidden
WriteLiteral("\' == \'ACC\' && WFStatus()!=\'Approved\' && WFStatus()!=\'Verified\' ) ||(\'");

            
            #line 1165 "..\..\Views\PartnerRegistration\PartnerRegistrationView.cshtml"
                                                                                                                                                                                                        Write(ViewBag.UserRole);

            
            #line default
            #line hidden
WriteLiteral(@"' == 'TerminalOperator')) && $root.Isview()"">Update</button>

    <button type=""button"" class=""btn green"" id=""btnVerify"" data-target=""#rejectBulk"" data-toggle=""modal"" data-bind=""click: $root.ShowContainersPopup,visible:false"">Verify</button>
    <button type=""button"" class=""btn red"" id=""btnRejectVerification"" data-target=""#rejectBulk"" data-toggle=""modal"" data-bind=""click: $root.ShowContainersPopup,visible:false"">Reject</button>
    <button type=""button"" class=""btn green"" id=""btnApprove"" data-target=""#rejectBulk"" data-toggle=""modal"" data-bind=""click: $root.ShowContainersPopup,visible:false"">Approve</button>
    <button type=""button"" class=""btn red"" id=""btnReject"" data-target=""#rejectBulk"" data-toggle=""modal"" data-bind=""click: $root.ShowContainersPopup,visible:false"">Reject</button>
    <button type=""button"" class=""btn red"" id=""btnUpdate"" data-target=""#rejectBulk"" data-toggle=""modal"" data-bind=""click: $root.ShowContainersPopup,visible:false"">Update</button>
                          <button type=""submit"" class=""btn default button-previous"" data-bind=""click: $root.ExitScreen""><i class=""m-icon-swapleft""></i>Back</button>
                            </div>
                        </div>



                    </div>



                </div>
            </div>


        </div>
    </div>
</script>
");

        }
    }
}
#pragma warning restore 1591
