#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PartnerRegistration/PartnerRegistration.cshtml")]
    public partial class _Views_PartnerRegistration_PartnerRegistration_cshtml : System.Web.Mvc.WebViewPage<PortKonnect.UserAccessManagement.Domain.DTOS.PrivilegeDTO>
    {
        public _Views_PartnerRegistration_PartnerRegistration_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\PartnerRegistration\PartnerRegistration.cshtml"
      
    ViewBag.Title = "PartnerRegistration";
    Layout = "~/Views/Shared/_eGateLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 388), Tuple.Create("\"", 453)
, Tuple.Create(Tuple.Create("", 394), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/Model/PartnerRegistrationModel.js")
, 394), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 477), Tuple.Create("\"", 550)
, Tuple.Create(Tuple.Create("", 483), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/ViewModel/PartnerRegistrationViewModel.js")
, 483), false)
);

WriteLiteral("></script>\r\n");

});

DefineSection("ko_apply", () => {

WriteLiteral("\r\nvar viewModel = new eGateRoot.PartnerKYCFormViewModel();\r\nko.applyBindingsWithV" +
"alidation(viewModel, $(\"#KYCForm\")[0], { insertMessages: false, messagesOnModifi" +
"ed: false, grouping: { deep: true }});\r\n");

});

WriteLiteral(@"
<style>
    .k-upload-status .k-upload-status-total {
        visibility: hidden;
        display: none;
    }

    .k-icon .k-i-tick {
        visibility: hidden;
        display: none;
    }

    .k-upload-status .k-upload-status-total {
        visibility: hidden;
        display: none;
    }

    .k-upload-button > span {
        padding: 8px !important;
    }

    .k-dropzone strong {
        display: none;
    }

    .k-upload-empty > validationError {
        position: relative !important;
    }

    .k-upload-status {
        display: none;
    }

    .k-widget {
        border-color: #F1F6FA;
    }
</style>


<div");

WriteLiteral(" id=\"KYCForm\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" data-bind=\"visible: viewMode() == \'Form\', template: { name: \'Form-template\' }\"");

WriteLiteral("></div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n\r\n<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"Form-template\"");

WriteLiteral(">\r\n    <div class=\"row\">\r\n        <div class=\"col-md-12\">\r\n            <h3 class=" +
"\"page-title\"><span id=\"spnTitle\">Partner Registration</span></h3>\r\n            <" +
"ul class=\"page-breadcrumb breadcrumb\"></ul>\r\n        </div>\r\n    </div>\r\n    <di" +
"v class=\"portlet-body\">\r\n        <div class=\"table-toolbar\">\r\n\r\n            <div" +
" class=\"portlet portlet-body form\" data-bind=\"loadingWhen: $root.viewModelHelper" +
".isLoading\">\r\n                <div class=\"form-wizard\">\r\n                    <di" +
"v class=\"form-body form-horizontal\">\r\n                        <div class=\"form-g" +
"roup\" data-bind=\"with: PartnerRegistrationModel\">\r\n                            <" +
"fieldset>\r\n                                <legend>Partner Selection</legend>\r\n " +
"                               <div class=\"row\">\r\n                              " +
"      <div class=\"\">\r\n                                        <div class=\"form-g" +
"roup\">\r\n                                            <label class=\"control-label " +
"col-md-2\">Partner Selection:</label>\r\n                                          " +
"  <div class=\"col-md-5\">\r\n                                                <div c" +
"lass=\"radio-list\">\r\n                                                    <input t" +
"ype=\"radio\" id=\"partVOA\" name=\"partnerselection\" value=\"VesselOperatingAgent\" da" +
"ta-bind=\"checked: PartnerType, event: { click: $root.GetDocTypes }\">\r\n          " +
"                                          <label class=\"radio-inline\">VOA</label" +
">&nbsp;&nbsp;&nbsp;&nbsp;\r\n                                                    <" +
"input type=\"radio\" id=\"partCOA\" name=\"partnerselection\" value=\"ContainerOperator" +
"Agent\" data-bind=\"checked: PartnerType, event: { click: $root.GetDocTypes }\">\r\n " +
"                                                   <label class=\"radio-inline\">C" +
"OA</label>&nbsp;&nbsp;&nbsp;&nbsp;\r\n                                            " +
"        <input type=\"radio\" id=\"partCHA\" name=\"partnerselection\" value=\"CustomHo" +
"useAgent\" data-bind=\"checked: PartnerType, event: { click: $root.GetDocTypes }\">" +
"\r\n                                                    <label class=\"radio-inline" +
"\">CHA</label>&nbsp;&nbsp;&nbsp;&nbsp;\r\n                                         " +
"           <input type=\"radio\" id=\"partCFS\" name=\"partnerselection\" value=\"Conta" +
"inerFreightStation\" data-bind=\"checked: PartnerType, event: { click: $root.GetDo" +
"cTypes }\">\r\n                                                    <label class=\"ra" +
"dio-inline\">CFS</label>&nbsp;&nbsp;&nbsp;&nbsp;\r\n                               " +
"                     <input type=\"radio\" id=\"partM&R\" name=\"partnerselection\" va" +
"lue=\"MandR\" data-bind=\"checked: PartnerType, event: { click: $root.GetDocTypes }" +
"\">\r\n                                                    <label class=\"radio-inli" +
"ne\">M&R</label>\r\n                                                </div>\r\n       " +
"                                     </div>\r\n                                   " +
"     </div>\r\n                                    </div>\r\n                       " +
"         </div>\r\n                            </fieldset>\r\n\r\n                    " +
"        <fieldset>\r\n                                <legend>Establishment Detail" +
"s</legend>\r\n                                <div class=\"row\">\r\n                 " +
"                   <div class=\"col-md-6\">\r\n                                     " +
"   <div class=\"form-group\">\r\n                                            <label " +
"class=\"control-label col-md-6\">Name:<span class=\"required\">*</span></label>\r\n   " +
"                                         <div class=\"col-md-6\">\r\n               " +
"                                 <div>\r\n                                        " +
"            <input type=\"text\" id=\"partnerName\" name=\"\" class=\"form-control\" dat" +
"a-bind=\"value: PartnerName, event: { keypress: $root.validationHelper.ValidateAl" +
"phabetsWithSpacesAndSpecialChars_keypressEvent, change: $root.CheckUniquePartner" +
"Name }\" maxlength=\"50\">\r\n                                                    <sp" +
"an class=\"validationError\" data-bind=\"validationMessage: PartnerName\"></span>\r\n " +
"                                               </div>\r\n                         " +
"                   </div>\r\n\r\n                                        </div>\r\n   " +
"                                 </div>\r\n                                    <di" +
"v class=\"col-md-6\">\r\n                                        <div class=\"form-gr" +
"oup\">\r\n                                            <label class=\"control-label c" +
"ol-md-6\">Year:<span class=\"required\">*</span></label>\r\n                         " +
"                   <div class=\"col-md-6\">\r\n                                     " +
"           <input type=\"text\" id=\"txtYear\" name=\"\" class=\"form-control\" maxlengt" +
"h=\"4\" data-bind=\"value: Year, event: { keypress: $root.validationHelper.Validate" +
"Numeric }\">\r\n                                                <span class=\"valida" +
"tionError\" data-bind=\"validationMessage: Year\"></span>\r\n                        " +
"                    </div>\r\n                                        </div>\r\n    " +
"                                </div>\r\n                                </div>\r\n" +
"                                <div class=\"row\">\r\n                             " +
"       <div class=\"col-md-6\">\r\n                                        <div clas" +
"s=\"form-group\">\r\n                                            <label class=\"contr" +
"ol-label col-md-6\">House Number:<span class=\"required\">*</span></label>\r\n       " +
"                                     <div class=\"col-md-6\" data-bind=\"with: Part" +
"nerRegistrationAddress\">\r\n                                                <div>\r" +
"\n                                                    <input type=\"text\" id=\"hous" +
"eNumber\" name=\"\" class=\"form-control\" data-bind=\"value: HouseNumber, event: { ke" +
"ypress: $root.validationHelper.ValidateAlphaNumericWithSpacesAndSpecialCharsForH" +
"ouseNo_keypressEvent }\" onchange=\" validateHouseNumber() \" maxlength=\"10\">\r\n    " +
"                                                <span class=\"validationError\" id" +
"=\"validationHouseNumber\"></span>\r\n                                              " +
"  </div>\r\n                                            </div>\r\n\r\n                " +
"                        </div>\r\n                                    </div>\r\n    " +
"                                <div class=\"col-md-6\">\r\n                        " +
"                <div class=\"form-group\">\r\n                                      " +
"      <label class=\"control-label col-md-6\">Street Name:<span class=\"required\">*" +
"</span></label>\r\n                                            <div class=\"col-md-" +
"6\" data-bind=\"with: PartnerRegistrationAddress\">\r\n                              " +
"                  <input type=\"text\" id=\"streetName\" name=\"\" class=\"form-control" +
"\" onchange=\" validateStreetName() \" maxlength=\"100\" data-bind=\"value: StreetName" +
"\">\r\n                                                <span class=\"validationError" +
"\" id=\"validationStreetName\"></span>\r\n                                           " +
" </div>\r\n                                        </div>\r\n                       " +
"             </div>\r\n                                </div>\r\n\r\n                 " +
"               <div class=\"row\">\r\n                                    <div class" +
"=\"col-md-6\">\r\n                                        <div class=\"form-group\">\r\n" +
"                                            <label class=\"control-label col-md-6" +
"\">Area Name :<span class=\"required\">*</span></label>\r\n                          " +
"                  <div class=\"col-md-6\" data-bind=\"with: PartnerRegistrationAddr" +
"ess\">\r\n                                                <div>\r\n                  " +
"                                  <input type=\"text\" id=\"areaName\" name=\"\" class" +
"=\"form-control\" maxlength=\"100\" data-bind=\"value: AreaName\" onchange=\" validatea" +
"reaName() \">\r\n                                                    <span class=\"v" +
"alidationError\" id=\"validationAreaName\"></span>\r\n                               " +
"                 </div>\r\n                                            </div>\r\n   " +
"                                     </div>\r\n                                   " +
" </div>\r\n                                    <div class=\"col-md-6\">\r\n           " +
"                             <div class=\"form-group\">\r\n                         " +
"                   <label class=\"control-label col-md-6\">Town Or City :<span cla" +
"ss=\"required\">*</span></label>\r\n                                            <div" +
" class=\"col-md-6\" data-bind=\"with: PartnerRegistrationAddress\">\r\n               " +
"                                 <div>\r\n                                        " +
"            <input type=\"text\" id=\"townOrCity\" name=\"\" class=\"form-control\" maxl" +
"ength=\"50\" data-bind=\"value: TownOrCity\" onchange=\" validatetownOrCity() \">\r\n   " +
"                                                 <span class=\"validationError\" i" +
"d=\"validationTownOrCity\"></span>\r\n                                              " +
"  </div>\r\n                                            </div>\r\n                  " +
"                      </div>\r\n                                    </div>\r\n      " +
"                          </div>\r\n                                <div class=\"ro" +
"w\">\r\n                                    <div class=\"col-md-6\">\r\n               " +
"                         <div class=\"form-group\">\r\n                             " +
"               <label class=\"control-label col-md-6\">Zip Code:<span class=\"requi" +
"red\">*</span></label>\r\n                                            <div class=\"c" +
"ol-md-6\" data-bind=\"with: PartnerRegistrationAddress\">\r\n                        " +
"                        <div>\r\n                                                 " +
"   <input type=\"text\" id=\"zipCode\" name=\"\" class=\"form-control\" maxlength=\"6\" da" +
"ta-bind=\"value: ZipCode, event: { keypress: $root.validationHelper.ValidateNumer" +
"ic }\" onchange=\" validatezipCode() \">\r\n                                         " +
"           <span class=\"validationError\" id=\"validationZipCode\"></span>\r\n       " +
"                                         </div>\r\n                               " +
"             </div>\r\n                                        </div>\r\n           " +
"                         </div>\r\n                                    <div class=" +
"\"col-md-6\">\r\n                                        <div class=\"form-group\">\r\n " +
"                                           <label class=\"control-label col-md-6\"" +
">Country :<span class=\"required\">*</span></label>\r\n                             " +
"               <div class=\"col-md-6\" data-bind=\"with: PartnerRegistrationAddress" +
"\">\r\n                                                <div>\r\n                     " +
"                               <select id=\"ddlCountry\" name=\"\" class=\"form-contr" +
"ol\" data-bind=\"options: $root.Countries, optionsText: \'CountryName\', optionsCapt" +
"ion: \'Select...\', optionsValue: \'CountryCode\', value: Country, event: { change: " +
"$root.SelectStates }\" onchange=\" validateCountry() \"></select>\r\n                " +
"                                    <span class=\"validationError\" id=\"validation" +
"Country\"></span>\r\n                                                </div>\r\n      " +
"                                      </div>\r\n                                  " +
"      </div>\r\n                                    </div>\r\n\r\n                    " +
"            </div>\r\n                                <div class=\"row\">\r\n         " +
"                           <div class=\"col-md-6\">\r\n                             " +
"           <div class=\"form-group\">\r\n                                           " +
" <label class=\"control-label col-md-6\">State :<span class=\"required\">*</span></l" +
"abel>\r\n                                            <div class=\"col-md-6\" data-bi" +
"nd=\"with: PartnerRegistrationAddress\">\r\n                                        " +
"        <div>\r\n                                                    <select id=\"d" +
"dlState\" name=\"\" class=\"form-control\" data-bind=\"options: $root.States, optionsT" +
"ext: \'StateName\', optionsCaption: \'Select...\', optionsValue: \'StateCode\', value:" +
" State\" onchange=\" validateState() \"></select>\r\n                                " +
"                    <span class=\"validationError\" id=\"validationState\"></span>\r\n" +
"                                                </div>\r\n                        " +
"                    </div>\r\n                                        </div>\r\n    " +
"                                </div>\r\n                                    <div" +
" class=\"col-md-6\">\r\n                                        <div class=\"form-gro" +
"up\">\r\n                                            <label class=\"control-label co" +
"l-md-6\">Status :<span class=\"required\">*</span></label>\r\n\r\n\r\n\r\n                 " +
"                           <div class=\"col-md-6\">\r\n                             " +
"                   <div>\r\n                                                    <s" +
"elect id=\"ddlStatus\" name=\"\" class=\"form-control\" data-bind=\"options: $root.Stat" +
"usList, optionsCaption: \'Select...\',\r\n    value: Status\">\r\n                     " +
"                               </select>\r\n                                      " +
"              <span class=\"validationError\" data-bind=\"validationMessage: Status" +
"\"></span>\r\n                                                </div>\r\n             " +
"                               </div>\r\n                                        <" +
"/div>\r\n                                    </div>\r\n\r\n\r\n                         " +
"       </div>\r\n\r\n                                <div class=\"row\">\r\n            " +
"                        <div class=\"col-md-6\">\r\n                                " +
"        <div class=\"form-group\">\r\n                                            <l" +
"abel class=\"control-label col-md-6\">Corporate Indentification Number (CIN) (in c" +
"ase of company / LLP):<span class=\"required\">*</span></label>\r\n                 " +
"                           <div class=\"col-md-6\">\r\n                             " +
"                   <div>\r\n                                                    <i" +
"nput type=\"text\" id=\"txtCIN\" name=\"\" class=\"form-control\" maxlength=\"21\" data-bi" +
"nd=\"value: CIN, event: { keypress: $root.validationHelper.ValidateNumeric, chang" +
"e: $root.CheckUniqueCIN }\">\r\n\r\n                                                 " +
"   <span class=\"validationError\" data-bind=\"validationMessage: CIN\"></span>\r\n   " +
"                                             </div>\r\n                           " +
"                 </div>\r\n                                        </div>\r\n       " +
"                             </div>\r\n\r\n                                    <div " +
"class=\"col-md-6\">\r\n                                        <div class=\"form-grou" +
"p\">\r\n                                            <label class=\"control-label col" +
"-md-6\">Establishment Regn. No.:<span class=\"required\">*</span></label>\r\n        " +
"                                    <div class=\"col-md-6\">\r\n                    " +
"                            <div>\r\n                                             " +
"       <input type=\"text\" id=\"registrationNo\" name=\"\" class=\"form-control\" maxle" +
"ngth=\"8\" data-bind=\"value: RegistrationNo, event: { keypress: $root.validationHe" +
"lper.ValidateAlphaNumeric, change: $root.CheckUniqueRegistrationNo }\">\r\n        " +
"                                            <span class=\"validationError\" data-b" +
"ind=\"validationMessage: RegistrationNo\"></span>\r\n                               " +
"                 </div>\r\n                                            </div>\r\n   " +
"                                     </div>\r\n                                   " +
" </div>\r\n                                </div>\r\n                               " +
" <div class=\"row\">\r\n                                    <div class=\"col-md-6\">\r\n" +
"                                        <div class=\"form-group\">\r\n              " +
"                              <label class=\"control-label col-md-6\">Permanent Ac" +
"count Number (PAN):<span class=\"required\">*</span></label>\r\n                    " +
"                        <div class=\"col-md-6\">\r\n                                " +
"                <div>\r\n                                                    <inpu" +
"t type=\"text\" style=\"text-transform: uppercase\" id=\"txtPAN\" name=\"\" class=\"form-" +
"control\" maxlength=\"10\" data-bind=\"value: PAN, event: { keypress: $root.validati" +
"onHelper.ValidateAlphaNumeric, change: $root.CheckUniquePAN }\" onchange=\"validat" +
"ePAN()\">\r\n                                                    <span class=\"valid" +
"ationError\" id=\"validationPAN\"></span>\r\n                                        " +
"        </div>\r\n                                            </div>\r\n            " +
"                            </div>\r\n                                    </div>\r\n" +
"\r\n                                    <div class=\"col-md-6\">\r\n                  " +
"                      <div class=\"form-group\">\r\n                                " +
"            <label class=\"control-label col-md-6\">Registration Place:<span class" +
"=\"required\">*</span></label>\r\n                                            <div c" +
"lass=\"col-md-6\">\r\n                                                <div>\r\n       " +
"                                             <input type=\"text\" id=\"txtPlace\" na" +
"me=\"\" class=\"form-control\" maxlength=\"15\" data-bind=\"value: Place, event: { keyp" +
"ress: $root.validationHelper.ValidateAlphaNumericWithSpaces_keypressEvent }\">\r\n\r" +
"\n                                                    <span class=\"validationErro" +
"r\" data-bind=\"validationMessage: Place\"></span>\r\n                               " +
"                 </div>\r\n                                            </div>\r\n   " +
"                                     </div>\r\n                                   " +
" </div>\r\n                                </div>\r\n                               " +
" <div class=\"row\">\r\n                                    <div class=\"col-md-6\">\r\n" +
"                                        <div class=\"form-group\">\r\n              " +
"                              <label class=\"control-label col-md-6\">Tax Deductio" +
"n & Collection Account Number (TAN):<span class=\"required\">*</span></label>\r\n   " +
"                                         <div class=\"col-md-6\">\r\n               " +
"                                 <div>\r\n                                        " +
"            <input type=\"text\" id=\"txtTAN\" style=\"text-transform: uppercase\" nam" +
"e=\"\" class=\"form-control\" maxlength=\"10\" data-bind=\"value: TAN, event: { keypres" +
"s: $root.validationHelper.ValidateAlphaNumeric, change: $root.CheckUniqueTAN }\">" +
"\r\n                                                    <span class=\"validationErr" +
"or\" data-bind=\"validationMessage: TAN\"></span>\r\n                                " +
"                </div>\r\n                                            </div>\r\n    " +
"                                    </div>\r\n                                    " +
"</div>\r\n\r\n                                    <div class=\"col-md-6\">\r\n          " +
"                              <div class=\"form-group\">\r\n                        " +
"                    <label class=\"control-label col-md-6\">Service Tax / VAT Regn" +
". No.:<span class=\"required\">*</span></label>\r\n                                 " +
"           <div class=\"col-md-6\">\r\n                                             " +
"   <div>\r\n                                                    <input type=\"text\"" +
" id=\"txtVAT\" name=\"\" class=\"form-control\" maxlength=\"11\" data-bind=\"value: VAT, " +
"event: { keypress: $root.validationHelper.ValidateNumeric, change: $root.CheckUn" +
"iqueVAT }\">\r\n                                                    <span class=\"va" +
"lidationError\" data-bind=\"validationMessage: VAT\"></span>\r\n                     " +
"                           </div>\r\n                                            <" +
"/div>\r\n                                        </div>\r\n                         " +
"           </div>\r\n                                </div>\r\n                     " +
"           <div class=\"row\">\r\n                                    <div class=\"co" +
"l-md-6\">\r\n                                        <div class=\"form-group\">\r\n    " +
"                                        <label class=\"control-label col-md-6\">Na" +
"ture of Business:<span class=\"required\">*</span></label>\r\n                      " +
"                      <div class=\"col-md-6\" >\r\n                                 " +
"               <div>\r\n                                                    <input" +
" type=\"text\" id=\"txtNatureOfBusiness\" name=\"\" class=\"form-control\" maxlength=\"20" +
"\" data-bind=\"value: NatureOfBusiness, event: { keypress: $root.validationHelper." +
"ValidateAlphabetsWithSpaces_keypressEvent }\">\r\n                                 " +
"                   <span class=\"validationError\" data-bind=\"validationMessage: N" +
"atureOfBusiness\"></span>\r\n                                                </div>" +
"\r\n                                            </div>\r\n                          " +
"              </div>\r\n                                    </div>\r\n\r\n            " +
"                         <div class=\"col-md-6\">\r\n                               " +
"         <div class=\"form-group\">\r\n                                            <" +
"label class=\"control-label col-md-6\">Email Id:<span class=\"required\">*</span></l" +
"abel>\r\n                                            <div class=\"col-md-6\" data-bi" +
"nd=\"with: PartnerRegistrationAddress\">\r\n                                        " +
"        <div>\r\n                                                     <input type=" +
"\"text\" id=\"PartnerEmailId\" name=\"\" class=\"form-control\" data-bind=\"value: Email," +
" event: { keypress: $root.validationHelper.ValidateAlphanumericEmail }\" maxlengt" +
"h=\"254\" onchange=\"validatePartnerEmail()\" >\r\n                                   " +
"                 <span class=\"validationError\" id=\"validationPartnerEmail\"></spa" +
"n>\r\n                                                </div>\r\n                    " +
"                        </div>\r\n                                        </div>\r\n" +
"                                    </div>\r\n                                </di" +
"v>\r\n                                <div class=\"row\">\r\n                         " +
"           <div class=\"row\">\r\n                                        <div class" +
"=\"col-md-6\">\r\n                                            <div class=\"row form-g" +
"roup\">\r\n                                                <label class=\"control-la" +
"bel col-md-6\">Logo :<span class=\"required\">&nbsp;&nbsp;</span></label>\r\n        " +
"                                        <div class=\"col-md-6\" style=\"border: 1px" +
" solid #ccc; border-radius: 5px;\">\r\n                                            " +
"        <table style=\"width: 100%; height: 20px;\">\r\n                            " +
"                            <tr>\r\n                                              " +
"              <td>\r\n                                                            " +
"    <img id=\"sigImage\" src=\"#\" height=\"60\" data-bind=\"visible: (PartnerRegistrat" +
"ionAddress().LogoPath() != \'\' && PartnerRegistrationAddress().LogoPath() != null" +
")\">\r\n                                                                <span class" +
"=\"validationError\" id=\"validationLogo\"></span>\r\n                                " +
"                            </td>\r\n                                             " +
"           </tr>\r\n                                                    </table>\r\n" +
"                                                </div>\r\n                        " +
"                    </div>\r\n\r\n                                            <div c" +
"lass=\"row\">\r\n                                                <div class=\"col-md-" +
"12\">\r\n                                                    <label class=\"control-" +
"label col-md-6\"></label>\r\n                                                    <d" +
"iv class=\"col-md-6\">\r\n                                                        <s" +
"pan style=\"color: red\">Preferred Dimensions : 90 X 30</span>\r\n                  " +
"                                  </div>\r\n                                      " +
"          </div>\r\n                                            </div>\r\n          " +
"                                  <div class=\"row\">\r\n                           " +
"                     <label class=\"control-label col-md-6\"></label>\r\n           " +
"                                     <div class=\"col-md-6\">\r\n                   " +
"                                 <table>\r\n                                      " +
"                  <tbody data-bind=\"with: PartnerRegistrationAddress\">\r\n        " +
"                                                    <tr>\r\n                      " +
"                                          <td data-bind=\"visible: (LogoPath() !=" +
" \'\' && LogoPath() != null)\">\r\n                                                  " +
"                  <a href=\"\" id=\"fileNameLink\" data-bind=\"attr: { href: applicat" +
"ion.viewbag.appSettings.uamapiUrl + \'/FileUploads/Logo/\' + LogoPath() }\" target=" +
"\"_blank\"><span data-bind=\"    text: LogoFileName\"></span></a>\r\n\r\n               " +
"                                                 </td>\r\n                        " +
"                                    </tr>\r\n\r\n                                   " +
"                     </tbody>\r\n                                                 " +
"   </table>\r\n                                                </div>\r\n           " +
"                                 </div>\r\n\r\n                                     " +
"       <div class=\"row\">\r\n                                                <label" +
" class=\"control-label col-md-6\"></label>\r\n                                      " +
"          <div class=\"col-md-6\">\r\n                                              " +
"      <div class=\"fileupload-buttonbar\">\r\n                                      " +
"                  <div class=\"form-group\">\r\n                                    " +
"                        <div class=\"col-md-6\" data-bind=\"visible: $parent.IsUplo" +
"ad\">\r\n                                                                <span clas" +
"s=\"btn btn-xs green fileinput-button\">\r\n                                        " +
"                            <i class=\"fa fa-plus\"></i>\r\n                        " +
"                                            <span data-bind=\"visible: $parent.Is" +
"Upload\">Browse\r\n                                                                " +
"    </span>\r\n                                                                   " +
" <input type=\"file\" class=\"upload\" name=\"files[]\" id=\"fileToUpload\" multiple />\r" +
"\n                                                                </span>\r\n      " +
"                                                          <button type=\"button\" " +
"id=\"CapturePicture\" data-icon=\"upload\" data-role=\"button\" data-bind=\"click: $roo" +
"t.uploadFile, visible: $root.IsUpload\" class=\"btn btn-xs blue start\">\r\n         " +
"                                                           <i class=\"fa fa-uploa" +
"d\"></i>\r\n                                                                    <sp" +
"an>Upload\r\n                                                                    <" +
"/span>\r\n\r\n                                                                </butt" +
"on>\r\n                                                            </div>\r\n       " +
"                                                 </div>\r\n                       " +
"                             </div>\r\n                                           " +
"     </div>\r\n                                            </div>\r\n               " +
"                         </div>\r\n                                    </div>\r\n   " +
"                             </div>\r\n                            </fieldset>\r\n\r\n" +
"\r\n\r\n\r\n                            <fieldset>\r\n                                <l" +
"egend>Details of Directors/Partners/Promoters</legend>\r\n                        " +
"        <div class=\"row\">\r\n                                    <div class=\"table" +
"-toolbar\">\r\n                                        <div id=\"tableheader\">\r\n    " +
"                                        <a class=\"button gbtngreen\" id=\"btnAddNe" +
"w\" data-bind=\"click: $root.AddNewDetails\"><i class=\"fa fa-plus\"></i>Add New</a>\r" +
"\n                                        </div>\r\n                               " +
"         <div class=\"table-scrollable\">\r\n                                       " +
"     <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" id=\"tblmovementsdetails\" " +
"class=\"table tinytable\">\r\n                                                <thead" +
">\r\n                                                    <tr>\r\n                   " +
"                                     <th>Action</th>\r\n                          " +
"                              <th>Name</th>\r\n                                   " +
"                     <th>Permanent Account Number (PAN)</th>\r\n                  " +
"                                      <th>Address</th>\r\n                        " +
"                                <th>Mobile</th>\r\n                               " +
"                         <th>Telephone</th>\r\n                                   " +
"                     <th>Email</th>\r\n                                           " +
"         </tr>\r\n                                                </thead>\r\n      " +
"                                          <tbody data-bind=\"foreach: PartnerDire" +
"ctorDetailss\">\r\n                                                    <tr data-bin" +
"d=\"css: { trhighlight: ErrorStatus() }\">\r\n                                      " +
"                  <td style=\"text-align: center;\">\r\n                            " +
"                                <a href=\'#\' id=\"btnRemove\" data-bind=\'click: $ro" +
"ot.RemoveDetails\' title=\"Delete\"><i class=\"fa fa-ban ban-before\"></i></a>\r\n     " +
"                                                   </td>\r\n                      " +
"                                  <td>\r\n                                        " +
"                    <input type=\"text\" class=\"form-control\" maxlength=\"20\" data-" +
"bind=\"value: PDirectorName, event: { keypress: $root.validationHelper.ValidateAl" +
"phabetsWithSpaces_keypressEvent }\"></td>\r\n                                      " +
"                  <td>\r\n                                                        " +
"    <input type=\"text\" class=\"form-control\" style=\"text-transform: uppercase\" ma" +
"xlength=\"10\" data-bind=\"value: PDirectorPAN, event: { keypress: $root.validation" +
"Helper.ValidateAlphaNumeric }\"></td>\r\n                                          " +
"              <td>\r\n                                                            " +
"<textarea class=\"form-control\" style=\"resize: none;\" rows=\"1\" data-bind=\"value: " +
"PDirectorAddress, event: { keypress: $root.validationHelper.ValidateAlphabetsWit" +
"hSpaces_keypressEvent }\"></textarea></td>\r\n                                     " +
"                   <td>\r\n                                                       " +
"     <input type=\"text\" class=\"form-control\" maxlength=\"15\" data-bind=\"value: PD" +
"irectorMobile, event: { keypress: $root.validationHelper.ValidateNumeric }, attr" +
": { id: \'pDirectorMobile\' + $index() }\"></td>\r\n                                 " +
"                       <td>\r\n                                                   " +
"         <input type=\"text\" class=\"form-control\" maxlength=\"11\" data-bind=\"value" +
": PDirectorTele, event: { keypress: $root.validationHelper.ValidateNumeric }\"></" +
"td>\r\n                                                        <td>\r\n             " +
"                                               <input type=\"text\" id=\"emailId\" n" +
"ame=\"\" class=\"form-control\" data-bind=\"value: PDirectorEmail, event: { keypress:" +
" $root.validationHelper.ValidateAlphanumericEmail }\" maxlength=\"254\">\r\n         " +
"                                           </tr>\r\n\r\n                            " +
"                    </tbody>\r\n                                            </tabl" +
"e>\r\n                                        </div>\r\n                            " +
"        </div>\r\n\r\n                                </div>\r\n                      " +
"      </fieldset>\r\n                            <fieldset>\r\n                     " +
"           <legend>Bank Details</legend>\r\n                                <div c" +
"lass=\"row\">\r\n                                    <div class=\"col-md-6\">\r\n       " +
"                                 <div class=\"form-group\">\r\n                     " +
"                       <label class=\"control-label col-md-6\">Bank Name:<span cla" +
"ss=\"required\">*</span></label>\r\n                                            <div" +
" class=\"col-md-6\">\r\n                                                <input type=" +
"\"text\" name=\"\" class=\"form-control\" maxlength=\"20\" data-bind=\"value: BankName, e" +
"vent: { keypress: $root.validationHelper.ValidateAlphabetsWithSpaces_keypressEve" +
"nt }\">\r\n                                                <span class=\"validationE" +
"rror\" data-bind=\"validationMessage: BankName\"></span>\r\n                         " +
"                   </div>\r\n                                        </div>\r\n     " +
"                               </div>\r\n                                    <div " +
"class=\"col-md-6\">\r\n                                        <div class=\"form-grou" +
"p\">\r\n                                            <label class=\"control-label col" +
"-md-6\">Account No.:<span class=\"required\">*</span></label>\r\n                    " +
"                        <div class=\"col-md-6\">\r\n                                " +
"                <input type=\"text\" name=\"\" class=\"form-control\" maxlength=\"18\" d" +
"ata-bind=\"value: AccountNo, event: { keypress: $root.validationHelper.ValidateNu" +
"meric }\">\r\n                                                <span class=\"validati" +
"onError\" data-bind=\"validationMessage: AccountNo\"></span>\r\n\r\n                   " +
"                         </div>\r\n                                        </div>\r" +
"\n                                    </div>\r\n                                </d" +
"iv>\r\n\r\n                                <div class=\"row\">\r\n                      " +
"              <div class=\"col-md-6\">\r\n                                        <d" +
"iv class=\"form-group\">\r\n                                            <label class" +
"=\"control-label col-md-6\">Bank Address :<span class=\"required\">*</span></label>\r" +
"\n                                            <div class=\"col-md-6\">\r\n           " +
"                                     <textarea name=\"\" class=\"form-control\" maxl" +
"ength=\"40\" style=\"resize: none;\" data-bind=\"value: BankAddress, event: { keypres" +
"s: $root.validationHelper.ValidateAlphaNumericWithSpaces_keypressEvent }\"></text" +
"area>\r\n                                                <span class=\"validationEr" +
"ror\" data-bind=\"validationMessage: BankAddress\"></span>\r\n                       " +
"                     </div>\r\n                                        </div>\r\n   " +
"                                 </div>\r\n                                    <di" +
"v class=\"col-md-6\">\r\n                                        <div class=\"form-gr" +
"oup\">\r\n                                            <label class=\"control-label c" +
"ol-md-6\">IFSC Code :<span class=\"required\">*</span></label>\r\n                   " +
"                         <div class=\"col-md-6\">\r\n                               " +
"                 <input type=\"text\" name=\"\" class=\"form-control\" maxlength=\"11\" " +
"data-bind=\"value: IFSCCode, event: { keypress: $root.validationHelper.ValidateAl" +
"phaNumeric }\">\r\n\r\n                                                <span class=\"v" +
"alidationError\" data-bind=\"validationMessage: IFSCCode\"></span>\r\n               " +
"                             </div>\r\n                                        </d" +
"iv>\r\n                                    </div>\r\n                               " +
" </div>\r\n\r\n\r\n                            </fieldset>\r\n\r\n                        " +
"    <fieldset>\r\n                                <legend>Details of Representativ" +
"es</legend>\r\n                                <div class=\"row\">\r\n                " +
"                    <div class=\"col-md-6\">\r\n                                    " +
"    <h4>Finance</h4>\r\n                                        <div class=\"row\">\r" +
"\n\r\n                                            <div class=\"form-group\">\r\n       " +
"                                         <label class=\"control-label col-md-4\">N" +
"ame :<span class=\"required\">*</span></label>\r\n                                  " +
"              <div class=\"col-md-6\">\r\n                                          " +
"          <input type=\"text\" name=\"\" class=\"form-control\" maxlength=\"20\" data-bi" +
"nd=\"value: FinanceName, event: { keypress: $root.validationHelper.ValidateAlphab" +
"etsWithSpaces_keypressEvent }\">\r\n                                               " +
"     <span class=\"validationError\" data-bind=\"validationMessage: FinanceName\"></" +
"span>\r\n                                                </div>\r\n                 " +
"                           </div>\r\n\r\n                                        </d" +
"iv>\r\n                                        <div class=\"row\">\r\n\r\n              " +
"                              <div class=\"form-group\">\r\n                        " +
"                        <label class=\"control-label col-md-4\">Email :<span class" +
"=\"required\">*</span></label>\r\n                                                <d" +
"iv class=\"col-md-6\">\r\n                                                    <input" +
" type=\"text\" id=\"finEmail\" class=\"form-control\" data-bind=\"value: FinanceEmail, " +
"event: { keypress: $root.validationHelper.ValidateAlphanumericEmail }\" onchange=" +
"\" validateFinEmailId() \" maxlength=\"254\">\r\n                                     " +
"               <span class=\"validationError\" id=\"validationFinEmail\"></span>\r\n  " +
"                                              </div>\r\n                          " +
"                  </div>\r\n\r\n                                        </div>\r\n    " +
"                                    <div class=\"row\">\r\n\r\n                       " +
"                     <div class=\"form-group\">\r\n                                 " +
"               <label class=\"control-label col-md-4\">Mobile :<span class=\"requir" +
"ed\">*</span></label>\r\n                                                <div class" +
"=\"col-md-6\">\r\n                                                    <input type=\"t" +
"ext\" id=\"finMobile\" name=\"\" class=\"form-control\" maxlength=\"15\" data-bind=\"value" +
": FinanceMobile, event: { keypress: $root.validationHelper.ValidateNumeric }\" on" +
"change=\"validatefinNumber()\">\r\n                                                 " +
"   <span class=\"validationError\" id=\"validationfinMobile\"></span>\r\n             " +
"                                   </div>\r\n                                     " +
"       </div>\r\n\r\n                                        </div>\r\n               " +
"                     </div>\r\n                                    <div class=\"col" +
"-md-6\">\r\n                                        <h4>Operations</h4>\r\n          " +
"                              <div class=\"row\">\r\n\r\n                             " +
"               <div class=\"form-group\">\r\n                                       " +
"         <label class=\"control-label col-md-4\">Name :<span class=\"required\">*</s" +
"pan></label>\r\n                                                <div class=\"col-md" +
"-6\">\r\n                                                    <input type=\"text\" nam" +
"e=\"\" class=\"form-control\" maxlength=\"20\" data-bind=\"value: OperationsName, event" +
": { keypress: $root.validationHelper.ValidateAlphabetsWithSpaces_keypressEvent }" +
"\">\r\n                                                    <span class=\"validationE" +
"rror\" data-bind=\"validationMessage: OperationsName\"></span>\r\n                   " +
"                             </div>\r\n                                           " +
" </div>\r\n\r\n                                        </div>\r\n                     " +
"                   <div class=\"row\">\r\n\r\n                                        " +
"    <div class=\"form-group\">\r\n                                                <l" +
"abel class=\"control-label col-md-4\">Email :<span class=\"required\">*</span></labe" +
"l>\r\n                                                <div class=\"col-md-6\">\r\n    " +
"                                                <input type=\"text\" id=\"operation" +
"Email\" class=\"form-control\" data-bind=\"value: OperationsEmail, event: { keypress" +
": $root.validationHelper.ValidateAlphanumericEmail }\" onchange=\" validateOperati" +
"onEmail() \" maxlength=\"254\">\r\n                                                  " +
"  <span class=\"validationError\" id=\"validationOperationsEmail\"></span>\r\n        " +
"                                        </div>\r\n                                " +
"            </div>\r\n\r\n                                        </div>\r\n          " +
"                              <div class=\"row\">\r\n\r\n                             " +
"               <div class=\"form-group\">\r\n                                       " +
"         <label class=\"control-label col-md-4\">Mobile :<span class=\"required\">*<" +
"/span></label>\r\n                                                <div class=\"col-" +
"md-6\">\r\n                                                    <input type=\"text\" i" +
"d=\"operationMobile\" name=\"\" class=\"form-control\" maxlength=\"10\" data-bind=\"value" +
": OperationsMobile, event: { keypress: $root.validationHelper.ValidateNumeric }\"" +
" onchange=\"validateOperationMobile()\">\r\n                                        " +
"            <span class=\"validationError\" id=\"validationOperationMobile\"></span>" +
"\r\n                                                </div>\r\n                      " +
"                      </div>\r\n\r\n                                        </div>\r\n" +
"\r\n                                    </div>\r\n                                </" +
"div>\r\n                                <div class=\"row\">\r\n                       " +
"             <div class=\"col-md-6\">\r\n                                        <h4" +
">IT</h4>\r\n                                        <div class=\"row\">\r\n\r\n         " +
"                                   <div class=\"form-group\">\r\n                   " +
"                             <label class=\"control-label col-md-4\">Name :<span c" +
"lass=\"required\">*</span></label>\r\n                                              " +
"  <div class=\"col-md-6\">\r\n                                                    <i" +
"nput type=\"text\" name=\"\" maxlength=\"20\" class=\"form-control\" data-bind=\"value: I" +
"TName, event: { keypress: $root.validationHelper.ValidateAlphabetsWithSpaces_key" +
"pressEvent }\">\r\n                                                    <span class=" +
"\"validationError\" data-bind=\"validationMessage: ITName\"></span>\r\n               " +
"                                 </div>\r\n                                       " +
"     </div>\r\n\r\n                                        </div>\r\n                 " +
"                       <div class=\"row\">\r\n\r\n                                    " +
"        <div class=\"form-group\">\r\n                                              " +
"  <label class=\"control-label col-md-4\">Email :<span class=\"required\">*</span></" +
"label>\r\n                                                <div class=\"col-md-6\">\r\n" +
"                                                    <input type=\"text\" id=\"itEma" +
"il\" class=\"form-control\" data-bind=\"value: ITEmail, event: { keypress: $root.val" +
"idationHelper.ValidateAlphanumericEmail }\" onchange=\" validateITEmail() \" maxlen" +
"gth=\"254\">\r\n                                                    <span class=\"val" +
"idationError\" id=\"ValidationiTEmail\"></span>\r\n                                  " +
"              </div>\r\n                                            </div>\r\n\r\n    " +
"                                    </div>\r\n                                    " +
"    <div class=\"row\">\r\n\r\n                                            <div class=" +
"\"form-group\">\r\n                                                <label class=\"con" +
"trol-label col-md-4\">Mobile :<span class=\"required\">*</span></label>\r\n          " +
"                                      <div class=\"col-md-6\">\r\n                  " +
"                                  <input type=\"text\" id=\"iTMobile\" name=\"\" class" +
"=\"form-control\" maxlength=\"10\" data-bind=\"value: ITMobile, event: { keypress: $r" +
"oot.validationHelper.ValidateNumeric }\" onchange=\"validateITMobile()\">\r\n        " +
"                                            <span class=\"validationError\" id=\"va" +
"lidationiTMobile\"></span>\r\n                                                </div" +
">\r\n                                            </div>\r\n\r\n                       " +
"                 </div>\r\n                                    </div>\r\n           " +
"                         <div class=\"col-md-6\"></div>\r\n                         " +
"       </div>\r\n                            </fieldset>\r\n\r\n\r\n\r\n                  " +
"          <fieldset>\r\n                                <legend>Documents Upload (" +
"All documents to be self attested with Company Seal)</legend>\r\n\r\n               " +
"                 <div class=\"row\">\r\n                                    <div cla" +
"ss=\"col-md-6\">\r\n                                        <div class=\"form-group\">" +
"\r\n                                            <label class=\"control-label col-md" +
"-3\">Document Type:<span class=\"required\">*</span></label>\r\n                     " +
"                       <div class=\"col-md-9\">\r\n                                 " +
"               <select id=\"ddlDoctype\" name=\"\" class=\"form-control\" data-bind=\"o" +
"ptions: $root.DocumentList, optionsCaption: \'Select...\', value: DocumentType\"></" +
"select>\r\n                                                <span class=\"validation" +
"Error\" data-bind=\"validationMessage: DocumentType\"></span>\r\n                    " +
"                        </div>\r\n                                        </div>\r\n" +
"                                    </div>\r\n                                    " +
"<div class=\"col-md-3\">\r\n                                        <div class=\"form" +
"-group\">\r\n                                            <label class=\"control-labe" +
"l col-md-6\">Valid Till:<span class=\"required\">*</span></label>\r\n                " +
"                            <div class=\"col-md-6\">\r\n\r\n                          " +
"                      <input type=\"text\" style=\"border-width: 1px\" id=\"validTill" +
"\" class=\"form-control date-picker\" onkeydown=\"\" data-bind=\"value: ValidTill\" max" +
"length=\"12\" />\r\n                                                <span class=\"val" +
"idationError\" data-bind=\"validationMessage: ValidTill\"></span>\r\n                " +
"                            </div>\r\n                                        </di" +
"v>\r\n                                    </div>\r\n                                " +
"</div>\r\n                                <div class=\"portlet box advbg\">\r\n       " +
"                             <div class=\"portlet-title\">\r\n                      " +
"                  <div class=\"caption\">\r\n                                       " +
"     Uploaded Files\r\n                                        </div>\r\n           " +
"                             <div class=\"tools\">\r\n                              " +
"              <a href=\"javascript:;\" class=\"collapse\"></a>\r\n                    " +
"                    </div>\r\n                                    </div>\r\n        " +
"                            <div class=\"portlet-body\">\r\n                        " +
"                <div class=\"row\">\r\n                                            <" +
"div>\r\n                                                <div class=\"col-md-2\">\r\n  " +
"                                                  <input id=\"btnFileUpload\" clas" +
"s=\"btn btn\" data-bind=\"kendoUpload: {\r\n    async: {\r\n        saveUrl: \'/api/Mult" +
"ipleFileUpload/DocType_Copy/\' + \'");

            
            #line 661 "..\..\Views\PartnerRegistration\PartnerRegistration.cshtml"
                                                       Write(Html.Encode(User.Identity.Name));

            
            #line default
            #line hidden
WriteLiteral("    \',\r\n        autoUpload: true\r\n    }, localization: {\r\n        select: \'Upload" +
" Document\', dropFilesHere: \'\'\r\n    }, enabled: $root.IsbuttonsEnable, multiple: " +
"false, select: SelectFile, upload: $root.Upload, success: $root.FileSuccess,\r\n  " +
"  showFileList: false\r\n}\"type=\"file\" multiple=\"multiple\"/>\r\n                    " +
"                            </div>\r\n                                            " +
"    <div class=\"col-md-10\" style=\"margin-top: 13px;\">\r\n                         " +
"                           <span>\r\n                                             " +
"           <label class=\"text text-danger\"><i class=\"fa fa-info-circle\"></i>Plea" +
"se upload [ .pdf, .jpg, .jpeg, .bmp, .gif, .png, .csv , .docx, .doc, .xlsx, .xls" +
" ] files only</label></span>\r\n                                                </" +
"div>\r\n                                                <div style=\"height: 5px;\">" +
"</div>\r\n                                                <div class=\"row\">\r\n     " +
"                                               <div class=\"table-responsive\">\r\n " +
"                                                       <table class=\"tinytable\">" +
"\r\n                                                            <thead>\r\n         " +
"                                                       <tr>\r\n                   " +
"                                                 <th class=\"bg-dark font-color1\"" +
" style=\"width: 50px;\">S.No.</th>\r\n                                              " +
"                      <th class=\"bg-dark font-color1\">Document Name</th>\r\n      " +
"                                                              <th class=\"bg-dark" +
" font-color1\">Document Type</th>\r\n                                              " +
"                      <th class=\"bg-dark font-color1\" style=\"width: 100px;\">Vali" +
"d Till</th>\r\n                                                                   " +
" <th class=\"bd-dark font-color1\" style=\"width: 100px;\">Action</th>\r\n\r\n          " +
"                                                      </tr>\r\n                   " +
"                                         </thead>\r\n                             " +
"                               <tbody data-bind=\"foreach: DocumentDTOs\">\r\n      " +
"                                                          <tr>\r\n                " +
"                                                    <td data-bind=\"text: $index(" +
") + 1\" style=\"text-align: center;\"></td>\r\n                                      " +
"                              <td><a data-bind=\"text: OriginalName, attr: { href" +
": \'/FileUploads/\' + FileName() }\" target=\"_blank\" style=\"text-decoration: underl" +
"ine;\"></a></td>\r\n                                                               " +
"     <td data-bind=\"text: DocumentType\" style=\"text-align: center;\"></td>\r\n     " +
"                                                               <td data-bind=\"te" +
"xt: ValidTill\" style=\"text-align: center;\"></td>\r\n                              " +
"                                      <td style=\"text-align: center;\">\r\n        " +
"                                                                <a href=\"#\" titl" +
"e=\"Remove\" data-bind=\"click: $root.RemoveDocument, visible: IsCurrentdoc() == \'Y" +
"\'\"><i class=\"fa fa-ban ban-before\"></i></a>\r\n                                   " +
"                                 </td>\r\n                                        " +
"                        </tr>\r\n                                                 " +
"           </tbody>\r\n                                                        </t" +
"able>\r\n                                                    </div>\r\n             " +
"                                   </div>\r\n\r\n\r\n                                 " +
"           </div>\r\n                                        </div>\r\n             " +
"                       </div>\r\n                                </div>\r\n\r\n\r\n\r\n   " +
"                         </fieldset>\r\n\r\n                            <div class=\"" +
"row\">\r\n                                <div class=\"col-md-1\" align=\"right\">\r\n   " +
"                                 <input class=\"k-header k-with-icon k-filterable" +
"\" type=\'Checkbox\' data-bind=\"checked: IsAccept\" />\r\n                            " +
"    </div>\r\n                                <div class=\"col-md-11\">I / We hereby" +
" declare that the above stated information is tru and correct and will be held l" +
"iable for any omission, incorrect, incomplete of misdeclaration to herein above." +
" We undertake to keep your office informed of any changes to the above details a" +
"nd re-submit the relevant documents along with revised KYC Form</div>\r\n         " +
"                   </div>\r\n                            <div class=\"row\">&nbsp;</" +
"div>\r\n\r\n\r\n                            <div class=\"btns-group form-actions fluid\"" +
">\r\n                                <input type=\"button\" value=\"Save\" class=\"btn " +
"green\" data-bind=\"click: $root.SaveScreen\" />\r\n                                ");

WriteLiteral(@"
                                <button type=""submit"" class=""btn blue"" data-bind=""click: $root.ResetScreen"">Reset</button>
                                <button type=""submit"" class=""btn default button-previous"" data-bind=""click: $root.ExitScreen""><i class=""m-icon-swapleft""></i>Back</button>
                            </div>
                        </div>



                    </div>



                </div>
            </div>


        </div>
    </div>
</script>
");

        }
    }
}
#pragma warning restore 1591
