#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ChangePassword.cshtml")]
    public partial class _Views_Account_ChangePassword_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Account_ChangePassword_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Account\ChangePassword.cshtml"
  
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_eGateLayout.cshtml";

    var IsFirstTimeLogin = "N";

    if (!string.IsNullOrEmpty(ViewBag.IsFirstTimeLogin))
    {
        IsFirstTimeLogin = ViewBag.IsFirstTimeLogin;

    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 291), Tuple.Create("\"", 325)
, Tuple.Create(Tuple.Create("", 297), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Lib/angular.min.js")
, 297), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 345), Tuple.Create("\"", 401)
, Tuple.Create(Tuple.Create("", 351), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/Model/ChangePasswordModel.js")
, 351), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 421), Tuple.Create("\"", 485)
, Tuple.Create(Tuple.Create("", 427), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/ViewModel/ChangePasswordViewModel.js")
, 427), false)
);

WriteLiteral("></script>\r\n");

});

DefineSection("ko_apply", () => {

WriteLiteral("\r\n    var viewModel = new eGateRoot.ChangePasswordViewModel(\"");

            
            #line 21 "..\..\Views\Account\ChangePassword.cshtml"
                                                      Write(IsFirstTimeLogin);

            
            #line default
            #line hidden
WriteLiteral("\");\t \r\n    ko.applyBindingsWithValidation(viewModel, $(\"#ChangePassword\")[0], { i" +
"nsertMessages: false, messagesOnModified: false, grouping: { deep: true }});\r\n");

});

WriteLiteral("\r\n<style>\r\n    .input-help {\r\n        display: none;\r\n        /*position:absolute" +
";*/\r\n        z-index: 100;\r\n        top: -27px;\r\n        left: -200px;\r\n        " +
"width: 300px;\r\n        padding: 8px;\r\n        background: #fefefe;\r\n        font" +
"-size: .875em;\r\n        border-radius: 5px;\r\n        box-shadow: 0 1px 3px #aaa;" +
"\r\n        border: 1px solid #ddd;\r\n        opacity: 0.9;\r\n    }\r\n\r\n        .inpu" +
"t-help::before {\r\n            content: \"\\25C0\";\r\n            /*position: absolut" +
"e;*/\r\n            top: 10px;\r\n            left: -12px;\r\n            font-size: 1" +
"6px;\r\n            line-height: 16px;\r\n            color: #ddd;\r\n            text" +
"-shadow: none;\r\n        }\r\n\r\n        .input-help h4 {\r\n            margin: 0;\r\n " +
"           padding: 0;\r\n            font-weight: normal;\r\n            font-size:" +
" 1.1em;\r\n        }\r\n\r\n    /* Always hide the input help when it\'s pristine */\r\n " +
"   input.ng-pristine + .input-help {\r\n        display: none;\r\n    }\r\n\r\n    /* Hi" +
"de the invalid box while the input has focus */\r\n    .ng-invalid:focus + .input-" +
"help {\r\n        display: none;\r\n    }\r\n\r\n    /* Show a blue border while an inpu" +
"t has focus, make sure it overrides everything else */\r\n    /* Overriding Twitte" +
"r Bootstrap cuz I don\'t agree we need to alarm the user while they\'re typing */\r" +
"\n    input:focus {\r\n        color: black !important;\r\n        border-color: rgba" +
"(82, 168, 236, 0.8) !important;\r\n        -webkit-box-shadow: inset 0 1px 1px rgb" +
"a(0, 0, 0, 0.075), 0 0 8px rgba(82, 168, 236, 0.6) !important;\r\n        -moz-box" +
"-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(82, 168, 236, 0.6) !" +
"important;\r\n        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rg" +
"ba(82, 168, 236, 0.6) !important;\r\n    }\r\n\r\n\r\n    /* Show green border when stuf" +
"f has been typed in, and its valid */\r\n    .ng-dirty.ng-valid {\r\n        border-" +
"color: #3a7d34;\r\n    }\r\n\r\n    /* Show red border when stuff has been typed in, b" +
"ut its invalid */\r\n    .ng-dirty.ng-invalid {\r\n        border-color: #ec3f41;\r\n " +
"   }\r\n\r\n    .immediate-help {\r\n        display: block;\r\n        width: 20%;\r\n   " +
"     font-size: 13px;\r\n        color: #555;\r\n        vertical-align: middle;\r\n  " +
"      background-color: white;\r\n        background-image: none;\r\n        border-" +
"radius: 4px;\r\n    }\r\n\r\n        /* Show the help box once it has focus */\r\n      " +
"  .immediate-help:focus + .input-help {\r\n            position: relative;\r\n      " +
"      margin-left: 450px;\r\n            display: block;\r\n        }\r\n\r\n        /* " +
"Immediate help should be red when pristine */\r\n        .immediate-help.ng-pristi" +
"ne:focus + .input-help {\r\n            border-color: #ec3f41;\r\n        }\r\n\r\n     " +
"       .immediate-help.ng-pristine:focus + .input-help::before {\r\n              " +
"  color: #ec3f41;\r\n            }\r\n    .input-help::before {display:none;\r\n    }\r" +
"\n\r\n    /* Help hould be green when input is valid */\r\n    .ng-valid + .input-hel" +
"p {\r\n        border-color: #3a7d34;\r\n    }\r\n\r\n        .ng-valid + .input-help::b" +
"efore {\r\n            color: #3a7d34;\r\n        }\r\n\r\n    /* Help should show and b" +
"e red when invalid */\r\n    .ng-invalid + .input-help {\r\n        display: block;\r" +
"\n        /*position:relative;*/\r\n        /*margin-left: 450px;*/\r\n        border" +
"-color: #ec3f41;\r\n    }\r\n\r\n        .ng-invalid + .input-help::before {\r\n        " +
"    color: #ec3f41;\r\n        }\r\n\r\n    /* Style input help requirement bullets */" +
"\r\n    .input-help ul {\r\n        list-style: none;\r\n        margin: 10px 0 0 0;\r\n" +
"    }\r\n\r\n    /* Default each bullet to be invalid with a red cross and text */\r\n" +
"    .input-help li {\r\n        padding-left: 22px;\r\n        line-height: 24px;\r\n " +
"       color: #ec3f41;\r\n        background: url(data:image/png;base64,iVBORw0KGg" +
"oAAAANSUhEUgAAABAAAAA1CAYAAABIkmvkAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAJwAAACcBKg" +
"mRTwAAABZ0RVh0Q3JlYXRpb24gVGltZQAxMC8wOS8xMlhq+BkAAAAcdEVYdFNvZnR3YXJlAEFkb2JlIE" +
"ZpcmV3b3JrcyBDUzVxteM2AAAEA0lEQVRIie2WW2jbVRzHv//zT5rkn0ub61zaNdEiPqTC9EFRhtgJk6" +
"3qg3Wr0806pswNiYgDUXxwyryCEB8UBevtaSCCDHQoboKyoVvVzfRmL2napU0mrdbl8s//dy4+dM1M28" +
"n64FsPnIdz+XzO75zfOXA0pRRWU7o/uS9FxOc+3/vlIQBgq4F3fHxvKuIPJ9cFwi9uTXU8BwDa1Uaw/a" +
"N7UusCkWRbPI5yxcTI2Bgy49kXrkrwwIedqYg/nGyLXwsJiYHBYWTGs7Cq5Kpt4cA3PXft+2rX40vhrt" +
"7OVLgplIzHYuBKoH9gCKMjGVE1LdfJl86YDAAOfN2ziZP4NODyv9/z2fanFuH7P9iWCjcFk/FYK4QSGL" +
"gEk0WeUy/3mQCgPXFs9xbBRW883NrssDvQN3hWcOLPEPGWiD94MBaPQymBoaERjI9mBSfu+fHwL+biIt" +
"pjR3e6JFfloDeAaGQ9SpUycvlp6ExHJBKGYsDvgyMYH81KTsL90yuX4VoWdh3pMqSQpWBjAC3RZkgpYE" +
"kCFDA8NIqJ0UlFxI3Tr/5aB9elsau305BcloKBAFpjLeBSYGRwDBNjk4oTN06/dnYZXCcAgK1vbzYkl6" +
"VwOATihOzYlOLEjTOvn1sRXiYAgDsP32YIKUuWaXFOwtP3xrnqleAVBQBwy/M3GZy4+PnN3/4TvqJgNW" +
"VVj2lNsCZYE6wJ1gRrgv9dYAMAHHw2Bl2fUEpBVavtLPVW/78nVR/Zk4CupzVHA6zChSOK0yHv0S8GFy" +
"K4BMPhAJxOgLE03/9kYhE2dz+agKaldY8bDaEQ7D5ft7Roy+UIlCooy5LQdaZ5vVBEgGmmrT172yVxaI" +
"ylmdcDm9cHc2oK1Zm8kETvLAo0pRRk8mmnEqKouVw68zVCzP8F/uccFHHoXi/sjT6Y53Mw83mhOHn8J7" +
"416wQAwPftd0ouiswwdJu/CRASkBKQAmYuBzNfWIC/O173W6llwfbeu6Yi8tDsrAQJYGICyGQAIWDO5K" +
"UkaxlcJwAASdSmaWAQHCACOAc4h6YzJi1qWymNNUHlwYcT0JDWXQbACYhGgeh6gHM4Ghuh2/R0YePNia" +
"UCTSmFcvdDCY1paZvhht3nQ2VmGmahICSR5vQHmDt6DcozeZSnp2FdLLZHhwdq94SVd+xMaJqWtrkM2L" +
"1uVHILpy0t8igidymXExfHMzBCQbhCIdga7Onz8etqkdgkUYTZbYCSqORmULlQEIq4J3jyexMA8jdu9B" +
"RzuaKyLN3udkNjDEqICID+2hbm797Wwez24/T3vJTE3aFTP9Sd9vT1NziVEMUGr1c35+Y2b5jKnqgNKq" +
"WglMLspjs6/rj1dudie2mdao07J5s3dCzt/werJTyI1yYqpQAAAABJRU5ErkJggg==) no-repeat 2p" +
"x -34px;\r\n    }\r\n\r\n        /* Set to green check and text when valid */\r\n       " +
" .input-help li.valid {\r\n            color: #3a7d34;\r\n            background-pos" +
"ition: 2px 6px;\r\n        }\r\n\r\n    /* Set submit button */\r\n    form .disn, form." +
"ng-valid .btn[disabled] {\r\n        display: none;\r\n    }\r\n\r\n    form.ng-invalid " +
".btn[disabled], form.ng-valid .btn {\r\n        /*margin-left: 400px;*/\r\n        d" +
"isplay: inline-block;\r\n    }\r\n\r\n    /*body {\r\n padding: 20px 0;   \r\n}*/\r\n    inp" +
"ut {\r\n        width: 166px;\r\n    }\r\n    /*.form-horizontal .control-label {\r\n   " +
" width: 180px;\r\n}*/\r\n    /*.form-horizontal .controls {\r\n  position: relative;\r\n" +
"  margin-left: 200px;\r\n}*/\r\n</style>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"page-title\"");

WriteLiteral(">Change Password</h3>\r\n        <ul");

WriteLiteral(" class=\"page-breadcrumb breadcrumb\"");

WriteLiteral("></ul>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n<script");

WriteLiteral(" id=\"customMessageTemplate\"");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(">\r\n    <span class=\"validationError\" data-bind=\'validationMessage: field\'></span>" +
"\r\n</script>\r\n<div");

WriteLiteral(" class=\"portlet-body\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"table-toolbar\"");

WriteLiteral(">\r\n        <fieldset>\r\n\r\n            <form");

WriteLiteral(" ng-app=\"form-example\"");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(" novalidate>\r\n                <div");

WriteLiteral(" id=\"ChangePassword\"");

WriteLiteral(" data-bind=\"with: changepasswordModel\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-wizard\"");

WriteLiteral(" data-bind=\'validationOptions: { messageTemplate: \"customMessageTemplate\" }\'");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"control-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"controls\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"control-label col-md-5\"");

WriteLiteral(" for=\"inputPassword\"");

WriteLiteral(">User Name:</label>\r\n                                <label");

WriteLiteral(" class=\"control-label displaytxt\"");

WriteLiteral(" data-bind=\"text:$root.Name()\"");

WriteLiteral("></label>\r\n                                 <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"Username\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral("></input>\r\n                                ");

WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"control-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"controls form-group\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"control-label col-md-5\"");

WriteLiteral(" for=\"inputPassword\"");

WriteLiteral(">Current Password:</label>\r\n                                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" class=\"immediate-help form-control\"");

WriteLiteral(" style=\"width: 100%\"");

WriteLiteral(" id=\"currentPassword\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" placeholder=\"Current Password\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" data-bind=\"value: Password\"");

WriteLiteral(">\r\n                                </div>\r\n                            </div>\r\n  " +
"                      </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"control-group\"");

WriteLiteral(">\r\n\r\n                            <div");

WriteLiteral(" class=\"controls form-group\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"control-label col-md-5\"");

WriteLiteral(" for=\"inputPassword\"");

WriteLiteral(">New Password:</label>\r\n                                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" ng-model=\"password\"");

WriteLiteral(" style=\"width: 100%\"");

WriteLiteral(" class=\"immediate-help form-control\"");

WriteLiteral(" password-validate required");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"inputPassword\"");

WriteLiteral(" placeholder=\"New Password\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" data-bind=\"value: NewPassword\"");

WriteLiteral(" oncopy=\"return false\"");

WriteLiteral(" onpaste=\"return false\"");

WriteLiteral(" oncut=\"return false\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"input-help\"");

WriteLiteral(">\r\n                                        <h4>New Password must meet the followi" +
"ng requirements:</h4>\r\n                                        <ul>\r\n           " +
"                                 <li");

WriteLiteral(" ng-class=\"pwdUpperLetter\"");

WriteLiteral(">At least <strong>one upper letter</strong></li>\r\n                               " +
"             <li");

WriteLiteral(" ng-class=\"pwdLowerLetter\"");

WriteLiteral(">At least <strong>one lower letter</strong></li>\r\n                               " +
"             <li");

WriteLiteral(" ng-class=\"pwdHasNumber\"");

WriteLiteral(">At least <strong>one number</strong></li>\r\n                                     " +
"       <li");

WriteLiteral(" ng-class=\"pwdSpecialChar\"");

WriteLiteral(">At least <strong>one special character</strong></li>\r\n                          " +
"                  <li");

WriteLiteral(" ng-class=\"pwdValidLength\"");

WriteLiteral(@">At least <strong>8 characters long</strong></li>

                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div");

WriteLiteral(" class=\"control-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"controls form-group\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"control-label col-md-5\"");

WriteLiteral(" for=\"inputPassword\"");

WriteLiteral(">Confirm Password:</label>\r\n                                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" class=\"immediate-help form-control\"");

WriteLiteral(" style=\"width: 100%\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" placeholder=\"Confirm Password\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" data-bind=\"value: ConfirmPassword\"");

WriteLiteral(" oncopy=\"return false\"");

WriteLiteral(" onpaste=\"return false\"");

WriteLiteral(" oncut=\"return false\"");

WriteLiteral(">\r\n                                </div>\r\n                            </div>\r\n  " +
"                      </div>\r\n                        <div");

WriteLiteral(" class=\"fluid\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row control-group \"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-5\"");

WriteLiteral(">&nbsp;</div>\r\n                                <div");

WriteLiteral(" class=\"controls\"");

WriteLiteral(" style=\"padding: 10px\"");

WriteLiteral(">\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"disn btn btn-xs green\"");

WriteLiteral(" data-bind=\"click: $root.SubmitPassword\"");

WriteLiteral(">Submit</a>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"disn btn btn-xs green\"");

WriteLiteral(" disabled");

WriteLiteral(" data-bind=\"click: $root.SubmitPassword\"");

WriteLiteral(">Submit</a>\r\n                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-xs red\"");

WriteLiteral(" data-bind=\"click: $root.Cancel\"");

WriteLiteral(">Cancel</a>\r\n                                </div>\r\n                            " +
"</div>\r\n                        </div>\r\n\r\n\r\n\r\n                    </div>\r\n      " +
"          </div>\r\n\r\n            </form>\r\n\r\n        </fieldset>\r\n    </div>\r\n</di" +
"v>");

        }
    }
}
#pragma warning restore 1591
