#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/User/Users.cshtml")]
    public partial class _Views_User_Users_cshtml : System.Web.Mvc.WebViewPage<PortKonnect.UserAccessManagement.Domain.DTOS.PrivilegeDTO>
    {
        public _Views_User_Users_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\User\Users.cshtml"
      
    ViewBag.Title = "Users";
    Layout = "~/Views/Shared/_eGateLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 189), Tuple.Create("\"", 251)
, Tuple.Create(Tuple.Create("", 195), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/Model/UserRegistrationModel.js")
, 195), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 271), Tuple.Create("\"", 345)
, Tuple.Create(Tuple.Create("", 277), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Application/UAM/ViewModel/UserRegistrationListViewModel.js")
, 277), false)
);

WriteLiteral("></script>\r\n\r\n");

});

WriteLiteral("\r\n\r\n");

DefineSection("ko_apply", () => {

WriteLiteral("\r\nvar viewModel = new eGateRoot.UserRegistrationListViewModel();\r\nko.applyBinding" +
"sWithValidation(viewModel, $(\"#Users\")[0], { insertMessages: false, messagesOnMo" +
"dified: false, grouping: { deep: true }});\r\n");

});

WriteLiteral("<style>\r\n\t.k-grid-header .k-header {\r\n\t\twhite-space: nowrap;\r\n\t\tline-height: 15px" +
";\r\n\t}\r\n</style>\r\n<!-- BEGIN CONTENT -->\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n\t\t<h3");

WriteLiteral(" class=\"page-title\"");

WriteLiteral("><span");

WriteLiteral(" id=\"spnTitle\"");

WriteLiteral("></span></h3>\r\n\t\t<ul");

WriteLiteral(" class=\"page-breadcrumb breadcrumb\"");

WriteLiteral("></ul>\r\n\t</div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"Users\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" data-bind=\"visible: viewMode() == \'List\', template: { name: \'Users-template\' }\"");

WriteLiteral("></div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"portlet-body\"");

WriteLiteral(">\r\n\r\n\t\t<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"Users-template\"");

WriteLiteral(">\r\n\r\n\t\t\t<div class=\"table-toolbar\">\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<div class=\"portlet box advb" +
"g\">\r\n\t\t\t\t\t\t<div class=\"portlet-title\">\r\n\t\t\t\t\t\t\t<div class=\"caption\">\r\n\t\t\t\t\t\t\t\t<i" +
" class=\"fa fa-search\" aria-hidden=\"true\"></i>Advance Search\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t" +
"\t\t\t<div class=\"tools\">\r\n\t\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"expand\"></a>\r\n\t\t\t\t" +
"\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div class=\"portlet-body\" data-bind=\"with: UserRe" +
"gistrationGridModel\" style=\"display:none;\">\r\n\t\t\t\t\t\t\t<div class=\"form-wizard form" +
"-horizontal\">\r\n\t\t\t\t\t\t\t\t<div class=\"form-body\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t" +
"\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<" +
"label class=\"control-label col-md-4\">User Name:</label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class=" +
"\"col-md-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"SearchUserName\" class=\"form-con" +
"trol\" data-bind=\"value: UserName, event: { keypress: $root.validationHelper.Vali" +
"dateAlphaNumeric }\" maxlength=\"50\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t" +
"\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-grou" +
"p\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label col-md-4\">First Name:</label>\r\n\t\t\t\t" +
"\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"SearchFirstN" +
"ame\" class=\"form-control\" data-bind=\"value: FirstName, event: { keypress: $root." +
"validationHelper.ValidateAlphabetsWithSpaces_keypressEvent }\" maxlength=\"50\">\r\n\t" +
"\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"co" +
"l-md-4\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control" +
"-label col-md-4\">Last Name:</label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n\t\t\t\t\t\t\t" +
"\t\t\t\t\t\t<input type=\"text\" id=\"SearchLastName\" class=\"form-control\" data-bind=\"val" +
"ue: LastName, event: { keypress: $root.validationHelper.ValidateAlphabetsWithSpa" +
"ces_keypressEvent }\" maxlength=\"50\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t" +
"\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\r\n\t\t\t\t\t\t\t\t\t\t<div cla" +
"ss=\"col-md-4\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"c" +
"ontrol-label col-md-4\">Partner Type:</label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">" +
"\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"ddlPartnerType\" name=\"\" class=\"form-control\" data-bin" +
"d=\"options: $root.PartnerTypes, optionsText: \'PartnerTypeName\', optionsCaption: " +
"\'Select...\', optionsValue: \'PartnerTypeId\', value: PartnerType\"></select>\r\n\r\n\r\n\t" +
"\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"co" +
"l-md-4\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control" +
"-label col-md-4\">Is Dormant User?:</label>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n" +
"\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"Checkbox\" id=\"IsDormantUser\" name=\"IsDormantUser\" data" +
"-bind=\"checked: $parent.isDormantUser\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t\t\t\t\t\t\t</div>" +
"\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"f" +
"orm-group \">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label col-md-4\"></label>\r\n\t\t\t\t\t\t" +
"\t\t\t\t\t\t<div class=\"col-md-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-" +
"xs green\" data-bind=\"click: $root.LoadUsers\">Search</button>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<butt" +
"on type=\"submit\" class=\"btn btn-xs blue\" data-bind=\"click: $root.ResetFilters\">R" +
"eset</button>\r\n\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t" +
"\t\t\t</div>\r\n\r\n\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t</div>\r\n\t\t\t" +
"\t</div>\r\n\r\n\t\t\t\t<div id=\"tableheader\">\r\n");

            
            #line 130 "..\..\Views\User\Users.cshtml"
					
            
            #line default
            #line hidden
            
            #line 130 "..\..\Views\User\Users.cshtml"
                     if (Model.HasPrivilege("eGateUserAdd")) //TODO: Need to implment Entity Functions as Enums
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" class=\"button gbtngreen\"");

WriteLiteral(" data-bind=\"click: $root.Adduser \"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-plus\"");

WriteLiteral("></i>&nbsp; <strong>New User</strong> </a>\r\n");

            
            #line 133 "..\..\Views\User\Users.cshtml"
					}

            
            #line default
            #line hidden
WriteLiteral(@"				</div>
				<div id=""Grid2"" data-bind=""kendoGrid: {
	data: UserList,
	groupable: false,
	sortable: true,
	scrollable: true,
	filterable: {
		extra: false, operators: {
			string: {
				startswith: 'Starts with',
				eq: 'Is equal to',
				neq: 'Is not equal to',
				contains: 'Contains',
				doesnotcontain: 'Does not Contain'
			},
			number: { eq: 'Is equal to' }
		}
	},
	rowTemplate: 'rowTmpl',
	useKOTemplates: true,
	columns: [
 { title: 'Actions', width: 50, filterable: false },
        { field: 'UserNameSort', title: 'User Name', width: 70, filterable: true },
        { field: 'FirstNameSort', title: 'First Name', width: 50, filterable: true },
  { field: 'LastNameSort', title: 'Last Name', width: 50, filterable: true },
        { field: 'PartnerTypeSort', title: 'Partner Type', width: 70, filterable: true },
{ field: 'EmailIdSort', title: 'Email Id', width: 70, filterable: true },
        { field: 'ContactNoSort', title: 'Contact No', width: 70, filterable: true },
  { field: 'RecordStatusSort', title: 'Status', width: 40, filterable: true }

	]
}"">
				</div>
				<script id=""rowTmpl"" type=""text/html"">
					<tr>
						<td align=""center"">
							<div class=""nowrap"">
");

            
            #line 171 "..\..\Views\User\Users.cshtml"
								
            
            #line default
            #line hidden
            
            #line 171 "..\..\Views\User\Users.cshtml"
                                 if (Model.HasPrivilege("eGateUserView")) //TODO: Need to implment Entity Functions as Enums
                                {

            
            #line default
            #line hidden
WriteLiteral("                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"View\"");

WriteLiteral(" data-bind=\"click: $parent.ViewUser\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-eye\"");

WriteLiteral("></i></a>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t<a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"Edit\"");

WriteLiteral(" data-bind=\"click: $parent.EditUser\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-edit\"");

WriteLiteral("></i></a>\r\n");

            
            #line 175 "..\..\Views\User\Users.cshtml"

								}

            
            #line default
            #line hidden
WriteLiteral("                                <a href=\"#\" title=\"Reset Password\" data-bind=\"cli" +
"ck: $parent.ResetPassword\">  <span class=\"fa-stack fa-lg\" style=\"width: 1em;\">\r\n" +
"                                        <i class=\"fa fa-key fa-stack-2x\" aria-hi" +
"dden=\"true\" style=\"font-size: 14px;color: #56abef;transform: rotate(-45deg) scal" +
"e(-1,1);\"></i>\r\n                                      <i class=\"fa fa-refresh fa" +
"-stack-1x \" aria-hidden=\"true\" style=\"font-size: 11px;margin-top: 1px;margin-lef" +
"t: 6px;color: #001526;\"></i>\r\n                                    </span></a>\r\n\t" +
"\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t<div class=\"nowrap\"><span data-bin" +
"d=\"text: UserName, attr: { title: UserName }\"></span></div>\r\n\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t" +
"<td>\r\n\t\t\t\t\t\t\t<div class=\"nowrap\"><span data-bind=\"text: FirstName, attr: { title" +
": FirstName }\"></span></div>\r\n\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t<div class=\"nowrap" +
"\"><span data-bind=\"text: LastName, attr: { title: LastName }\"></span></div>\r\n\t\t\t" +
"\t\t\t</td>\r\n\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t<div class=\"nowrap\"><span data-bind=\"text: PartnerT" +
"ype, attr: { title: PartnerType }\"></span></div>\r\n\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t<td>\r\n\t\t\t\t\t" +
"\t\t<div class=\"nowrap\" style=\"word-wrap:break-word;\"><span data-bind=\"text: Email" +
"Id, attr: { title: EmailId }\"></span></div>\r\n\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t<di" +
"v class=\"nowrap\"><span data-bind=\"text: ContactNo, attr: { title: ContactNo }\"><" +
"/span></div>\r\n\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t<div class=\"nowrap\"><span data-bin" +
"d=\"text: RecordStatus\"></span></div>\r\n\t\t\t\t\t\t</td>\r\n\r\n\r\n\r\n\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t</scr" +
"ipt>\r\n\r\n\t\t\t</div>\r\n\t\t</script>\r\n\t</div>\r\n\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
