
Insert into USAM.APPLICATIONENTITYFUNCTION
   (APPLICATIONENTITYID, FUNCTIONCODE, FUNCTIONNAME, FORMURL, ISMENU, 
    MENUORDER, ISDELETED, RECORDSTATUS, CREATEDBY, CREATEDON, 
    UPDATEDBY, UPDATEDON)
 Values
   ('cargoEXShippingBill', 'cargoRotationNoUpdate', 'Rotation No Update', null, 'N', 
    6, 'N', 'A', '1', TO_DATE('06/06/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '1', TO_DATE('06/06/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

Insert into USAM.APPLICATIONENTITYFUNCTION
   (APPLICATIONENTITYID, FUNCTIONCODE, FUNCTIONNAME, FORMURL, ISMENU, 
    MENUORDER, ISDELETED, RECORDSTATUS, CREATEDBY, CREATEDON, 
    UPDATEDBY, UPDATEDON)
 Values
   ('finMSTRProformaInvoice', 'finProformaParkDocDeletion', 'Park Doc Deletion', null, 'N', 
    6, 'N', 'A', '1', TO_DATE('06/06/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '1', TO_DATE('06/06/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

Insert into USAM.APPLICATIONENTITYFUNCTION
   (APPLICATIONENTITYID, FUNCTIONCODE, FUNCTIONNAME, FORMURL, ISMENU, 
    MENUORDER, ISDELETED, RECORDSTATUS, CREATEDBY, CREATEDON, 
    UPDATEDBY, UPDATEDON)
 Values
   ('cargoEXShippingBill', 'cargoLEOEntryUpdate', 'LEO Entry Update', null, 'N', 
    6, 'N', 'A', '1', TO_DATE('06/06/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '1', TO_DATE('06/06/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));


MERGE INTO usam.rolefunction d
USING (SELECT 'Admin' roleid, 'cargoImportGeneralManifestUpdate' FUNCTIONCODE,'N' ISDELETED from dual) s
ON (d.roleid = s.roleid and d.FUNCTIONCODE=s.FUNCTIONCODE)
WHEN MATCHED THEN UPDATE SET d.ISDELETED = s.ISDELETED
WHEN NOT MATCHED THEN INSERT  (ROLEID, APPLICATIONENTITYID, FUNCTIONCODE, ISDELETED, RECORDSTATUS, 
    CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, APPLICATIONID, 
    SUBSCRIBERID)
 Values
   ('Admin', 'cargoIMGeneralManifest', 'cargoImportGeneralManifestUpdate', 'N', 'A', 
    'KPCL', TO_DATE('08/08/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'b8d4d782-ec73-4c93-8b0c-b2989b2825b7', TO_DATE('11/20/2018 17:51:20', 'MM/DD/YYYY HH24:MI:SS'), 6, 
    'KPCL');
	
MERGE INTO usam.rolefunction d
USING (SELECT 'Admin' roleid, 'cargoImportDeliveryOrderUpdate' FUNCTIONCODE,'N' ISDELETED from dual) s
ON (d.roleid = s.roleid and d.FUNCTIONCODE=s.FUNCTIONCODE)
WHEN MATCHED THEN UPDATE SET d.ISDELETED = s.ISDELETED
WHEN NOT MATCHED THEN INSERT  (ROLEID, APPLICATIONENTITYID, FUNCTIONCODE, ISDELETED, RECORDSTATUS, 
    CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, APPLICATIONID, 
    SUBSCRIBERID)
 Values
   ('Admin', 'cargoIMDeliveryOrder', 'cargoImportDeliveryOrderUpdate', 'N', 'A', 
    'KPCL', TO_DATE('08/08/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'b8d4d782-ec73-4c93-8b0c-b2989b2825b7', TO_DATE('11/20/2018 17:51:20', 'MM/DD/YYYY HH24:MI:SS'), 6, 
    'KPCL');	

MERGE INTO usam.rolefunction d
USING (SELECT 'Admin' roleid, 'cargoImportDeliveryOrderRecord' FUNCTIONCODE,'N' ISDELETED from dual) s
ON (d.roleid = s.roleid and d.FUNCTIONCODE=s.FUNCTIONCODE)
WHEN MATCHED THEN UPDATE SET d.ISDELETED = s.ISDELETED
WHEN NOT MATCHED THEN INSERT  (ROLEID, APPLICATIONENTITYID, FUNCTIONCODE, ISDELETED, RECORDSTATUS, 
    CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, APPLICATIONID, 
    SUBSCRIBERID)
 Values
   ('Admin', 'cargoIMDeliveryOrder', 'cargoImportDeliveryOrderRecord', 'N', 'A', 
    'KPCL', TO_DATE('08/08/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'b8d4d782-ec73-4c93-8b0c-b2989b2825b7', TO_DATE('11/20/2018 17:51:20', 'MM/DD/YYYY HH24:MI:SS'), 6, 
    'KPCL');	
	
MERGE INTO usam.rolefunction d
USING (SELECT 'Admin' roleid, 'cargoImportBillofEntryUpdate' FUNCTIONCODE,'N' ISDELETED from dual) s
ON (d.roleid = s.roleid and d.FUNCTIONCODE=s.FUNCTIONCODE)
WHEN MATCHED THEN UPDATE SET d.ISDELETED = s.ISDELETED
WHEN NOT MATCHED THEN INSERT  (ROLEID, APPLICATIONENTITYID, FUNCTIONCODE, ISDELETED, RECORDSTATUS, 
    CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, APPLICATIONID, 
    SUBSCRIBERID)
 Values
   ('Admin', 'cargoIMBillofEntry', 'cargoImportBillofEntryUpdate', 'N', 'A', 
    'KPCL', TO_DATE('08/08/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'b8d4d782-ec73-4c93-8b0c-b2989b2825b7', TO_DATE('11/20/2018 17:51:20', 'MM/DD/YYYY HH24:MI:SS'), 6, 
    'KPCL');

MERGE INTO usam.rolefunction d
USING (SELECT 'Admin' roleid, 'cargoImportBillofEntryRecord' FUNCTIONCODE,'N' ISDELETED from dual) s
ON (d.roleid = s.roleid and d.FUNCTIONCODE=s.FUNCTIONCODE)
WHEN MATCHED THEN UPDATE SET d.ISDELETED = s.ISDELETED
WHEN NOT MATCHED THEN INSERT  (ROLEID, APPLICATIONENTITYID, FUNCTIONCODE, ISDELETED, RECORDSTATUS, 
    CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, APPLICATIONID, 
    SUBSCRIBERID)
 Values
   ('Admin', 'cargoIMBillofEntry', 'cargoImportBillofEntryRecord', 'N', 'A', 
    'KPCL', TO_DATE('08/08/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'b8d4d782-ec73-4c93-8b0c-b2989b2825b7', TO_DATE('11/20/2018 17:51:20', 'MM/DD/YYYY HH24:MI:SS'), 6, 
    'KPCL');	

MERGE INTO usam.rolefunction d
USING (SELECT 'Admin' roleid, 'CargoVesselDeliveryOrderUpdate' FUNCTIONCODE,'N' ISDELETED from dual) s
ON (d.roleid = s.roleid and d.FUNCTIONCODE=s.FUNCTIONCODE)
WHEN MATCHED THEN UPDATE SET d.ISDELETED = s.ISDELETED
WHEN NOT MATCHED THEN INSERT  (ROLEID, APPLICATIONENTITYID, FUNCTIONCODE, ISDELETED, RECORDSTATUS, 
    CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, APPLICATIONID, 
    SUBSCRIBERID)
 Values
   ('Admin', 'cargoIMVesselDeliveryOrder', 'CargoVesselDeliveryOrderUpdate', 'N', 'A', 
    'KPCL', TO_DATE('08/08/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'b8d4d782-ec73-4c93-8b0c-b2989b2825b7', TO_DATE('11/20/2018 17:51:20', 'MM/DD/YYYY HH24:MI:SS'), 6, 
    'KPCL');	

MERGE INTO usam.rolefunction d
USING (SELECT 'Admin' roleid, 'CargoVesselDeliveryOrderRecord' FUNCTIONCODE,'N' ISDELETED from dual) s
ON (d.roleid = s.roleid and d.FUNCTIONCODE=s.FUNCTIONCODE)
WHEN MATCHED THEN UPDATE SET d.ISDELETED = s.ISDELETED
WHEN NOT MATCHED THEN INSERT  (ROLEID, APPLICATIONENTITYID, FUNCTIONCODE, ISDELETED, RECORDSTATUS, 
    CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, APPLICATIONID, 
    SUBSCRIBERID)
 Values
   ('Admin', 'cargoIMVesselDeliveryOrder', 'CargoVesselDeliveryOrderRecord', 'N', 'A', 
    'KPCL', TO_DATE('08/08/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'b8d4d782-ec73-4c93-8b0c-b2989b2825b7', TO_DATE('11/20/2018 17:51:20', 'MM/DD/YYYY HH24:MI:SS'), 6, 
    'KPCL');	
	
MERGE INTO usam.rolefunction d
USING (SELECT 'Admin' roleid, 'finProformaParkDocDeletion' FUNCTIONCODE,'N' ISDELETED from dual) s
ON (d.roleid = s.roleid and d.FUNCTIONCODE=s.FUNCTIONCODE)
WHEN MATCHED THEN UPDATE SET d.ISDELETED = s.ISDELETED
WHEN NOT MATCHED THEN INSERT  (ROLEID, APPLICATIONENTITYID, FUNCTIONCODE, ISDELETED, RECORDSTATUS, 
    CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, APPLICATIONID, 
    SUBSCRIBERID)
 Values
   ('Admin', 'finMSTRProformaInvoice', 'finProformaParkDocDeletion', 'N', 'A', 
    'KPCL', TO_DATE('08/08/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'b8d4d782-ec73-4c93-8b0c-b2989b2825b7', TO_DATE('11/20/2018 17:51:20', 'MM/DD/YYYY HH24:MI:SS'), 6, 
    'KPCL');


MERGE INTO usam.rolefunction d
USING (SELECT 'Admin' roleid, 'cargoShippingBillUpdate' FUNCTIONCODE,'N' ISDELETED from dual) s
ON (d.roleid = s.roleid and d.FUNCTIONCODE=s.FUNCTIONCODE)
WHEN MATCHED THEN UPDATE SET d.ISDELETED = s.ISDELETED
WHEN NOT MATCHED THEN INSERT  (ROLEID, APPLICATIONENTITYID, FUNCTIONCODE, ISDELETED, RECORDSTATUS, 
    CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, APPLICATIONID, 
    SUBSCRIBERID)
 Values
   ('Admin', 'cargoExShippingBillEntry', 'cargoShippingBillUpdate', 'N', 'A', 
    'KPCL', TO_DATE('08/08/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'b8d4d782-ec73-4c93-8b0c-b2989b2825b7', TO_DATE('11/20/2018 17:51:20', 'MM/DD/YYYY HH24:MI:SS'), 6, 
    'KPCL');	
	
MERGE INTO usam.rolefunction d
USING (SELECT 'Admin' roleid, 'cargoRotationNoUpdate' FUNCTIONCODE,'N' ISDELETED from dual) s
ON (d.roleid = s.roleid and d.FUNCTIONCODE=s.FUNCTIONCODE)
WHEN MATCHED THEN UPDATE SET d.ISDELETED = s.ISDELETED
WHEN NOT MATCHED THEN INSERT  (ROLEID, APPLICATIONENTITYID, FUNCTIONCODE, ISDELETED, RECORDSTATUS, 
    CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, APPLICATIONID, 
    SUBSCRIBERID)
 Values
   ('Admin', 'cargoRotationalNo', 'cargoRotationNoUpdate', 'N', 'A', 
    'KPCL', TO_DATE('08/08/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'b8d4d782-ec73-4c93-8b0c-b2989b2825b7', TO_DATE('11/20/2018 17:51:20', 'MM/DD/YYYY HH24:MI:SS'), 6, 
    'KPCL');	

MERGE INTO usam.rolefunction d
USING (SELECT 'Admin' roleid, 'cargoLEOEntryUpdate' FUNCTIONCODE,'N' ISDELETED from dual) s
ON (d.roleid = s.roleid and d.FUNCTIONCODE=s.FUNCTIONCODE)
WHEN MATCHED THEN UPDATE SET d.ISDELETED = s.ISDELETED
WHEN NOT MATCHED THEN INSERT  (ROLEID, APPLICATIONENTITYID, FUNCTIONCODE, ISDELETED, RECORDSTATUS, 
    CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, APPLICATIONID, 
    SUBSCRIBERID)
 Values
   ('Admin', 'cargoExLEO', 'cargoLEOEntryUpdate', 'N', 'A', 
    'KPCL', TO_DATE('08/08/2019 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'b8d4d782-ec73-4c93-8b0c-b2989b2825b7', TO_DATE('11/20/2018 17:51:20', 'MM/DD/YYYY HH24:MI:SS'), 6, 
    'KPCL');
commit;